- src/script/ui/app/toolbar.jsx
- src/script/ui/component/actionmenu.jsx
Fix #4 - "minimum font size" in Chromium
> Remove titles for buttons on toolbar

- gulp/dev-script.js
- gulpfile.js
- package.json
Ketcher will **not** build on newer versions of Node due to the now unsupported Gulp 3 (see below and [here](https://github.com/gulpjs/gulp/issues/2324)). This PR upgrades the **gulpfile.js** to Gulp 4 (see. [Gulp 3 to 4](https://www.sitepoint.com/how-to-migrate-to-gulp-4/)). There are some other things that could be optimised e.g. gulp-util is now [deprecated](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) but not essential and thought'd I see if this PR gets accepted first before suggesting making changes.
Here is the error:
```
[john@harbinger:ketcher]% npx gulp serve
fs.js:27
const { Math, Object } = primordials;
^
ReferenceError: primordials is not defined
at fs.js:27:26
at req_ (/Users/john/Workspace/GitHub/ketcher/node_modules/natives/index.js:143:24)
at Object.req [as require] …
```
> Update to Gulp 4 allow it Ketcher build.

- .vscode/launch.json
- example/config/webpack.config.js
- example/package.json
- example/yarn.lock
- package.json
- rollup.config.js
- src/script/chem/struct/fragment.js
- src/script/ui/component/form/combobox.jsx
- src/script/ui/state/action/index.js
- src/script/ui/state/editor/index.js
- src/script/ui/state/index.js
- yarn.lock
- fix global.state initialization
- add webpack sourcemap loader
- fix issue with stereo label
- add delete rollup plugin
> #97 Prepare ketcher for publishing to NPM part 1

- src/script/editor/tool/rotate.js
- add case if there are no atoms on the canvas
> #136 Rotation is broken if only arrow has been added on canvas

- src/script/ui/dialog/template/template-attach.jsx
- add placeholder to 'Edit template' dialog
> #159 'Template name' field does not contain grey 'tmpl' placeholder

- packages/ketcher-core/src/chemistry/serializers/mol/utils.js
when open a molfile which contain a dative bond, ketcher will be crash
> add `DATIVE` to bondTypeMap

- packages/ketcher-react/package.json
- packages/ketcher-react/src/index.tsx
- packages/ketcher-react/src/script/index.ts
Exports `Ketcher` and `buildKetcherAsync` to allow for subscribing to editor changes.
Example
```tsx
const ref = useRef(null);
const [smiles, setSmiles] = useState("");
useEffect(() => {
if (ref.current) {
buildKetcherAsync({
element: ref.current,
staticResourcesUrl: process.env.PUBLIC_URL,
structServiceProvider: structServiceProvider,
}).then((k) => {
k.editor.subscribe("change", () => {
k.getSmilesAsync(false).then(setSmiles);
});
});
}
}, []);
```
> Export ketcher and buildKetcherAsync

- packages/ketcher-react/src/script/ui/views/toolbars/toolbar.less
Reduce the width of the scrollbar in Firefox
>  #612 Left toolbar is not visible in firefox

- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/RGroup/RGroup.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/Shape/Shape.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/mediaSizes.ts
> #719 'R-Group Label Tool' and 'Shape Eclipse' buttons should not be expanded

- packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/FontControl.tsx
**Now font size applying works the same way as for font styles: all settings resets to default if are chosen before clicking on text field**
> #759 Fixed font size applying behavior

- packages/ketcher-react/src/script/ui/component/structrender.jsx
Fixes issue #900 
This is a patch, further refactoring may be required. This branch adds 3 lines of code that calculate implicit H for a structure right before it is rendered to the table with previews.
It's probably not the best way to fix it, because these same calculations are performed again right after rendering (because we call force update on it):
https://github.com/epam/ketcher/blob/bb1efd45119e13a923d7e0d3b6855a45399264c7/packages/ketcher-react/src/script/ui/component/structrender.jsx#L31-L32
, but the component does not catch this update after mounting.
> #900 Structure previews display hydrogen if settings specify it

- packages/ketcher-react/src/script/ui/dialog/template/template-attach.jsx
Subscribing template edit modal component to global display settings to pass them with other options down to structure editor.
> #900 Template editor respects global display settings

- packages/ketcher-react/src/script/editor/tool/select.ts
Fixes issue #1109 
The problem is with type coercion, atom or bond with id of `0` are coerced to `false` in a logical expression, thus not being considered as non-null.
> #1109 FG correctly detected by doubleclick on atom or bond with Select tool

- packages/ketcher-core/src/application/ketcherBuilder.ts
- packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts
Fixes #1108 , making use of `aromatize-skip-super-atoms` flag implemented in Indigo, [issue 506](https://github.com/epam/Indigo/issues/506).
> #1108 functional groups are not aromatized

- packages/ketcher-core/src/domain/serializers/ket/schema.json
This prevents throwing a validation error when empty `*.ket` file is opened, as described in issue #1137 
However, modal window is not closed if the structure is empty:
https://github.com/epam/ketcher/blob/ab62ab034b444164e30845701aeccf40815ef36f/packages/ketcher-react/src/script/ui/state/shared.js#L133-L143
Please let me know if we _should_ close the modal and maybe treat empty structure as a new structure.
Also worth noting: as of now it is not possible to test this with potential empty struct response from Indigo.
> #1137 Allow empty ket file

- packages/ketcher-react/src/script/ui/state/shared.js
This branch updates behaviour of Open structure modal window when empty structure is loaded.
Now, if user wants:
- to load empty structure as fragment, then modal is closed and Select tool is selected (like after paste).
- to load empty structure as new canvas, then canvas with empty structure is loaded.
> #1137 Close modal on empty file load

- packages/ketcher-polymer-editor-react/jest.config.js
- packages/ketcher-polymer-editor-react/package.json
- packages/ketcher-polymer-editor-react/setupTests.ts
- yarn.lock
This configures jest to include `@testing-library/jest-dom` custom matchers, so we can write tests for React components a little more nicely. 🙂
>  #1140 Configure jest-dom in polymer editor

- packages/ketcher-core/src/application/render/restruct/reatom.ts
Using `fill-opacity` attribute, as FireFox doesn't seem to work with `opacity` for `<tspan>`. Fixes #1163
> #1163 Stereocenter labels color gradient works in FF

- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.module.less
- packages/ketcher-react/src/style/mixins.less
- packages/ketcher-react/src/style/variables.less
- get rid of redundant scrollbars
- apply unified font for textarea
- add rule for scrollbars for mozilla
> #1292 Incorrect horizontal scrollbars in save structure modal window

- packages/ketcher-react/src/script/ui/state/modal/index.js
Updated modalReducer to check whether modal is closed upon receiving `UPDATE_FORM` action.
> #1291 Prevent Check Structure modal from updating its state after being closed

- packages/ketcher-react/src/script/ui/Portal/Portal.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ToolbarMultiToolItem/usePortalStyle.ts
- fix portal container
- fix portal position
> #1325 button group is not presented if ketcher is in a drawer

- packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less
Scrollbar appears because of fixed standard width of dialog and select width that depends on option string length
Set max width for the select itself, options in dropdown can have bigger width, like this (there's a single edge case):
Another option:
- set bigger (not standard) width for data s-group modal (inconsistency with other modals)
> #1312 extra scrollbar in data s-group modal when field name contains long string

- packages/ketcher-react/src/script/ui/dialog/template/template-lib.module.less
- align close button in header
- following mockup was used for mark-up (close button should be instead of hide button)
> #1435 the templates window doesn't match the mockup

- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.module.less
- fix incorrect ratio in preview
- blur is caused by external issues
> #1472 blur structure in the preview tab when saved in pdf

- packages/ketcher-react/src/script/ui/dialog/template/template-attach.jsx
[Issue](https://github.com/epam/ketcher/issues/1554)
Fix: disabled button if name-field is empty, add styles fo disabled button
> #1154 The 'Apply' button in the 'Template edit' window is enabled

- packages/ketcher-core/src/application/ketcher.ts
To check the operation of the recognize method:
have a saved molecule in .png format
convert image to base64 (for example [here](https://www.base64-image.de/))
1. Open ketcher in remote mode
2. Through the browser console, create a blob-object from the image code and make sure that it was created correctly (you can create a Blob URL to check)
3. use ketcher.recognize( blob, ?imago version)
The structure should be returned as an object
> Add recognize method to ketcher API

- packages/ketcher-core/src/application/formatters/formatterFactory.ts
Ketcher started using API call /convert to convert ket format to Daylight SMILES because Indigo supports reagents
> #1723 convert Daylight SMILES using indigo api

- packages/ketcher-core/src/application/editor/editor.types.ts
- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-react/src/script/editor/Editor.ts
> feat: implement addFragment method

- packages/ketcher-core/src/application/formatters/formatterFactory.ts
we have decided to move Daylight SMILES to the backend again for consistency
because loading on the backend
> Daylight SMILES on Indigo

- packages/ketcher-react/src/script/ui/views/modal/components/document/Open/Open.tsx
- packages/ketcher-react/src/script/ui/views/modal/components/document/Open/components/TextEditor.tsx
Added optional attribute `autofocus` for textarea. Added this new attribute in `Open` modal, making text editor focused by default.
> added autofocus attribute for texarea

- packages/ketcher-react/src/script/ui/App/App.tsx
Fix bug #1802: [Refresh the interface when the scroll axis appears again, it will automatically scroll to the bottom ](https://github.com/epam/ketcher/issues/1802)
> #1802 fix set scroll to the top after reloading the page

- packages/ketcher-react/src/script/ui/component/form/input.jsx
- packages/ketcher-react/src/script/ui/component/form/input.module.less
There were `input` selectors lying in the outer-most layer of a `.less` file, which led to overriding other styles when importing the `less` file.
After going through all `.less` files, I found just one file having that problem. I changed the tag selector to its corresponding class selector. I've checked styles that may be affected by my changes to make sure everything works fine.
* Update selector `input` to `.input`
Resolves: #1694
> Fix local `input` styles overriding other styles

- .github/ISSUE_TEMPLATE/bug_report.md
- example/config/webpack.config.js
> #1839 – removed lightweight tag from page title

- packages/ketcher-react/src/script/ui/component/form/input.jsx
- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
It works but we have errors in console
> #1822 – fixing Template-window input focus

- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
Fix ket objects coordinates issue (add text scaling for files, contains reaction arrows).
> #1764 ket objects coordinates issues

- packages/ketcher-core/src/application/formatters/formatProperties.ts
- packages/ketcher-core/src/application/formatters/formatterFactory.ts
- packages/ketcher-core/src/application/formatters/identifyStructFormat.ts
- packages/ketcher-core/src/application/formatters/serverFormatter.ts
- packages/ketcher-core/src/application/formatters/structFormatter.types.ts
- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-react/src/script/ui/action/copyAs.js
- packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx
Implements automatic selection of mol encoding: add "molAuto" to SupportedFormat type and to formatProperties - with { 'molfile-saving-mode': 'auto' } option.
> #1852 Implements automatic selection of mol encoding

- packages/ketcher-core/src/domain/entities/atom.ts
- packages/ketcher-core/src/domain/serializers/mol/common.js
- packages/ketcher-core/src/domain/serializers/mol/v2000.js
When Atom has alias with single quotes, it is parsed as "pseudo". This "pseudo" didn't have corresponding setter, that's why error was shown.
resolves #1894
> #1894 – added support for extra spaces and alias in mol v2000 files

- packages/ketcher-react/src/script/editor/tool/atom.ts
Now atom tool hover Icon disappears if cursor isn't over canvas
fixes #1908
> #1827: fix hover icon

- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/editor/tool/bond.ts
- packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts
Fixed `isSaltOrSolvent` by also considering an abbreviation of structure.
`Struct` now also has `abbreviation` property.
> #1920 Salts and Solvents tab: Abbreviation is expanded after adding to the canvas

- packages/ketcher-react/src/script/ui/dialog/toolbox/sdata.jsx
- packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less
> #1914 Data S-Group: In the window 'S-Group Properties' the names of the radio buttons are displayed without separation

- packages/ketcher-core/src/application/formatters/formatProperties.ts
- packages/ketcher-core/src/application/formatters/formatterFactory.ts
- packages/ketcher-core/src/application/formatters/identifyStructFormat.ts
- packages/ketcher-core/src/application/formatters/structFormatter.types.ts
- packages/ketcher-core/src/domain/services/struct/structService.types.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
- packages/ketcher-react/src/script/ui/utils/fileOpener.js
- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
- packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.types.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
* add cdx format to types
* add check for cdx format
* add magic word for cdx for recognizing on server
* delete magik number
* fix format check
* update indigo to 1.7.3
* fix format check
* clear string from unnecessary info
* clear string from \n symbols from clipboard
* update indigo version
Co-authored-by: Nikita_Vozisov <Nikita_Vozisov@epam.com>
> Backmerge: #1640 add cdx support (#1650)

- packages/ketcher-react/src/script/ui/dialog/template/useSaltsAndSolvets.ts
When nothing is found, then empty object is returned. Then 'Salts and Solvents' property is accessed in this empty object. So that's why application was failing.
closes #1973
> #1973 – App crashes when template dialog is closed and there is text in the search filter

- packages/ketcher-react/src/script/editor/tool/bond.ts
- packages/ketcher-react/src/script/ui/component/structrender.tsx
- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
- packages/ketcher-react/src/script/ui/dialog/template/useSaltsAndSolvets.ts
- packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts
- packages/ketcher-react/src/script/ui/utils/index.ts
- packages/ketcher-react/src/script/ui/utils/renderStruct.ts
Improve performance, when opening Salts and Solvents tab (#1960)
* #1958 Salts And Solvents performance improved: added batches, caching and prerendering
* #1958 – moved salts and solvents logic to hook
> Backmerge:  #1958 Improve performance, when opening Salts and Solvents tab

- packages/ketcher-core/src/application/formatters/formatProperties.ts
- packages/ketcher-core/src/application/formatters/formatterFactory.ts
- packages/ketcher-core/src/application/formatters/identifyStructFormat.ts
- packages/ketcher-core/src/application/formatters/structFormatter.types.ts
- packages/ketcher-core/src/domain/services/struct/structService.types.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
– Added check for molV2000 format
– CDX format is recognised by header "VjCD0100"
– If no format is recognised, then new "unknown" format is returned
closes #1986
> #1986 – SMILES: Pasting structure with small letters throw an error

- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
Added selection removal on mouseup.
When passing `null` to `editor.selection` it just left the previous selection and didn't actually reset selection.
closes #1955
> #1955 – Selection tool: The highlight of structure, abbreviation is not reset when clicking on the canvas

- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
… hot key (e.g. 'C','S','O','N') Ketcher crashes
Closes #1984
> #1984: Hot key: If a 'Hand tool' is selected, then when you press any hot key (e.g. 'C','S','O','N') Ketcher crashes

- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
… hot key (e.g. 'C','S','O','N') Ketcher crashes (#2013)
> #1984: Hot key: If a 'Hand tool' is selected, then when you press any hot key (e.g. 'C','S','O','N') Ketcher crashes (#2013)

- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
> #2020: When hovering over a functional group for the first time a lot of errors are generated in console

- packages/ketcher-standalone/package.json
- yarn.lock
> #2015: Migrate to Indigo v1.9.0-rc.2 in-browser module

- packages/ketcher-react/src/templates/fg.sdf
…eview 'Boc' is displayed as 'Bn'
> Backmerge: #1998: Functional Groups: The abbreviation and hovering preview 'Boc' is displayed as 'Bn'

- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
… time a lot of errors are generated in console
> Backmerge: #2020: When hovering over a functional group for the first time a lot of errors are generated in console

- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
- packages/ketcher-react/src/script/ui/dialog/template/template-lib.module.less
- packages/ketcher-react/src/script/ui/state/templates/index.js
Closes #1942
1. The search filter reset when the 'Custom Templates' window is closed.
2. The last opened tab shown when you re-open the modal window.
3. Fixed styles for 3th tab
> #1942 Automatically reset the search filter when the 'Custom Templates' window is closed

- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
> hotfix: #1942 Automatically reset the search filter when the 'Custom Templates' window is closed

- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
Fix getFunctionalGroupByName - so that it doesn't return first functionalGroup for empty searchName;
Show name=value pair on hover for 'DAT' sGroup (and nothing - for other sGroup types):
inside InfoPanel - check if groupStruct is null and there is sGroup and sGroup.type is 'DAT' - render div with sGroup name and value.
> #1999 S-group: hover over the s group displays always acetaldehyde

- packages/ketcher-react/src/script/editor/tool/reactionmap.ts
fixed #2011 
- fixed ci that returns null
- remove validation as we needn't it any more because we no longer have restrictions on the direction/numbers of the arrows from the reactant to the product or from node to node of the structure
> #2011 Reaction Mapping Tool: Manual mapping of atoms does not work

- packages/ketcher-react/src/script/ui/state/handleHotkeysOverAtom.ts
- packages/ketcher-react/src/script/ui/state/hotkeys.ts
Changed behaviour of "Select" tool hotkey: now it ignores hovering status and acts consistently in all cases.
Solves #2035
> #2035 Changing the logic of interaction with the 'Selection tool' hotkey

- packages/ketcher-core/src/domain/serializers/mol/molfile.ts
According to the specification in the CTFileformats, p.46, the atom symbol of the list entry should be in the field of width 4.
So, if an atom's symbol consists of one letter, it should have three spaces after it.
If an atom's symbol consists of two letters, it should have three spaces after if.
Steps to verify:
1. Click the PT button under the atom's panel on the right
2. In the opened Periodic Table modal select 'List' radio button at bottom
3. Select any atoms
4. Click 'Add'
5. Click on the canvas to place the atom
6. Click the 'Save' icon on the instrument panel at the top of the page
7. In the opened 'Save Structure' modal inspect the line after the letters 'M  ALS'
8. If an atom's symbol consists of 1 letter, it should have 3 spaces after it, if an atom's symbol consists of 2 …
> #2003 MDL Molfile v2000: Incorrect padding for M ALS

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/atom.ts
When clearing canvas `Visel`s (Visual Elements) are cleared. Because of this, DOM representation of hoverIcon was removed, despite having a reference. Fix – after clearing canvas this icon is recreated.
In addition, last cursor position is saved. This is done due to inability to get mouse cursor position at random time (only in mouse-event handlers). Previous behaviour led to showing a part of atom at top-left corner ((0,0) coordinates) and atom wasn't shown immediately at mouse cursor.
Now, last cursor position is used, when we use a shortcut for atoms.
closes #2028
> #2028 Hotkey: Atom symbols are not displayed under mouse cursor while mouse hovers over the canvas

- packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo/enhancedStereo.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ExternalFuncControls.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.tsx
- Moved enhanced stereochemistry icon to left toolbar
- Fixed enhanced stereochemistry dialog radio buttons not activating properly
Resolves #2057
> #2057 Move enhanced stereochemistry icon to left toolbar

- packages/ketcher-react/src/script/ui/state/hotkeys.ts
Prevent implicit picking next tool in a group when hovering over a shape.
Related to #1826 
Resolves #2038
> #2038: Charge Tool Hot key: Pressing the hot button (5) on an atom applies the opposite charge

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
Now selection tool does not break when cursor leaves canvas.
Fixes #2060
> #2060: Don't break the selection if the user's cursor goes beyond the canvas

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenu.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/AtomBatchOperations.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/AtomSingleOperations.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/BatchDelete.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/BondBatchOperations.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/BondSingleOperations.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/utils.ts
Resolves #1995 #2083 
1. Context menu for one bond (looks a bit weird, seems we need to add icons for _Edit_, _Query bonds_ and _Delete_)
2. Context menu for one atom
3. Context menu for selection
> #1995 bond context menu move non query bonds to 1st level add dots to edit item & #2083 Error when deleting stereo bond via context-menu

- packages/ketcher-react/src/script/editor/tool/template.ts
- Fixed wrong false check on template insertion.
- Resolves #2045
> #2045: Functional Groups: The functional group is not added to one of the H3C

- packages/ketcher-react/src/script/ui/component/form/input.tsx
Removed `innerRef` from checkbox input element.
Resolves #2084
> #2084: When we double click on the selected atom we get error in console

- packages/ketcher-core/src/application/render/raphaelRender.js
- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
- packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx
- packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts
> #2043: Thumbnail images are not readable in Template Dialog

- packages/ketcher-react/src/script/editor/tool/sgroup.ts
- Fixed the check if atoms are selected
- Resolves #2104
> #2104: JS error is thrown, when clicking on a canvas after right click on a bond with "Data S-Group" tool selected

- packages/ketcher-core/src/application/editor/actions/rotate.ts
- packages/ketcher-core/src/application/editor/actions/utils.ts
- packages/ketcher-react/src/script/ui/action/flips.ts
Fixes a case, when only bonds are selected.
closes #1889
> #1889 – Add ability to flip a part of structure

- packages/ketcher-core/src/application/editor/actions/atom.ts
- packages/ketcher-core/src/application/editor/actions/closelyFusing.ts
- packages/ketcher-react/src/script/editor/Editor.ts
Fixes a big issue with valence validation upon merging structures.
Previously validation was performed atom by atom alongside other modifications, which resulted in miscalculations when taking into account atoms that were queued for deletion.
Now it is performed separately, after all merges complete, and takes into account all connected atoms in case structure is changed.
Resolves #2047
> #2047: Templates: When the structure is pasted or dragged on each other, carbon atoms are highlighted

- packages/ketcher-react/src/script/editor/tool/sgroup.ts
> #2129: Adding custom s-groups to bonds incorrectly selects atoms instead of the bond by default

- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/ui/state/editor/index.js
> #2130: Custom Templates: When drag an abbreviation preview is not hide

- packages/ketcher-standalone/package.json
- yarn.lock
> #2146: Migrate to Indigo v1.10.0-rc.2 in-browser module

- packages/ketcher-core/src/application/render/restruct/resgroup.js
- packages/ketcher-core/src/domain/entities/sgroup.ts
This PR resolves #2033 #899:
Abbreviations: Atoms protrude beyond the expanded view for Functional Groups and Salts and Solvents
> #2033: Abbreviations: Atoms protrude beyond the expanded view

- packages/ketcher-core/__tests__/domain/serializers/ket/KetSerializer.test.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- packages/ketcher-core/src/domain/serializers/ket/schema.json
- packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts
- packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts
Resolves: #2142 
Now in a ket file, all S-Groups either exist on the top layer (new version) or in the molecules (old version but compatible), which means there's no chance that some S-Groups exist on the top layer and some exist in the molecules.
More details: https://excalidraw.com/#json=EBblE5uf7cDbf7WO5-iSU,aqAVNKUKnIKF3EZUtjXVsA
> #2142 S-Groups get lost when saving as ket file

- packages/ketcher-react/src/script/ui/state/handleHotkeysOverAtom.ts
- packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
- packages/ketcher-react/src/script/ui/state/hotkeys.ts
- Revamped hotkey tool handler on hover.
- Resolves #2026
> #2026 - Erase tool: Hotkey (Del) can't delete arrows and plus sign

- packages/ketcher-react/src/script/editor/tool/eraser.ts
- packages/ketcher-react/src/script/editor/tool/template.ts
This PR resolves #2195: When you click one Functional Group on another there is no replacement
+small refactor in eraser tool to get rid of duplicated object
> #2195: When you click one Functional Group on another there is no replacement

- packages/ketcher-react/src/script/editor/tool/apoint.ts
- packages/ketcher-react/src/script/editor/tool/eraser.ts
- packages/ketcher-react/src/script/editor/tool/hand.ts
- packages/ketcher-react/src/script/editor/tool/reactionmap.ts
- packages/ketcher-react/src/script/editor/tool/reactionplus.ts
- packages/ketcher-react/src/script/editor/tool/reactionunmap.ts
- packages/ketcher-react/src/script/editor/tool/rgroupatom.ts
- packages/ketcher-react/src/script/editor/tool/rgroupfragment.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
- packages/ketcher-react/src/script/editor/tool/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/simpleobject.ts
Event wasn't passed for `editor.hover` everywhere. Without an event it is not possible to determine coordinates of mouse and show a tooltip at correct position.
closes #2210
> #2210 – label does not appear when hovering on created S-Group

- packages/ketcher-react/src/script/editor/tool/eraser.ts
- packages/ketcher-react/src/script/editor/tool/template.ts
+ small refactor in eraser tool to get rid of duplicated object
closes #2195
> Backmerge: #2195 - When you click one Functional Group on another there is no replacement (#2218)

- packages/ketcher-core/__tests__/domain/entities/pile.test.ts
- packages/ketcher-core/__tests__/domain/serializers/ket/KetSerializer.test.ts
- packages/ketcher-core/src/domain/entities/pile.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- packages/ketcher-core/src/domain/serializers/ket/schema.json
- packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts
- packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts
- packages/ketcher-standalone/package.json
- yarn.lock
* Revert "#2142: s groups get lost when saving as ket file (#2191)"
This reverts commit 289295397f769404afcf0519a540fa38ecf9c197.
* Fix S-Groups which combines multiple molecules getting lost when saving as ket file
* #2142 – updated indigo version to 1.10.0-rc.3
---------
closes #2142
> Backmerge: #2142 s groups that combine multiple molecules get lost when saving as ket file (#2219)

- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/template.ts
> #2229: Bond between Functional Group and structure disappears after adding Functional Group again

- packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts
* #2228 – There are freezes in application when Chrome DevTools are opened
* #2228 – changed throttle to debounce; fixed issue of InfoPanel appearing at (0;0) coordinates
closes #2228
> Backmerge: #2228 – There are freezes in application when Chrome DevTools are opened (#2232)

- packages/ketcher-react/src/script/editor/tool/template.ts
> #2227: Click and drag rotation is not working for Templates toolbar structures

- packages/ketcher-react/src/script/editor/tool/template.ts
> Backmerge: #2227: Click and drag rotation is not working for Templates toolbar structures

- packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
Hotfix for https://github.com/epam/ketcher/issues/2241
Resolves #2264
> Backmerge: #2264: Template menu tab and content differs

- packages/ketcher-core/src/application/render/restruct/rebond.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-react/src/script/editor/shared/closest.js
- packages/ketcher-react/src/script/editor/tool/eraser.ts
- packages/ketcher-react/src/script/editor/tool/helper/locate.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/editor/tool/sgroup.ts
> #1953 The bond between two Functional Group abbreviations disappears

- packages/ketcher-core/src/application/render/restruct/rebond.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-react/src/script/editor/shared/closest.js
- packages/ketcher-react/src/script/editor/tool/eraser.ts
- packages/ketcher-react/src/script/editor/tool/helper/locate.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/editor/tool/sgroup.ts
> Backmerge: #1953 The bond between two Functional Group abbreviations disappears

- packages/ketcher-react/src/hooks/useClickOutside.ts
- packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/FontControl.tsx
- implemented hook useClickOutside
- created ref wrapperRef to handle click out side dropdown
> #2173 Font size drop down does not collapse

- packages/ketcher-core/src/application/editor/actions/erase.ts
Backmerge of https://github.com/epam/ketcher/pull/2283
> Backmerge: #2266 Atom click on Functional Groups/Salts and Solvents doesn't replace them it forms a scattering of atoms

- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
- packages/ketcher-react/src/script/ui/views/components/StructEditor/SGroupDataRender.tsx
- packages/ketcher-react/src/script/ui/views/components/StructEditor/WrapperPositionedRelativeToRectangle.tsx
- packages/ketcher-react/src/script/ui/views/components/StructEditor/helpers.ts
For now it calculates according to the green rectangle that appears when user hovering over the element. Function calculateMiddleCoordsForRect calculate middle coord for each side of the rect. After that panel appears relativly to the middle point of side.
Panel info is always in the bottom if it is center of the page.
Close to borders
- created WrapperPositionedRelativeToRectangle component.
- moved calculateScrollOffsetX , calculateScrollOffsetY into helpers.ts to reduce code duplication
- created calculateMiddleCoordsForRect accepts array of arrays [[1,2], [3,4], [3,4]] => [{ x: 2, y: 3 }, { x: 3, y: 4}]
- added wrapperRef on div to get dinamically changed width / height of the element
> #2216 S-Group pop-up tool tip is positioned so that it overlaps structure

- packages/ketcher-react/src/script/editor/tool/atom.ts
- packages/ketcher-react/src/script/editor/tool/attach.ts
- packages/ketcher-react/src/script/editor/tool/bond.ts
- packages/ketcher-react/src/script/editor/tool/charge.ts
- packages/ketcher-react/src/script/editor/tool/reactionmap.ts
- packages/ketcher-react/src/script/editor/tool/reactionunmap.ts
- packages/ketcher-react/src/script/editor/tool/rgroupatom.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
- packages/ketcher-react/src/script/editor/tool/sgroup.ts
This PR resolves #2123 
Fixed by removing hover reset call from click handlers
> #2123: Hover effect doesn't appear after clicking on bonds or atoms

- packages/ketcher-react/src/script/editor/tool/atom.ts
> #2295 – Atom under mouse cursor does not disappear when cursor crosses bottom and right boundaries of canvas

- packages/ketcher-react/src/script/editor/tool/atom.ts
> Backmerge: #2295 – Atom under mouse cursor does not disappear when cursor crosses bottom and right boundaries of canvas (#2357)

- packages/ketcher-core/src/application/render/raphaelRender.js
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
- packages/ketcher-react/src/script/editor/tool/template.ts
> Backmerge: #2325 – When user hovers cursor with any template selected near the border of the canvas scrollbars appear (#2346)

- packages/ketcher-react/src/script/ui/action/zoom.js
> #2353 – CTRL+SHIFT+0 hotkey not working for 'Zoom 100%'

- packages/ketcher-react/src/script/ui/action/zoom.js
> Backmerge: #2353 – CTRL+SHIFT+0 hotkey not working for 'Zoom 100%' (#2364)

- packages/ketcher-core/src/application/editor/actions/utils.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useAtomStereo.ts
**Ticket**
https://github.com/epam/ketcher/issues/2368
- changed logic findStereoAtoms function to prevent crash of the application
- prevent to show ContextMenu in case if we do not have atoms and bonds
> #2368 When you select Stereo flag label and make right click application crashes

- packages/ketcher-core/src/application/editor/actions/utils.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useAtomStereo.ts
**Ticket**
https://github.com/epam/ketcher/issues/2368
- changed logic findStereoAtoms function to prevent crash of the application
- prevent to show ContextMenu in case if we do not have atoms and bonds
> Backmerge: #2368 When you select Stereo flag label and make right click application crashes

- packages/ketcher-react/src/script/editor/tool/template.ts
> Backmerge: #2326 - Functional Groups forms a bond instead of a replacement (#2363)

- packages/ketcher-react/src/script/editor/tool/template.ts
- packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
closes #2362 
1) Added condition group.hovering. It triggers and becomes active when you hover over an element. Condition solves the problem, that tooltip is visible when the cursor moves. (Remove appearance of a tooltip under mouse cursor) 
Now tooltip is visible when you hover the element. 
2) Added hover method in case Salt Or Solvent . It helps to show the tooltip when event "mouse up" appears
> #2362 Remove appearance of a tooltip under mouse cursor for Functional Groups/Salts and Solvents abbreviations 

- packages/ketcher-core/src/domain/constants/elementColor.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/HoverIcon.ts
- packages/ketcher-react/src/script/editor/tool/atom.ts
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
> Backmerge: #2390 – Selected atom is not displayed under cursor during structure loading (#2406)

- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/ui/data/convert/structconv.js
- packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/state/editor/utils/generateCommonProperties.ts
- packages/ketcher-react/src/script/ui/state/editor/utils/index.ts
- packages/ketcher-react/src/script/ui/state/modal/atoms.ts
- packages/ketcher-react/src/script/ui/state/modal/bonds.ts
- packages/ketcher-react/src/script/ui/state/modal/utils/index.ts
- packages/ketcher-react/src/script/ui/state/modal/utils/updateOnlyChangedProperties.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useBondEdit.ts
closes https://github.com/epam/ketcher/issues/2246
> #2246 Multiple bond editing changes bond types to all selected bonds

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/utils/canvasExtension.ts
> Backmerge: #2446 – Structures are drawn outside the viewbox, when changing rendering options (#2448)

- packages/ketcher-core/src/application/render/canvasExtension.ts
- packages/ketcher-core/src/application/render/index.ts
- packages/ketcher-core/src/application/render/raphaelRender.js
- packages/ketcher-react/src/script/editor/tool/select.ts
closes #2427 
* #2427 – prevented canvas size decrease
> Backmerge: #2427 – When moving a structure outside of the canvas, structure does not move smoothly

- packages/ketcher-react/src/script/editor/tool/atom.ts
> #2402 Atom under mouse cursor on click and drag freezes on canvas if you move cursor away from dragged atom

- packages/ketcher-core/src/application/render/raphaelRender.js
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/ui/component/form/input.tsx
> #2482 – Ketcher with iFrame loads with scrollbars activated

- packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
Closes [#2442](https://github.com/epam/ketcher/issues/2442)
In this case we are catching actions while hovering items, but we handle just tools and dialogs ignoring others. That's why we need to add handler for others actions
> #2442 When mouse hovering on atom or bond hotkey CTRL+Z (Undo) is not working

- packages/ketcher-core/src/application/render/options.js
- packages/ketcher-core/src/application/render/restruct/index.ts
- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/domain/entities/atom.ts
- packages/ketcher-react/src/script/ui/data/schema/options-schema.ts
Closes #2245 
Notice: This PR adds implicit _H_ to _D_ and _T_ according to the issue description. The red underline will show if the number of linked bonds is more than one.
> #2245 Settings: `Terminal and Hetero` is not selected as default and `on` option is not working

- packages/ketcher-core/__tests__/application/editor/actions/bond.test.ts
- packages/ketcher-core/src/application/editor/actions/atom.ts
- packages/ketcher-core/src/application/editor/actions/bond.ts
- packages/ketcher-core/src/application/editor/actions/chain.ts
- packages/ketcher-core/src/application/editor/actions/template.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/atom.ts
- packages/ketcher-react/src/script/editor/tool/bond.ts
- packages/ketcher-react/src/script/editor/tool/chain.ts
- packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
- Resolves: #2257 
- Refactors `fromBondAddition`
Notice: this PR also fixes another 3 bugs of Bond Tool:
https://user-images.githubusercontent.com/27288153/233392678-ee54ec42-e1c4-4761-a41c-273dd5cb1b9a.mp4
https://user-images.githubusercontent.com/27288153/233393118-718617ac-c414-4116-a0cf-383e48123460.mp4
https://user-images.githubusercontent.com/27288153/233400508-6c210a51-aca7-422c-8983-37b2de2f0612.mp4
> #2257 Unable to add a bond to a functional group by bond tool

- packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
> Backmerge: #2502 – It is not possible to scroll to the top of a structure pasted partially outside a canvas (#2506)

- packages/ketcher-core/src/application/editor/actions/erase.ts
> Backmerge: #2528 – Erase tool does not completely remove the Functional Groups if it selecting via the hot key CTRL + A (#2536)

- packages/ketcher-react/src/constants.ts
- packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
> Backmerge: #2420 - Hotkey (Del) can't delete Functional Groups and Salts abbreviation

- packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
- packages/ketcher-react/src/script/ui/utils/renderStruct.ts
- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
closes #2548
S-Group doesn't contain its underlying struct (needs to be refactored), so as a simple fix I've added construction of `Struct` from its atoms and bonds.
> #2548 – If name of Superatom matches abbreviation in Custom Templates, then tooltip is shown on hover

- packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
- packages/ketcher-react/src/script/ui/utils/renderStruct.ts
- packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
> Backmerge: #2548 – If name of Superatom matches abbreviation in Custom Templates, then tooltip is shown on hover (#2563)

- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useFunctionalGroupEoc.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/FunctionalGroupMenuItems.tsx
if sgroup has more than 1 attachment point, we should expand sgroup. I made this logic for paste tool. "Expanded" function invokes in 2 places: 
1) constructor - in that case we firstly render struct from paste and after what we make expand sgroup
2) mouse move - I can't invoke function "setExpandSGroup" because struct and editor have absolutely different id for atoms and sgroups.  I create array sGroupsIdExpanded with id "s groups" which need to be expanded and put this array in "fromPaste" function. if id sgroup  is exist in "sGroupsIdExpanded" than field expanded = true
https://user-images.githubusercontent.com/100932091/235716156-d8c4d236-a5e0-4022-87fe-27de1426e979.mov
> Backmerge: #2517 File with Superatom opens without part of structure

- packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts
> #2273 When user selects and moves atom on Functional Group or Salt it doesn't replaces atom in the structure

- packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts
> Backmerge: #2273 - When user selects and moves atom on Functional Group or Salt it doesn't replaces atom in the structure

- packages/ketcher-react/src/script/ui/action/index.js
Actions ordering was changed in clear action, reused removeStructAction.
> #2483:  Pressing Clear Canvas with Reaction Arrow under mouse cursor causes errors in DevTool console

- packages/ketcher-react/jest.config.js
- packages/ketcher-react/src/script/ui/component/form/colorPicker/ColorPicker.test.js
- packages/ketcher-react/src/script/ui/component/view/SaveButton.test.tsx
- packages/ketcher-react/src/script/ui/component/view/savebutton.tsx
- packages/ketcher-react/src/setupTests.ts
* Fix `disabled` prop for `SaveButton` component
* Add tests for `disabled` prop
> #2196 - the Save button is active for empty canvas

- packages/ketcher-react/src/script/ui/state/hotkeys.ts
* Remove opening Label Editor when pressing hot keys
> #2490 - When atoms are selected, pressing atoms hotkey opens a modal window instead of an instant replacement

- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.module.less
- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/RightToolbar.tsx
Closes #2512
Details:
1) I have set the visibility threshold for the "scroll up" and "scroll down" reference elements to 1 (100%). This means that we consider the reference element as visible only when the entire element is within the view area. 
2) To address potential issues with the right toolbar, I have extracted the first basic atom into a separate element. This allows us to link the "scroll up" reference to a single button. If we were to leave the reference on the entire "atoms list" group, it could cause problems when the height values are low. In such cases, the height of the "atoms list" group would be greater than the actual view area height, resulting in the "scroll up" toolbar arrow persisting permanently.
3) The "arrow scroll" component appears only when the height of the …
> #2512 Toolbar arrow is active after the Ketcher with iFrame is loaded and disappears when you click on it

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.test.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
- packages/ketcher-react/src/script/ui/action/index.js
Closes #2463 
Note: 
1. According to UX design, the predefined degrees will be hidden if the radius is less than 65px.
~~2. One **existing** implementation that needs attention is **15° is the smallest rotation degree**, which means the user cannot rotate like 13° or 34° etc.~~
~~[rotation-2463-02](https://user-images.githubusercontent.com/27288153/236608057-12083049-3bf8-421d-b8ff-3770e8cd00ea.gif)~~
> #2463 Rotation Tool: display predefined rotation angles and current angle

- packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
Closes: #2583 
- It shouldn't be moved if selected structures are connected with any other non-selected ones.
- It should reset to default if dropping center out of canvas' bounding
- It should reset to default after finishing rotating
> #2583 - Rotation tool: ability to move the center of rotation

- packages/ketcher-core/src/domain/entities/struct.ts
> #2614 – Contracted unknown superatom is parsed as expanded, and brackets with name are lost

- packages/ketcher-core/src/domain/entities/struct.ts
> Backmerge: #2614 – Contracted unknown superatom is parsed as expanded and brackets with name are lost (#2615)

- packages/ketcher-core/src/application/ketcher.ts
> #2619 - Add ketcher api method getCDXml() for retrieving molecule in CDXml format

- demo/package.json
- example/package.json
- package.json
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/contextMenu.types.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/AtomMenuItems.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/BondMenuItems.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/FunctionalGroupMenuItems.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/SelectionMenuItems.tsx
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/utils.test.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/utils.ts
* Show context menu for the closest item only if there is no selected item(s)
* Show context menu for a selection only if a user clicked on an item included in the selection
* Otherwise reset the current selection and show the context menu for the closest item
* Clear selection if a user clicks RMB outside of selection and other items
* Remove parentheses from menu items for General selection context menu
* Show "Edit selected atom..." menu item if atoms and something except bonds and Functional Groups are selected
* Show "Edit selected bonds..." menu item if bonds and something except atoms and Functional Groups are selected
> #2576 - Right click menu shown for highlighted functional group instead of clicked

- packages/ketcher-react/src/script/editor/tool/template.ts
- packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.module.less
- packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx
* Add lazy loading for miew-react
* Fix build errors if any
> #2655 - Add dynamic load for Miew (#2661)

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useFunctionalGroupEoc.ts
> #2624 - Rotation tool: incorrect selection box for s-groups

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useFunctionalGroupEoc.ts
> Backmerge: #2624 - Rotation tool: incorrect selection box for s-groups (#2674)

- packages/ketcher-react/src/script/editor/tool/rotate-controller.test.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
- packages/ketcher-react/src/script/editor/tool/select.ts
- packages/ketcher-react/src/script/ui/state/hotkeys.ts
Closes #2625 
1. History stack shouldn't be changed after reverting rotation
2. The reverted structure should stay selected
> #2625 Rotation tool: cancel rotation by pressing "Escape" key

- packages/ketcher-core/src/application/editor/actions/rotate.ts
- packages/ketcher-core/src/application/editor/operations/OperationType.ts
- packages/ketcher-core/src/application/editor/operations/Text/TextMove.ts
- packages/ketcher-core/src/application/editor/operations/rxn/RxnArrowRotate.ts
- packages/ketcher-core/src/application/editor/operations/rxn/index.ts
- packages/ketcher-core/src/application/operations/operations.types.ts
- packages/ketcher-core/src/application/render/restruct/visel.js
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.test.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
Closes #2680 
Add support to rotate the selected reaction arrows, reaction pluses, and texts.
Notice that if only one reaction plus or text is selected, the rotation handle will not show up. However, it will show up if only one reaction arrow is selected, see:
> #2680 Reaction arrow and text don't rotate with rotated objects

- packages/ketcher-core/src/application/render/renderStruct.ts
> Backmerge: #2719 – Preview images for Functional Groups and Salts and Solvents are less readable (#2724)

- packages/ketcher-core/src/domain/serializers/ket/schema.json
closes #2766 
Ketcher failed to validate a response from Indigo, because field "fieldName" was absent.
Removing "fieldName" from required fields as according to Molfile specification it is optional field.
> #2766 – Can not open .rxn files with S-Group properties

- package-lock.json
- packages/ketcher-react/src/script/editor/tool/rotate-controller.test.ts
- packages/ketcher-standalone/package.json
> #2738 – Migrate to Indigo v1.12.0-rc.2 in-browser module

- packages/ketcher-react/src/script/editor/tool/select.ts
Closes #2753 
fix: double-clicking on atoms or bonds to open edit modals
> #2753 Snap arrows to horizontal and vertical orientation

- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
- packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/BottomToolbar/BottomToolbar.container.ts
- packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/RightToolbar.container.ts
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
closes #2803 
closes #2809 
Moved reference type variables to upper scope to prevent unnececessary rerenders
In addition, added selectors for components, which rerendered due to variables with referenced type
> #2803 – When user moves mouse, there is a constant update in the '3D Viewer' window

- packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
> Backmerge: #2812 – Tooltip for Data S-Group does not appear

- packages/ketcher-core/src/application/editor/actions/paste.ts
Closes #2810 
- fixed expanded property calculation for sgroups during mousemove of paste tool
> #2810 Part of the structure disappears when opening a contracted Superatom with multiple connection points

- packages/ketcher-core/src/application/editor/actions/paste.ts
Closes #2810
- fixed expanded property calculation for sgroups during mousemove of paste tool
> Backmerge: #2810 - Part of the structure disappears when opening a contracted Superatom with multiple connection points

- packages/ketcher-react/src/script/ui/state/moveSelectedItems.ts
closes #2825 
Mixed up `x` and `y` axis for finding the most left/right atoms
and `<` and `>`for finding the most top/bottom atoms
> #2825 – The structure when moving with arrows on the keyboard disappears beyond the edges of canvas

- packages/ketcher-core/src/application/render/restruct/resgroup.js
Closes #2806 
- added highlighting prevention if sgroup selected
https://github.com/epam/ketcher/assets/14859362/aa26728a-c174-4829-9b32-cba8cc80b7c2
> Backmerge: #2806 All inner space of selected Functional Group is highlighted if structure selected via CTRL+A

- packages/ketcher-core/src/application/render/restruct/resgroup.js
Closes #2806 
- added highlighting prevention if sgroup selected
https://github.com/epam/ketcher/assets/14859362/aa26728a-c174-4829-9b32-cba8cc80b7c2
> #2806 All inner space of selected Functional Group is highlighted if structure selected via CTRL+A

- packages/ketcher-core/src/application/editor/actions/rotate.ts
- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-core/src/application/render/restruct/retext.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
closes #2805 
* #2805 - fix Horizontal and vertical flips
* #2805 - refactor restruct getSelectionRotationCenter and getVBoxObj
> Backmerge: #2805 horizontal and vertical flips are working incorrectly (affect position) with some atoms, texts and functional groups (#2827)

- packages/ketcher-react/src/script/ui/state/moveSelectedItems.ts
> Backmerge: #2825 – The structure when moving with arrows on the keyboard disappears beyond the edges of canvas (#2846)

- packages/ketcher-core/src/application/render/restruct/reatom.ts
> Backmerge: #2865 – Incorrect display of carbon in attachment points for functional groups (#2871)

- packages/ketcher-core/src/application/render/restruct/reatom.ts
> Backmerge: #2864 – Incorrect display angle of attachment points for functional groups (#2866)

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
Closes #2128 
- added method in editor to zoom according content
- added this method execution after drawing opened structure
https://github.com/epam/ketcher/assets/14859362/a5b3fa6e-99eb-4d2a-be0f-39b2b80401b0
> #2128 Automatically adjust zoom when opening a structure

- packages/ketcher-react/src/script/ui/component/form/Input/Input.tsx
Fix the following warning in development environment:
> Warning: React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
**Steps to reproduce:**
1. Use S-Group Tool to select some objects
2. Check the console
> Fix `innerRef` warning in development environment

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-react/src/templates/fg.sdf
There are no actual changes in application logic. It just changes the display for some specific functional groups
closes #2879
> #2879 – Incorrect display of attachment points for some Functional Groups

- packages/ketcher-core/src/application/render/draw.ts
- packages/ketcher-core/src/application/render/options.ts
- packages/ketcher-core/src/application/render/render.types.ts
- packages/ketcher-core/src/application/render/restruct/rebond.ts
- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/editor/shared/utils.js
- packages/ketcher-react/src/script/editor/tool/rotate-controller.test.ts
- packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
- packages/ketcher-react/src/script/editor/tool/rotate.ts
Closes #2760 
Note: for easy review, this PR has been divided into 2 commits. One is refactoring, the other is the new feature.
Snap positions are 90, 120, and 180 degrees.
Snap positions are bisectors of any two bonds
> #2760 Snap partially selected structure to an attachment bond when rotated

- packages/ketcher-core/src/application/render/raphaelRender.ts
- packages/ketcher-react/src/script/editor/tool/bond.ts
Closes #2111 
https://github.com/epam/ketcher/assets/14859362/771d856b-d6f0-45f9-924d-5a48cc1303cc
> #2111 - Position newly added bond so that mouse cursor is over its atom

- packages/ketcher-react/src/script/editor/Editor.ts
Closes #2128 
- added margin for structure autoscaling after import
> #2128 - Automatically adjust zoom when opening a structure

- packages/ketcher-core/src/application/editor/editor.types.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/App/App.tsx
- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/views/Editor.jsx
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
> Backmerge: #2940 – No modal windows are opened during R-Group adding

- packages/ketcher-core/src/application/render/restruct/restruct.ts
> #2989 error message appears when copypaste structure with s group properties functional groups and salts and solvents

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/domain/entities/atom.ts
> #2958 - Atom lable disappears after updating R-Group attachment point to none

- packages/ketcher-core/src/application/render/restruct/retext.ts
> #2679 Highlight colors for Simple Objects do not match the new design

- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/GroupBlock/styles.ts
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/monomerLibraryGroup/MonomerGroup.tsx
- packages/ketcher-polymer-editor-react/src/components/shared/MonomerPreview/index.tsx
Small fixes for Monomer preview - z-index of popup is increased; debounce for hover added.
Also fixed paddings for icon in RNA Editor
https://github.com/epam/ketcher/assets/60065704/22857482-f0d2-45ef-baae-40775611545f
Closes #3045
/
> #3045 - Fix bugs for Preview monomers

- .github/auto_assign.yml
> #3064-added qa team members for 'auto_assign'

- packages/ketcher-react/src/script/ui/utils/fileOpener.js
The problem occurred because the number of characters for Mime Type was hardcoded. Now I've provided the universal solution.
closes #3091
> #3091 – Cannot open CDX files on Mac

- demo/src/constants/buttons.ts
- packages/ketcher-react/src/script/ui/action/tools.js
- packages/ketcher-react/src/script/ui/component/view/ToolActions.test.tsx
Navigate to ketcher
Navigate mouse to Arrow Filled Triangle
AR: it is "Arrow Filled Triangle"
ER: it should be "Arrow Filled Triangle Tool"
> #2541 - missing tool word for arrow filled triangle

- package-lock.json
- packages/ketcher-standalone/package.json
> Backmerge: #3151 - Migrate to Indigo v1.14.0-rc.2 in-browser module

- packages/ketcher-react/src/script/editor/tool/template.ts
> Backmerge: #3133 - Merge preview stops appearing after hovering over a terminal atoms

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/HoverIcon.ts
> #2849 – When zoom out or zoom in, atoms and templates are located not under the mouse cursor

- packages/ketcher-core/src/application/editor/actions/atom.ts
- packages/ketcher-core/src/application/editor/actions/utils.ts
if functional group is merged to another atom, then its' AttachmentPoint atom is removed. The problem occured because, atom itself was removed, but attachment point still pointed to deleted atom.
closes #3176
> #3176 – Drawing gets broken after dragging a Functional Group onto an atom

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/editor/HoverIcon.ts
> Backmerge: #2849 – When zoom out or zoom in, atoms and templates are located not under the mouse cursor

- packages/ketcher-core/src/application/editor/actions/utils.ts
- packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.tsx
> #3238 – Enhanced stereochemistry is disabled via right-click for stereocenters after pasting structure through API in Ket format

- packages/ketcher-core/src/application/editor/actions/utils.ts
> Backmerge: #3238 – Enhanced stereochemistry is disabled via right click for stereocenters after pasting structure through api in ket format

- packages/ketcher-react/src/script/ui/state/shared.ts
…arts with one query group error appear
> #3408 - When insert a smarts with two query groups after inserting smarts with one query group error appear

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
- packages/ketcher-core/src/application/editor/editor.types.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/state/shared.ts
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
- packages/ketcher-react/src/script/ui/views/modal/components/InfoModal/InfoModal.tsx
Closes #3498 
Added handling the cae when monomer doesn't have specific attachment point but we added bond to it.
> Macro: #3498 - When switching from the Macromolecules module to the Molecules module an application crashes

- packages/ketcher-core/src/application/editor/tools/Bond.ts
Can't provide a screenshot, but basically the new behavior is: when a user presses Escape while drawing a bond, the bond is removed (which wasn't happening before).
> Macro: #3539 – When pull bond away from monomer and press 'Escape', bond remains on canvas

- packages/ketcher-core/__tests__/domain/entities/drawingEntitiesManager.test.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
This fix prevents forming invalid R2-R2 polymer bond in cases when there is an R1 point in the first monomer
> Macro: #3525 - Wrong usage of AP when establishing a bond between monomers r1 and r2 r2

- packages/ketcher-core/__tests__/application/editor/tools/SelectRectangleTool.test.ts
- packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
- packages/ketcher-polymer-editor-react/src/Editor.tsx
- packages/ketcher-polymer-editor-react/src/components/Layout/Layout.tsx
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/MonomerLibrary.tsx
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/MonomerLibraryToggle.tsx
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/index.ts
Closes https://github.com/epam/ketcher/issues/3542
> #3542 - after hiding the library panel a residual strip remains concealing content on the canvas

- packages/ketcher-core/src/application/editor/tools/Bond.ts
https://github.com/epam/ketcher/assets/70894460/5d730596-aed8-4b5e-8f6c-bb51aa98ad22
> #3585 - APs are redrawn incorrectly after opening the modal window

- ketcher-autotests/tests/Indigo-Tools/Reaction Auto-mapping tool/reaction-am-tool-veryfing-button.spec.ts
- ketcher-autotests/tests/Settings/Atoms/atoms-settings.spec.ts
- ketcher-autotests/tests/utils/canvas/tools/helpers.ts
- ketcher-autotests/tests/utils/scrollSettingBar.ts
- packages/ketcher-polymer-editor-react/src/Editor.tsx
This PR prevents monomer preview from being displayed when user is drawing a polymer bond
> #3553 - macro while pulling bond onto monomer a preview is shown when hover monomer

- packages/ketcher-core/src/application/editor/tools/Bond.ts
- added bond creation to history for more cases (creation through modal window, creation by using specific attachment points)
- fixed temporary bond preview deletion after creation of bond through the modal window
> #2414 fix for bonds creation broken after merge of undo/redo task.

- packages/ketcher-react/src/script/ui/state/templates/init-lib.ts
- added postponing of templates library reinitialization if it is not yet initialized
> #3643 - Error appears in DevTool Console after call 'ketcher.setSettings' before templates initialization

- packages/ketcher-react/src/script/ui/state/templates/init-lib.ts
- added postponing of templates library reinitialization if it is not yet initialized
> Backmerge: #3643 - Error appears in DevTool Console after call 'ketcher.setSettings' before templates initialization

- packages/ketcher-react/src/Editor.module.less
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.tsx
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbarIconButton.ts
- changed media queries for top toolbar icons to container ones
> #3623 - Icons are too small if ketcher inserted in react component instead of iframe

- packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
- exit from resize handler in case if canvas has width 0
> #3702 - Macro: 'Uncaught DOMException' error in DevTool console after switch from Macro to Micro mode

- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed atom rglabel and monomers attachment points parsing from ket in case when label is not set explicitly
> #3766 - Macro: Incorrect attachment point labels parsing from ket

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- fixed cleaning potential attachment points in monomers
> #3787 - Macro: System allow to connect block to already occupied connection (that cases invalide saved files)

- packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- added ability to bond micro and macro structures in macro mode
> #3738 - Macro/Micro: Switching from Macromolecules view to Molecules view causes crash if custom aromatic hydrocarbon was connected with monomer

- packages/ketcher-core/src/application/editor/operations/index.ts
- packages/ketcher-polymer-editor-react/src/Editor.tsx
- packages/ketcher-polymer-editor-react/src/components/contextMenu/RNAContextMenu.test.tsx
- packages/ketcher-polymer-editor-react/src/components/contextMenu/mockedPresets.json
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaBuilder.tsx
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditor.tsx
- packages/ketcher-polymer-editor-react/src/components/monomerLibrary/monomerLibraryItem/MonomerItem.tsx
- packages/ketcher-polymer-editor-react/src/constants.ts
- packages/ketcher-polymer-editor-react/src/helpers/localStorage.ts
- packages/ketcher-polymer-editor-react/src/state/library/librarySlice.ts
- packages/ketcher-polymer-editor-react/src/state/rna-builder/rnaBuilderSlice.ts
closes https://github.com/epam/ketcher/issues/3640
> #3640 - macro after reloading the page monomers added to the favorites section disappear

- packages/ketcher-core/src/domain/entities/monomerMicromolecule.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- fixed macromolecules cloning in struct to include it into ket for indigo layout
During the struct cloning MonomerMicromolecule was converting into SGroup and we were loosing the information that structure is monomer. To fix that it was implemented clone method in MonomerMicromolecule. Also added setting of several attributes of sgroup in MonomerMicromolecule which needs to render monomers properly n molecules mode.
> #3712 - Macro: Pressing Layout/Clean Up button cleanup all macromoleculas from canvas

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed leaving group searching during ket deserialization
> Macro: #3874 - R2 label is displayed on attachment atom instead of leaving group in monomer preview

- packages/ketcher-core/src/application/formatters/formatterFactory.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
Added check for saving in mol v2000 (check for properties) and loading from mol v2000 ('MRV' substring)
> #3872 Add support for all query properties in Mol V2000

- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
The trim() method in the `onChangeName` function prevented the deletion of the last letter. Adjusted logic to allow for the removal of all characters, while still trimming input for the new state.
https://github.com/epam/ketcher/assets/72468284/10317cc4-5156-4319-a00a-f6290879ae1c
> Macro: #3900 - The last letter in RNA Builder name field cannot be deleted

- ketcher-autotests/tests/test-data/KET/monomers-connected-with-bonds-expected.ket
- packages/ketcher-core/src/application/editor/operations/monomer/monomerFactory.ts
- packages/ketcher-core/src/application/formatters/types/ket.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
closes https://github.com/epam/ketcher/issues/3846#event-11428842497
- cherry-pick https://github.com/epam/ketcher/pull/3859
> #3846 - macro class field is absent after serialisation to ket 

- packages/ketcher-macromolecules/src/components/modal/monomerConnection/MonomerConnections.tsx
An issue where bonds and connected attachment points were not updating correctly in the MonomerConnection component. The commit introduces a new function `handleSelectAttachmentPoint` and a useEffect hook to ensure that bonds and connected attachment points get correctly updated when the selected attachment point changes. Also the commit improves the disabling logic to properly account for the currently selected attachment point.
https://github.com/epam/ketcher/assets/72468284/5529cc9d-cab7-4490-9a44-716ceca01b7e
> Macro: #3736 - System marks availiable connection point as unavaliable in Select Connection Point dialog

- packages/ketcher-react/src/script/ui/state/hotkeys.ts
- added fallback to old clipboard api for smarts
> #3967 - Exception if you paste from clipboard using Ctrl+Alt+V (Smile insert)

- packages/ketcher-core/src/domain/entities/struct.ts
- fixed texts scaling (removed ignoring scaling for texts if there is no reaction in structure)
> #3961 - system disorganize molecules and labels during loading from pptx file (base64 cdx format)

- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts
- packages/ketcher-core/src/application/editor/tools/Bond.ts
> #4014 - Macro: Monomers (attachment points) cannot be connected by a bond in Firefox browser

- packages/ketcher-core/src/application/editor/tools/Bond.ts
> Backmerge: #4014 - Macro: Monomers (attachment points) cannot be connected by a bond in Firefox browser

- packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/AttachmentPoint.ts
Root cause: When mouse over the current attachment points, they will be destoryed in a setTimeout function and new set of attachment points will be created. There would be no issue if current attachment points are destoryed after their mouseleave event be triggered because the mouseleave event will trigger actions to clear the new created attachment points. While if current attachment points are destoryed before its mouseleave event be triggered(because the execution time of the settimeout function couldn't be guaranteed), then their mouseleave event will not be triggered and new created set of attachment points will be left in the view.
Solution: instead of creating new attachment points everytime when mouseover event listener triggered, just update attachment points' styles when there …
> Macro: #3899 - Attachment points do not disappear when hover is removed from some monomers.

- packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/AttachmentPoint.ts
Backmerge of https://github.com/epam/ketcher/pull/4035
> Backmerge: Macro: #3899 - Attachment points do not disappear when hover is removed from some monomers.

- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
- fixed canvas resize observer
> #4097 - Cursor position misalignment after switching in fullscreen after changing ketcher settings

- packages/ketcher-core/src/application/render/renderStruct.ts
- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
- fixed functional group id setting
> #3891 - Aromatize/Dearomatize of having abbreviation (Salts and Solvents) on the canvas causes spontaneous random de-abbreviation

- packages/ketcher-core/src/application/render/renderStruct.ts
- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
> Backmerge: #3891 - Aromatize/Dearomatize of having abbreviation (Salts and Solvents) on the canvas causes spontaneous random de-abbreviation

- ketcher-autotests/tests/User-Interface/Hot-Keys/hotkeys.spec.ts
- packages/ketcher-react/src/script/editor/tool/template.ts
- packages/ketcher-react/src/script/editor/tool/templatePreview.ts
- packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
- added template connected preview hiding before erase by hotkey
> #3918 - When deleting part of a structure using a hotkey Del, and preview of structure is under mouse cursor, an error occurs.

- packages/ketcher-macromolecules/src/components/shared/modal/Modal.tsx
When a specific HTML element enters fullscreen mode using the requestFullscreen API, all other elements outside this element are not rendered. Hence you cannot directly display a dialog outside of the fullscreen element.
So to make a dialog appear at the top of an element that is displayed in fill screen with requestFullscreen api, you can create a dialog inside the fullscreen element and position it correctly.
However, it's important to note that normal MUI Dialog behavior might not work as expected if a specific HTML element is in fullscreen mode because MUI Dialog is attached to the document body by default. You could use the ModalProps in the Dialog component. ModalProps has a property called container that can be used to set the container …
> Macro: #4173 - the pop-up window does not appear in fullscreen mode after clicking the “Open” button and the “Save as” button

- ketcher-autotests/tests/Macromolecule-editor/RNA-Builder/rna-library.spec.ts
- packages/ketcher-macromolecules/src/components/monomerLibrary/MonomerLibrary.tsx
- packages/ketcher-macromolecules/src/state/rna-builder/rnaBuilderSlice.ts
> #3663 - Macro: After clicking the 'Duplicate and Edit' button and subsequently clicking 'Cancel,' the preset remains saved.

- ketcher-autotests/tests/User-Interface/Editing-Tools/Copy-Cut-Paste/copy-cut-paste.spec.ts
- ketcher-autotests/tests/utils/clicks/index.ts
- ketcher-autotests/tests/utils/common/loaders/waitForRender.ts
- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/application/editor/operations/bond/BondAttr.ts
- packages/ketcher-core/src/application/editor/operations/bond/index.ts
- packages/ketcher-core/src/application/render/notifyRenderComplete.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
- added debounce for structures merge calculations
- added stop handling of mousemove if previous handler in progress
- added functionalGroup link to sgroup to more efficiently search it during different operations (for example for checking is atom in contracted group)
> #4241 - Pasting large cyclodextrins structure cause Ketcher to freeze

- ketcher-autotests/tests/User-Interface/Editing-Tools/Copy-Cut-Paste/copy-cut-paste.spec.ts
- ketcher-autotests/tests/utils/clicks/index.ts
- ketcher-autotests/tests/utils/common/loaders/waitForRender.ts
- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/application/editor/operations/bond/BondAttr.ts
- packages/ketcher-core/src/application/editor/operations/bond/index.ts
- packages/ketcher-core/src/application/render/notifyRenderComplete.ts
- packages/ketcher-core/src/domain/entities/functionalGroup.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/paste.ts
- added debounce for structures merge calculations
- added stop handling of mousemove if previous handler in progress
- added functionalGroup link to sgroup to more efficiently search it during different operations (for example for checking is atom in contracted group)
> Backmerge: #4241 - Pasting large cyclodextrins structure cause Ketcher to freeze

- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Entity-Selection-Flag-in-KET-format/entity-selection-flag-in-ket-format.spec.ts
- ketcher-autotests/tests/test-data/KET/three-bond-structure-with-custom-query-to-compare.ket
- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-core/src/application/utils.ts
> #4238 - getKet function return ket file without selection flags

- packages/ketcher-core/src/application/editor/actions/bond.ts
- packages/ketcher-core/src/application/editor/actions/erase.ts
- packages/ketcher-core/src/application/editor/actions/sgroup.ts
- add findAttachmentPoints function
- add addAttachmentPoint function
- add removeAttachmentPoint function
https://github.com/epam/ketcher/assets/117748331/18dfee12-94e4-4d4a-9fa7-92e8c621c3e1
> #4144 - Connection of bond to atom inside s-group supergroup cause it connected incorrectly in terms of layout

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
> Backmerge: #4369 - Del button works as Backspace button that is wrong

- ketcher-autotests/tests/Structure-Creating-&-Editing/SMARTS-attributes/Atom-properties-attributes/atom-properties-attributes.spec.ts
- packages/ketcher-react/src/script/ui/data/convert/structconv.js
- packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
- packages/ketcher-react/src/script/ui/data/utils.test.ts
- packages/ketcher-react/src/script/ui/data/utils.ts
- packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Atom/helper.ts
Screenshots
<details>
<summary>Atom's charge out of allowed range</summary>
</details>
<details>
<summary>Atom's charge in allowed range</summary>
</details>
Please also review fix for corner case with zero charge defined explicitly:
<details>
<summary>Current behaviour</summary>
All zero charge values get displayed on canvas and explicitly shown in atom's property field but get removed after export anyway
https://github.com/epam/ketcher/assets/50613241/cac33a27-ee89-4d65-911b-08f3044788f3
</details>
<details>
<summary>Proposed behavaiour</summary>
All zero values don't get displayed on canvas and don't get shown in atom's property field. So there is no difference with default atom after explicitly setting zero as charge value.
https://github.com/epam/ketcher/assets/50613241/7ab61815-39c5- …
> #3943 - System allow to create atoms with Charge value out or range

- packages/ketcher-core/src/domain/serializers/ket/schema.json
Update ket schema with new "selected" field for atoms and bonds.
>  #3934 Support selection entity selection flag in KET format

- ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-mol.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-base-monomers.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-phosphate-monomers.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Zoom-Tool/zoom-tool.spec.ts
- ketcher-autotests/tests/test-data/KET/CHEM-Templates/chem-connection-rules-cases-template.ket
> Autotests: #4535 - Failed tests need to be fixed

- example/package.json
- packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
Closes [#4507](https://github.com/epam/ketcher/issues/4507) 
- When Select Rectangle Tool is used and elements frantically moved mouseup event could be fired and some time it looses renderer object, so check for it is needed.
- Added possibility to run development with Polymer editor by script 'dev:standalone:macro'.
> #4507 - Macro: When expanding structures, added to the canvas via Clipboard, an error appears in the Console

- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/DrawingEntity.ts
- packages/ketcher-core/src/domain/entities/Phosphate.ts
- packages/ketcher-core/src/domain/entities/PolymerBond.ts
- packages/ketcher-core/src/domain/entities/RNABase.ts
- packages/ketcher-core/src/domain/entities/Sugar.ts
> #4508 – Macro: In the Text-editing mode, when selecting nucleotides linked through phosphates R2-R2, an error appears in the Console

- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/DrawingEntity.ts
- packages/ketcher-core/src/domain/entities/Phosphate.ts
- packages/ketcher-core/src/domain/entities/PolymerBond.ts
- packages/ketcher-core/src/domain/entities/RNABase.ts
- packages/ketcher-core/src/domain/entities/Sugar.ts
> Backmerge: #4508 – Macro: In the Text-editing mode, when selecting nucleotides linked through phosphates R2-R2, an error appears in the Console

- packages/ketcher-core/src/application/editor/modes/BaseMode.ts
> #4479 - Macro: quick double paste operation from clipboard leads to invalid entities on canvas

- .github/workflows/playwright.yml
temporary rise execution time for microtests up to 150
[skip ci]
> Bump request: Update playwright.yml

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
This pull request addresses the issue where, in Text-editing mode, the cursor moves to another row after inserting a fragment by pressing Ctrl+V twice.
The problem has been resolved by implementing a check for the presence of phosphate in the current sequence and the inserted sequence. 
Manual testing has been performed to validate the fix in various scenarios within the Text-editing mode.
This fix improves the user experience by preventing the cursor from inadvertently moving to another row after inserting a fragment. It enhances the overall usability and reliability of the Text-editing mode.
[In the Text-editing mode, when inserting a fragment after pressing Ctrl+V twice, the cursor is moved to another row #4509](https://github.com/epam/ketcher/issues/4509)
> #4509 - In the Text-editing mode, when inserting a fragment after pressing Ctrl+V twice, the cursor is moved to another row

- packages/ketcher-core/src/application/render/restruct/rebond.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- fixed position calculation for external bonds to sgroups without attachment points
> #4693 - Incorrect bond alignment to tBu S-group

- packages/ketcher-core/src/application/render/restruct/rebond.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- fixed position calculation for external bonds to sgroups without attachment points
> Backmerge: #4693 - Incorrect bond alignment to tBu S-group

- packages/ketcher-core/src/application/editor/Editor.ts
- added removing of copy/paste event listeners during switching between micro/macro modes
> #4730 - System doubles number of pasted monomers after switching from flex to sequence

- packages/ketcher-core/src/application/editor/Editor.ts
- added removing of copy/paste event listeners during switching between micro/macro modes
> Backmerge: #4730 - System doubles number of pasted monomers after switching from flex to sequence

- packages/ketcher-core/src/application/editor/actions/erase.ts
- packages/ketcher-core/src/application/editor/operations/sgroup/index.ts
- packages/ketcher-react/src/script/editor/tool/eraser.ts
- unblocked monomers deletion in micro mode
> #4734 - Preview: Monomers from macro mode are not erased by Erase tool in micro mode

- packages/ketcher-macromolecules/src/components/ZoomControls/ZoomControls.tsx
- fixed ZoomControls component subscription to ZoomTool instance
> #4744 - When changing zoom level in macro mode, there is no percentage indication

- packages/ketcher-macromolecules/src/components/ZoomControls/ZoomControls.tsx
- fixed ZoomControls component subscription to ZoomTool instance
> Backmerge: #4744 - When changing zoom level in macro mode, there is no percentage indication

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- skip handling of adding/deleteing phosphates and establishing bonds if selection if on the bound of chain
> #4740 - Delete of cycled sequnece from the canvas causes delete of another cycled sequence bond that makes it non-cycled

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- skip handling of adding/deleteing phosphates and establishing bonds if selection if on the bound of chain
> Backmerge: #4740 - Delete of cycled sequnece from the canvas causes delete of another cycled sequence bond that makes it non-cycled

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- added idtAliases serialisation to ket
> #4764 - IDT label is not shown or shown but layout is broken after load sequence from ket

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- added idtAliases serialisation to ket
> Backmerge: #4764 - IDT label is not shown or shown but layout is broken after load sequence from ket

- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- added ignoring of leaving groups connection count for valence warning calculation if there is connection to attachment point
> #4777 - Incorrect valence for carbon atom in ring with attachment point after saving and reopening file

- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- added ignoring of leaving groups connection count for valence warning calculation if there is connection to attachment point
> Backmerge: #4777 - Incorrect valence for carbon atom in ring with attachment point after saving and reopening file

- packages/ketcher-core/src/application/editor/actions/erase.ts
- packages/ketcher-core/src/application/editor/actions/sgroup.ts
- packages/ketcher-core/src/application/editor/operations/bond/index.ts
- added skipping of implicit leaving group atom deletion in case if it is explicitly selected
- added connected atoms invalidation for undo of bond deletion
- skipped regular logic of sgroup atoms deletion in case of superatoms without labels
> #4801 - Cut operation for attachment points makes canvas inaccessible/inoperational and delete entire molecule

- packages/ketcher-macromolecules/src/components/contextMenu/SequenceItemContextMenu/helpers.ts
If the number of selections equal the number of nucleic elements, then we write nucleotides, otherwise elements.
> #4636 - In the Sequence mode, when selecting elements on the canvas, the total number of elements is not displayed in the Right-click menu

- packages/ketcher-core/src/application/editor/Editor.ts
- added removing keydown subscription after editor destroy
> #4823 - In sequence mode, each press adds two characters and when deleted, also removes two

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/AtomMenuItems.tsx
> #4793 - Context menu for attachment point labels should contain only Delete option

- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useAddAttachmentPoint.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useDelete.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useRemoveAttachmentPoint.ts
Add focus function after deleting and adding attachment point
> #4786 - Keyboard shortcust stops working after adding/removing attachment point

- packages/ketcher-react/src/script/editor/tool/bond.ts
> #4782 - It is possible to attach bond to attachment point label

- packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
- packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
> #4791 - System saves selection states of attachment point labels to KET file (it should not)

- packages/ketcher-macromolecules/src/components/monomerLibrary/MonomerLibrary.tsx
Adding logic to track the first rendering of a component
> #4837 - Library filter does not reset when switching between Micro and Macro mode

- packages/ketcher-react/src/Editor.tsx
- packages/ketcher-react/src/constants.ts
- packages/ketcher-react/src/contexts/appContext.tsx
- packages/ketcher-react/src/hooks/useSubscribtionOnEvents.ts
- packages/ketcher-react/src/index.tsx
- packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts
- packages/ketcher-react/src/script/index.ts
- packages/ketcher-react/src/script/ui/App/initApp.tsx
Add a ketcherId so that multiple ketcher instances can be added to the same page without using an iframe. Instead of binding each ketcher instance to the iframe, they can now be stored in the React state and easily accessed to obtain the data.
> #4833 - Support rendering multiple ketcher editors on a page without an iframe

- package-lock.json
- packages/ketcher-core/package.json
- packages/ketcher-macromolecules/package.json
- packages/ketcher-react/package.json
- packages/ketcher-standalone/package.json
- updated indigo to 1.21.0-rc.2
- updated ketcher to 2.22.0-rc.7
> #4849 - Migrate to Indigo v1.21.0-rc.2 in-browser module

- example/config/webpack.config.js
- example/package.json
- package-lock.json
- packages/ketcher-standalone/package.json
- packages/ketcher-standalone/rollup.config.js
- added two ketcher-standalone builds: with base64 indigo wasm and with separate wasm file
> #2654 - Improve WASM loading performance

- packages/ketcher-react/src/script/editor/tool/atom.ts
added check for selected atoms in the functional group
> #4929 - System allow to change atoms inside S-group without removing abbreviation

- packages/ketcher-core/src/domain/entities/monomerMicromolecule.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed monomer atoms ids mapping during struct clone
> #4973 - Connection between molecule and monomer lost after opening and saving to ket

- packages/ketcher-core/src/application/render/renderers/sequence/UnsplitNucleotideSequenceItemRenderer.ts
- packages/ketcher-core/src/domain/constants/monomers.ts
> #4932 - Preview: Unsplit nucleotide without natural analog should be displayed as '@' symbol

- example/src/App.tsx
> #5005 - Use ketcher-standalone with separate indigo wasm file by default in ketcher example

- packages/ketcher-core/src/application/render/renderers/sequence/UnsplitNucleotideSequenceItemRenderer.ts
- packages/ketcher-core/src/domain/constants/monomers.ts
> Backmerge: #4932 - Preview: Unsplit nucleotide without natural analog should be displayed as '@' symbol 

- packages/ketcher-core/src/application/editor/data/monomers.ket
- packages/ketcher-core/src/application/render/renderers/UnsplitNucleotideRenderer.ts
- fixed nucleotides definition in library
- fixed unsplit nucleotides label styles
> Backmerge: #4920 - Preview: Unable to load IDT codes for unsplit monomers we have in the library

- packages/ketcher-react/src/script/editor/tool/atom.ts
- packages/ketcher-react/src/script/editor/tool/helper/getGroupIdsFromItems.ts
> #4927 - Able to change attachment point label to an atom if it is selected first

- packages/ketcher-core/src/domain/helpers/monomers.ts
- fixed check of chain beginning
> Backmerge: #4934 - Preview: Enumeration counters remain unchanged after bond being deleted

- packages/ketcher-core/src/application/editor/modes/types.ts
- packages/ketcher-core/src/application/editor/tools/Clear.ts
- fixed clear tool for sequence mode
> #4889 - After using "Clear Canvas" in the Sequence mode and entering new sequence, extra structures are shown in Flex and Snake modes

- packages/ketcher-macromolecules/src/helpers/getPreset.ts
- added safety checks in rna presets getter
> Backmerge: #4924 - RNA Preset without Base causes constant crash after switching to Macromolecules mode

- packages/ketcher-core/src/application/editor/modes/types.ts
- packages/ketcher-core/src/application/editor/tools/Clear.ts
- fixed clear tool for sequence mode
> Backmerge: #4889 - After using "Clear Canvas" in the Sequence mode and entering new sequence, extra structures are shown in Flex and Snake modes

- packages/ketcher-macromolecules/src/helpers/getPreset.ts
- added safety checks in rna presets getter
> #4924 - RNA Preset without Base causes constant crash after switching to Macromolecules mode

- packages/ketcher-core/src/application/formatters/types/ket.ts
- packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/monomerToDrawingEntity.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
- added filling of unresolved monomers by fake structure
> #4950 - Preview: Switching to Molecules mode causes crash if unknown monomer is on the canvas

- packages/ketcher-core/src/application/editor/actions/fragment.ts
- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/application/editor/operations/OperationType.ts
- packages/ketcher-core/src/application/editor/operations/base.ts
- packages/ketcher-core/src/application/editor/operations/rasterImage/index.ts
- packages/ketcher-core/src/application/editor/operations/rasterImage/rasterImageMove.ts
- packages/ketcher-core/src/application/editor/operations/rasterImage/rasterImageUpsertDelete.ts
- packages/ketcher-core/src/application/render/restruct/rerasterImage.ts
- packages/ketcher-core/src/application/render/restruct/restruct.ts
- packages/ketcher-core/src/domain/entities/rasterImage.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-core/src/domain/serializers/ket/fromKet/rasterImageToStruct.ts
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- packages/ketcher-core/src/domain/serializers/ket/schema.json
- packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts
- packages/ketcher-core/src/domain/serializers/ket/toKet/rasterImageToKet.ts
* Loading image from ket file to canvas
* Saving image from struct to ket
* operations to move image during paste\replace
>  #4911 - insert image from ket to canvas

- ketcher-autotests/tests/Macromolecule-editor/Snake-Mode/snake-bond-tool.spec.ts
> #5161 - Autotests: Turn some tests to clear canvas way instead of page reload 2

- packages/ketcher-core/src/domain/entities/canvas-matrix/CanvasMatrix.ts
Issue => https://github.com/epam/ketcher/issues/5126
Past behavior
Console error when connecting two unsplit nucleotides in snake mode.
Actual behavior
No console error shown.
> #5126 - The error appears in the Console, when connecting two unsplit nucleotides in Snake mode

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/BondMenuItems.tsx
Issue => https://github.com/epam/ketcher/issues/4806 
Past Behavior
Actual Behavior
> #4806 - It is allowed to change bond type between micro and macro

- example/vite.config.js
- package-lock.json
- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-core/src/domain/services/struct/structService.types.ts
- packages/ketcher-react/src/Editor.tsx
- packages/ketcher-react/src/constants.ts
- packages/ketcher-react/src/script/api.ts
- packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts
- packages/ketcher-react/src/script/index.ts
- packages/ketcher-react/src/script/ui/App/initApp.tsx
- packages/ketcher-react/src/script/ui/state/index.js
- packages/ketcher-standalone/package.json
- packages/ketcher-standalone/rollup.config.js
- packages/ketcher-standalone/src/index.ts
- packages/ketcher-standalone/src/infrastructure/services/index.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/constants.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/index.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
- added ketcher-standalone builds for indigo without render module
- added structService reinitialization
> #5190 - Include indigo without render module into ketcher-standalone build process

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- changed usage of previous/next node to previous/next node in same chain for replacing sequence items through the library
> #5242 - Replace phosphate at the end with petide causes cycled polymer

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- changed usage of previous/next node to previous/next node in same chain for replacing sequence items through the library
> Backmerge: #5242 - Replace phosphate at the end with petide causes cycled polymer

- ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-idt.spec.ts
- packages/ketcher-core/src/application/editor/tools/Bond.ts
- packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts
> #5184 – Fix unresolved monomers bond establishing issue

- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.test.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
> Backmerge: #5255 – Fix adding new monomers to canvas in sequence modewhile editing RNA in builder

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- moved rna node addition in sequence mode to separate function
- removed restriction of insertion/replacing rna without base
> #5245 - Replacement of peptide at the end of sequence on preset w/out base works wrong

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
- fixed case with adding new sequence items using replace from library in case if there is no attachment points
> #5228 - System insert monomer from the library to the canvas even if it shouldn't (and error message is wrong)

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
- fixed case with adding new sequence items using replace from library in case if there is no attachment points
> Backmerge: #5228 - System insert monomer from the library to the canvas even if it shouldn't (and error message is wrong)

- packages/ketcher-core/src/application/render/restruct/rergroup.js
- packages/ketcher-core/src/application/utils.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
- added set stereo labels to atoms to setMolecule
> #5335 - The application crashes when selecting Enhanced Stereochemistry from the right-click menu

- packages/ketcher-core/src/application/render/restruct/rergroup.js
- packages/ketcher-core/src/application/utils.ts
- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/ui/state/shared.ts
- added set stereo labels to atoms to setMolecule
> Backmerge: #5335 - The application crashes when selecting Enhanced Stereochemistry from the right-click menu

- ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-idt.spec.ts
- ketcher-autotests/tests/utils/canvas/tools/helpers.ts
- ketcher-autotests/tests/utils/keyboard/index.ts
- ketcher-autotests/tests/utils/macromolecules/index.ts
- ketcher-autotests/tests/utils/testAnnotations/resetToDefaultState.ts
This pull request refines and optimizes the test suite for IDT import and saving by clearing the canvas after each test without reloading the page in accordance with [this task](https://github.com/epam/ketcher/issues/5322).
- Optimized tests to decrease execution time.
- Reworked `selectClearCanvasTool` to automatically close all interfering popups before clicking the «Clear Canvas» button, making it faster to write tests with this approach in the future.
- Added `resetZoomLevelToDefault` and `chooseTab` functions to encapsulate its logic.
- Implemented `markResetToDefaultState` and `processResetToDefaultState` - these allow for broader and more flexible resetting of the test environment post-execution.
The modifications have resulted in a reduction in the maximum execution time on a …
> #5322 - Refactor IDT import and save tests for optimized execution

- ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-ket.spec.ts
This pull request refines and optimizes the test suite for KET import and saving by clearing the canvas after each test in accordance with [this task](https://github.com/epam/ketcher/issues/5396).
Since many tests involve checking the contents of generated files, a page reload has been added for them.
The modifications have resulted in a reduction in the maximum execution time on a single worker — down to approximately 115 seconds (on my PC) from the previous ~145 seconds using the older page reload method. For tests where it is still necessary to reload the page, clear comments have been added to explain the rationale.
> #5396 - Refactor KET import and save tests for optimized execution

- ketcher-autotests/tests/utils/canvas/tools/helpers.ts
- Removed the `number` type in the parameter declaration of the `selectClearCanvasTool` function in accordance with [this task](https://github.com/epam/ketcher/issues/5430).
> #5430 - Fix ESLint error in selectClearCanvasTool function

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- fixed fasta validation for ambiguous monomers
> #5454 - Export of variant monomers to Sequence/FASTA doesn't work for presets

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> #5425 - Undo-Redo operations over ambiguous monomer causes broken canvas

- packages/ketcher-react/src/components/MonomerPreview/AmbiguousMonomerPreview/AmbiguousMonomerPreview.tsx
> #5427 - Preview tooltip for mixture ambiguous monomer shows wrong percentages

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- fixed fasta validation for ambiguous monomers
> Backmerge: #5454 - Export of variant monomers to Sequence/FASTA doesn't work for presets

- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditor.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
- packages/ketcher-macromolecules/src/helpers/rnaValidations.ts
> #5313 - Creation preset without phosphate causes R3less sugars disabled in the library FOREVER

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
> Backmerge: #5470 - Export of diffrent mixed and alternatives peptides (with diffrent proportions and percents) works wrong

- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditor.tsx
- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
- packages/ketcher-macromolecules/src/helpers/rnaValidations.ts
- packages/ketcher-macromolecules/src/state/rna-builder/rnaBuilderSlice.ts
- added clearing of rna components validations in case of NOT edit mode
> Backmerge: #5313 - Creation preset without phosphate causes R3less sugars disabled in the library FOREVER

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed template id generation for ambiguous monomers
> #5512 - System saves mixture ambiguous monomers as alternatives ambiguous monomers

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed template id generation for ambiguous monomers
> Backmerge: #5512 - System saves mixture ambiguous monomers as alternatives ambiguous monomers

- packages/ketcher-core/src/application/editor/actions/bond.ts
- packages/ketcher-core/src/domain/entities/bond.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useChangeBondDirection.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/BondMenuItems.tsx
https://github.com/user-attachments/assets/056ed2da-d8f1-4553-a2d6-4dee98adfb0d
> #4982-Choose both directions of wedged/hashed bonds from right-clicking the bond

- packages/ketcher-core/src/application/render/renderers/PhosphateRenderer.ts
- packages/ketcher-core/src/application/render/renderers/SugarRenderer.ts
> #5521 - Sugar color is wrong if loaded from HELM with inline SMILES

- packages/ketcher-react/src/components/ToggleButtonGroup/ToggleButtonGroup.tsx
> Backmerge: #5615 - Overlapping UI elements in Query Properties right-click menu

- packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/FlexModePolymerBondRenderer.ts
- packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
- packages/ketcher-core/src/domain/entities/canvas-matrix/CanvasMatrix.ts
- packages/ketcher-core/src/domain/entities/canvas-matrix/Connection.ts
> #5497 – Refactor: Specify the types of classes for `SnakeModePolymerBondRenderer`

- ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Rxn-Files/rxn-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/SDF-Files/sdf-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Save-File/save-file.spec.ts
- ketcher-autotests/tests/Indigo-Tools/Aromatize-Dearomatize/aromatize-dearomatize.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher2.spec.ts
- ketcher-autotests/tests/Reactions/Reaction-Validation/reaction-validation.spec.ts
- ketcher-autotests/tests/Reagents/RXN-Format/reagents-rxn-format.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/attachment-point-tool.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-label-dialog.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-tool.spec.ts
- packages/ketcher-core/src/application/formatters/formatProperties.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
https://github.com/epam/ketcher/issues/5651 - The reaction can't save to MDL RXN V3000 (returns RXN V2000 instead)
https://github.com/epam/ketcher/issues/5652 - Export to SDF V3000 returns SDF V2000
https://github.com/epam/ketcher/issues/5653 - The reaction can't save to MOL V3000 (returns MOL V2000 instead)
> #5651 – The reaction can't save to MDL RXN V3000 (returns RXN V2000 instead)

- packages/ketcher-react/src/script/editor/tool/select/select.ts
+ Stop copying if mouse up event handled
+ fixed on MacOs issue, cannot open menu when ctrl+click to atom (because long tap functionality)
> Backmerge: #5672 - Multiple duplicate items

- packages/ketcher-core/src/utilities/SettingsManager.ts
> #5649 - Default values for bond settings (at least for bond) got corrupted and become wrong after ver 2.26 version installed

- packages/ketcher-core/src/utilities/SettingsManager.ts
> Backmerge: #5649 - Default values for bond settings (at least for bond) got corrupted and become wrong after ver 2.26 version installed

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/SelectionMenuItems.tsx
When select bonds + atoms together and create highlight, highlight create now for both: bonds and atoms
> Backmerge: Only bonds highlighting created when select bonds + atoms together

- packages/ketcher-react/src/constants.ts
> #5685 - The diagonal bond in the molecule is displayed incorrect with  ACS style

- packages/ketcher-macromolecules/src/state/library/librarySlice.ts
This PR includes an update for `selectFilteredMonomers` to also search by ambiguous monomers and their components during the search
> #5564 – Search of ambiguous monomers doesn't work

- packages/ketcher-core/src/application/editor/EditorHistory.ts
- packages/ketcher-core/src/application/editor/operations/drawingEntity/index.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/entities/Command.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Operation.ts
- removed hidden chems created for molecules in model from selection
- fixed performance by collecting moving
> #5659 - Moving of selected microstructures on macro canvas works wrong

- packages/ketcher-macromolecules/src/helpers/getPreset.ts
- added filtration of rna preset from local storage if its part does not exist in library
> #5800 - Application crashes with white screen in Macro mode when loading local storage data from a previous version

- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-core/src/domain/entities/multitailArrow.ts
> Backmerge: #5753 - Fixed issue with tail normalization when moving

- packages/ketcher-macromolecules/src/helpers/getPreset.ts
- added filtration of rna preset from local storage if its part does not exist in library
> Backmerge: #5800 - Application crashes with white screen in Macro mode when loading local storage data from a previous version 

- packages/ketcher-react/src/script/ui/views/modal/components/meta/Settings/Settings.tsx
> #5703 Added tooltip for image resolution option

- packages/ketcher-core/src/application/editor/EditorHistory.ts
- packages/ketcher-core/src/application/editor/operations/drawingEntity/index.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/entities/Command.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Operation.ts
- removed hidden chems created for molecules in model from selection
- fixed performance by collecting moving
> Backmerge: #5659 - Moving of selected microstructures on macro canvas works wrong

- packages/ketcher-react/src/script/editor/tool/eraser.ts
> Backmerge: #5665 – Show remove abbreviation dialog when trying to erase expanded monomer

- DEVNOTES.md
- ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts
- packages/ketcher-core/src/domain/entities/multitailArrow.ts
- updated minimal ket validation distance
- commented tests with minimal values because they are no longer valid
> #5761 - updated minimal ket validation distance

- packages/ketcher-core/src/application/render/renderers/BondRenderer.ts
- packages/ketcher-core/src/domain/entities/Phosphate.ts
- packages/ketcher-core/src/domain/entities/Sugar.ts
- packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts
> Backmerge: #5848 - Unable to establish connection between micro structure and sugar or phopshate (and partially - unresolved monomer)

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/application/render/restruct/rebond.ts
> Backmerge: #5685 - The diagonal bond in the molecule is displayed incorrect with  ACS style

- packages/ketcher-core/src/application/render/options.ts
- packages/ketcher-core/src/application/render/restruct/resgroup.ts
> #5836 - R-group fragment labels font size doesnt defined by sub font size property at settings 

- packages/ketcher-core/src/application/render/options.ts
- packages/ketcher-core/src/application/render/restruct/resgroup.ts
> Backmerge: #5836 - R-group fragment labels font size doesnt defined by sub font  size property at settings 

- ketcher-autotests/tests/Indigo-Tools/Reaction Auto-mapping tool/reaction-am-tool-veryfing-button.spec.ts
- package-lock.json
- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- packages/ketcher-standalone/package.json
- made conversion of atomId to string for monomer to atom connections
> Updated indigo to 1.26.0-dev.3

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.utils.ts
> Backmerge: #5809 – Open correct context menu for expanded monomer while clicking on bond or atom

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- made conversion of atomId to string for monomer to atom connections
> #5887 - After save and load a MOL V3000 file in macro and micro mode, bond connections are changed, and the microstructures are shifted

- packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
> #5814 - On Remote environment, the reaction/molecule can't be saved to V3000 formats (returns V2000 instead): MOL, RXN, SDF, RDF

- packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
> Backmerge: #5814 - On Remote environment, the reaction/molecule can't be saved to V3000 formats (returns V2000 instead): MOL, RXN, SDF, RDF

- ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDXML-Files/cdxml-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Cml-files/cml-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/KET-Files/ket-files-properties.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/PNG-Files/png-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Rxn-Files/rxn-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/SDF-Files/sdf-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/SVG_Files/svg-files.spec.ts
- ketcher-autotests/tests/Settings/ACS Style/acs-style-settings.spec.ts
- ketcher-autotests/tests/Settings/General/default-settings-verification.spec.ts
- packages/ketcher-react/src/script/ui/views/modal/components/InfoModal/InfoModal.tsx
- packages/ketcher-react/src/script/ui/views/modal/components/meta/Settings/Settings.tsx
Added an informational message when adjusting the "Reaction component margin size" setting. The message notifies the user that applying the layout is required for changes to take full effect. Added an "OK" button to close the notification
> #5351 – Inform User to Apply Layout after Settings Adjustment

- packages/ketcher-core/src/application/editor/modes/BaseMode.ts
- packages/ketcher-core/src/application/editor/tools/Bond.ts
- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/HydrogenBond.ts
- packages/ketcher-core/src/domain/entities/PolymerBond.ts
Closes:
#5935 - Unable to establish hydrogen bond connection if monomer has no free attachment points
#5940 - Copy/paste operation works wrong (copy only two hydrogen bonds and drops others)
#5941 - Hydrogen bonds remain in place on monomer delete
#5933 - Error message is wrong if user tries to establish hydrogen bond if it is already exist
> #5935 - Unable to establish hydrogen bond connection if monomer has no free attachment points

- packages/ketcher-core/src/application/editor/modes/BaseMode.ts
- packages/ketcher-core/src/application/editor/tools/Bond.ts
- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/HydrogenBond.ts
- packages/ketcher-core/src/domain/entities/PolymerBond.ts
Closes:
#5935 - Unable to establish hydrogen bond connection if monomer has no free attachment points
#5940 - Copy/paste operation works wrong (copy only two hydrogen bonds and drops others)
#5941 - Hydrogen bonds remain in place on monomer delete
#5933 - Error message is wrong if user tries to establish hydrogen bond if it is already exist
> Backmerge: #5935 - Unable to establish hydrogen bond connection if monomer has no free attachment points

- packages/ketcher-core/src/application/formatters/identifyStructFormat.ts
In this PR, conditions are added to check the pasted expression in macromolecules mode for compliance with the IDT format. The check is performed in the order: 3-letter - IDT - 1-letter
> #5974 – Paste to canvas recogniton logic should be changed

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> #5969 - Load from file having only micro structures on macro canvas causes unnecessary zoom up to 200% and shift molecule to top left angle

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> Backmerge: #5969 - Load from file having only micro structures on macro canvas causes unnecessary zoom up to 200% and shift molecule to top left angle

- packages/ketcher-core/src/application/editor/tools/Erase.ts
- packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Nucleoside.ts
- packages/ketcher-core/src/domain/entities/Nucleotide.ts
- packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
Closes:
- #6068 
- #6074 
- #6080
- #6081 
- #6087 
- #6077 
- #6076 
- #6075 
- #6070 
- #6067 
- #6061 
- handled case if antisense chain starts from the left of snake layout starting point
- fixed logic of sense/antisense chains calculation. Applied correct business rules. Handled not only rna base to rna base hydrogen connections, but rna base to any monomer.
- added antisense chains recalculation after adding/removing bonds
> #6068 - Same chain configuration imported by different HELM layouted differently (anyway - both are wrong)

- packages/ketcher-core/src/domain/constants/monomers.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Nucleoside.ts
- packages/ketcher-core/src/domain/entities/Nucleotide.ts
- packages/ketcher-core/src/domain/helpers/rna.ts
- added antisense creation for chains with ambiguous bases
> #6086 - Unable to create antisense chains for ambiguous monomers from the library

- ketcher-autotests/tests/Reagents/CML-format/CML-format.spec.ts
- packages/ketcher-core/src/application/editor/tools/Erase.ts
- packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Nucleoside.ts
- packages/ketcher-core/src/domain/entities/Nucleotide.ts
- packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
#6074 - System doesn't flip chain if connected to monomer but not to base (2)
#6068 - Same chain configuration imported by different HELM layouted differently (anyway - both are wrong)
#6080 - System doesn't flip chain if connected to monomer but not to base (3)
#6081 - Smaller chain should be at the bottom
#6087 - Antisense layout is wrong for any ambiguouse base from the library
#6077 - H-bond is not alligned to Snake mode view in some cases
#6076 - Two-to-one base H-bond connection layouted wrong
#6075 - In case of multipal H-bonds system should arrange antisence chain to first base of bottom chain
#6070 - System doesn't flip chain if connected to monomer but not to base
#6067 - Two chains connected by H-bond arranged wrong if third bond present on the canvas
#6061 - RNA chain remain …
> Backmerge: #6068 - Same chain configuration imported by different HELM layouted differently (anyway - both are wrong)

- packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
- packages/ketcher-core/src/application/editor/operations/coreAtom/atom.ts
- packages/ketcher-core/src/application/editor/operations/coreBond/bond.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/entities/Command.ts
- packages/ketcher-core/src/domain/entities/CoreBond.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Operation.ts
- added invertAfterAllOperations method to atom and bonds operations to allow renderers rely on final state of model before rendering
- added deleting of atoms and bonds from molecules struct to synchronize molecules and macromolecules modes
> #5949 - Delete of micromolecules bonds works wrong (or doesn't work)

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
- packages/ketcher-core/src/domain/helpers/monomers.ts
- changed implementation of searching first monomers in selection (in this case monomer can be in the middle of the chain and does not have free r1 attachment point)
- changed antisense base for Adenine
> #6107 - Create Antisense Strand doesn't work in some cases

- packages/ketcher-core/package.json
- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/editor/modes/FlexMode.ts
- packages/ketcher-core/src/application/editor/modes/SnakeMode.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-macromolecules/package.json
- packages/ketcher-macromolecules/src/components/modal/Open/Open.tsx
- packages/ketcher-react/package.json
- packages/ketcher-standalone/package.json
- applied snake layout in flex mode if open/paste file with antisense chain
- applied zoom to left top corner of the structures after antisense chains creation
> #6109 - Antisense of layout doesn't work on flex mode after load

- packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx
- packages/ketcher-react/src/script/ui/state/hotkeys.ts
- Use KET format to save in Clipboard instead of RXN
- Firefox doesn't support MIME types other than text/plain in ClipboardItem, and RXN format saved by default to text/plain supports only chemical elements
- When reading from Clipboard Firefox reads only chemical elements as text/plain saved to it is in RXN format
> #5476 - Copy/Cut and Paste using Ctrl+C/X and Ctrl+V doesn't work for static elements in Mozilla Firefox

- packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
The bug was caused by [validation](https://github.com/epam/ketcher/blob/master/packages/ketcher-core/src/domain/serializers/ket/validate.ts) that checks if passed data satisfies rules from [scheme](https://github.com/epam/ketcher/blob/master/packages/ketcher-core/src/domain/serializers/ket/schema.json).
Ambiguous monomers templates weren’t taken into consideration inside [this filtering](https://github.com/epam/ketcher/blob/master/packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts#L305-L336) and were passed to the validation that threw an exception from the issue’s description.
Added ambiguous monomers to the filter in oder to exclude them from the further processing.
> #5796 - Indigo functions doesn't work if monomer on micro canvas - system throws an error: Error: Cannot deserialize input JSON.

- packages/ketcher-core/src/application/editor/EditorHistory.ts
- packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
- packages/ketcher-core/src/application/editor/operations/coreAtom/atom.ts
- packages/ketcher-core/src/application/editor/operations/coreBond/bond.ts
- packages/ketcher-core/src/application/editor/operations/drawingEntity/index.ts
- packages/ketcher-core/src/application/render/renderers/RenderersManager.ts
- packages/ketcher-core/src/domain/entities/Command.ts
- packages/ketcher-core/src/domain/entities/CoreBond.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Operation.ts
- added invertAfterAllOperations method to atom and bonds operations to allow renderers rely on final state of model before rendering
- added deleting of atoms and bonds from molecules struct to synchronize molecules and macromolecules modes
> Backmerge: #5949 - Delete of micromolecules bonds works wrong (or doesn't work)

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
- packages/ketcher-core/src/domain/helpers/monomers.ts
- changed implementation of searching first monomers in selection (in this case monomer can be in the middle of the chain and does not have free r1 attachment point)
- changed antisense base for Adenine
> Backmerge: #6107 - Create Antisense Strand doesn't work in some cases

- packages/ketcher-core/package.json
- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/editor/modes/FlexMode.ts
- packages/ketcher-core/src/application/editor/modes/SnakeMode.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-macromolecules/package.json
- packages/ketcher-macromolecules/src/components/modal/Open/Open.tsx
- packages/ketcher-react/package.json
- packages/ketcher-standalone/package.json
* #6109 - Antisense of layout doesn't work on flex mode after load
- applied snake layout in flex mode if open/paste file with antisense chain
- fixed open file implementation
* #6083 - Creation of antisense chain causes monomer re-arrangement on the flex canvas
- applied zoom to left top corner of the structures after antisense chains creation
- updated ketcher version to 2.28.0-rc.2
> Backmerge: #6109 - Antisense of layout doesn't work on flex mode after load

- packages/ketcher-macromolecules/src/components/menu/menuItem/MenuItem.tsx
- packages/ketcher-macromolecules/src/helpers/canvas.ts
Closes:
#4338 - After Undo/Redo actions Enter repeats these actions.
#5139 - After pressing the Clear Canvas button in sequence-editing view, the Enter button does not start a new sequence but erases it
> #5139 - After pressing the Clear Canvas button in sequence-editing view, the Enter button does not start a new sequence but erases it

- documentation/help.md
- packages/ketcher-core/src/application/utils.ts
- packages/ketcher-core/src/domain/serializers/mol/molSerializer.ts
- packages/ketcher-core/src/domain/serializers/mol/molfile.ts
- packages/ketcher-react/src/script/ui/data/schema/options-schema.ts
- added ignoreChiralFlag parameter to be used in mol v2000 deserialization during setMolecule and openning files methods
- removed ignoreChiralFlag parameter from serialization
> Backmerge: #6161 - Stereo flags are displayed despite enabling 'Ignore chiral flag' in MOL V2000 files

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
When (the first/all) monomer(s) is replaced with one from the palette, the bond from the previous node will not be deleted while there is not the previous node.
Fixes #5341
> #5341 - Replacing all monomers (or part of them) in edit mode - works wrong - system cuts sequence on two

- ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDXML-Enhanced-Stereochemistry/cdxml-enhanced-stereochemistry.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDXML-Files/cdxml-files.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts
> Autotests: #6043 - autotests replace file comparison for cdxml files only operations with valid helper functions verifyfileexport

- .gitignore
- package-lock.json
- packages/ketcher-core/.eslintignore
- packages/ketcher-core/.prettierignore
- packages/ketcher-core/package.json
- packages/ketcher-core/src/domain/serializers/ket/validate.ts
Fix the issue mentioned in:
- #3627
- #853
Supersedes:
- #4749
Referring to [rrodionov91's comment](https://github.com/epam/ketcher/pull/4749#issuecomment-2149694336) , it was preferred to provide a solution using ajv, to avoid switching to jsonschema.
This PR uses ajv-cli to pre-compile the validation schema and allow ketcher to run under restrictive CSP header.
Ajv is removed from ketcher-core dependencies as not used anymore, replaced by ajv-cli only.
Ajv persists in ketcher-react as it is used and doesn't need pre-compilation.
This change has been successfully used in production without any issues. Please consider merging this change so all projects with restrictive Content Security Policies can also benefit from this excellent piece of software. =)
> #3627 - Ketcher requires unsafe-eval in order to run, which contradicts content security policy best practises

- packages/ketcher-standalone/rollup.config.js
- fixed build for esm base64 ketcher-standalone
> #6246 - Import indigo with EXPORT_ES6 & USE_ES6_IMPORT_META options

- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/AtomMenuItems.tsx
Issue => https://github.com/epam/ketcher/issues/5696
- **Description of Changes**
Added logic to prevent adding attachment points to a molecule if it is already connected to a monomer.
This decision was made based on a discussion with @rrodionov91 , where it was concluded that this implementation aligns better with the current functionality.
- **Done**
Implemented a check for monomer connections when adding attachment points.
Disabled the "Add Attachment Point" button if a molecule is connected to a monomer.
https://github.com/user-attachments/assets/1acc41ad-b308-4b8c-b4a8-72179e141f0e
> #5696-Adding Attachment point to microstructure already connected to monomer - causes problems

- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-react/src/Editor.tsx
#6370 - Inconsistent zoom behavior when inserting a molecule via setMolecule and Paste from Clipboard/Open from File
- added autozoom for setMolecule and addFragment in macro mode
#6375 - Ketcher renders editor twice in dev mode
- removed react strict mode from editor
> Backmerge: #6370 - Inconsistent zoom behavior when inserting a molecule via setMolecule and Paste from Clipboard/Open from File 

- packages/ketcher-core/src/domain/constants/monomers.ts
- packages/ketcher-core/src/domain/helpers/rna.ts
Issue => https://github.com/epam/ketcher/issues/6196
https://github.com/user-attachments/assets/49abd871-aec0-4e37-bf5b-00e0b3456364
> Backmerge:#6196-Ambiguous DNA bases (N, D, H, W) wrongly converted to DNA bases on antisense creation

- packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
This is how to looks like new ordered sense chains
> #6098 Two sense to antisense connection order problem

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
> Backmerge: #6272 - Cursor position after adding preset in sequence mode causes an incorrect sequence formation

- packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
Add handling for hydrogen attachment point in MacromoleculesConverter
> #6219-unable-to-save-to-helm-hydrogen-connection-between-micromolecule-with-ap-and-monomer

- ketcher-autotests/tests/Macromolecule-editor/Antisense-Chains/antisense-chains.spec.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
Changed starting position for flex mode.
> #6132 - System should not re-layout canvas in case of antisense creation

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.replaceMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Nucleotide.ts
- packages/ketcher-core/src/domain/types/monomers.ts
Fix SequenceMode.modifySequenceInRnaBuilder replacing a monomer for other isAmbiguous value.
Fix #6084
Fix #6085
Fix SequenceMode.modifySequenceInRnaBuilder replacing a monomer for other isAmbiguous.
Fix RnaEditorExpanded adding keyDown handle for Escape, Enter.
Fix resetRnaBuilderAfterSequenceUpdate adding turnOffEditMode;
Fix SequenceItemContextMenu consts with enum.
Fix Editor.events.selectTool, .rightClickSequence using single arguments only.
Fix npm scripts adding test:types, use in prepush.
Fix editorEvent adding typing, adding keydown event.
Fix OpenOptions interactivity visuals.
Fix snapshots for OpenOptions interactivity visuals.
> #6084 - system doesnt allow select ambiguous monomers from the library

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.replaceMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- packages/ketcher-core/src/domain/entities/Nucleotide.ts
- packages/ketcher-core/src/domain/types/monomers.ts
Fix SequenceMode.modifySequenceInRnaBuilder replacing a monomer for other isAmbiguous value.
Fix #6084
Fix #6085
Fix SequenceMode.modifySequenceInRnaBuilder replacing a monomer for other isAmbiguous.
Fix RnaEditorExpanded adding keyDown handle for Escape, Enter.
Fix resetRnaBuilderAfterSequenceUpdate adding turnOffEditMode;
Fix SequenceItemContextMenu consts with enum.
Fix Editor.events.selectTool, .rightClickSequence using single arguments only.
Fix npm scripts adding test:types, use in prepush.
Fix editorEvent adding typing, adding keydown event.
Fix OpenOptions interactivity visuals.
Fix snapshots for OpenOptions interactivity visuals.
> Backmerge: #6084 - Backmerge system doesnt allow select ambiguous monomers from the library (#6451)

- ketcher-autotests/tests/Macromolecule-editor/Antisense-Chains/antisense-chains.spec.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
Changed starting position for flex mode.
> Backmerge: #6132 - System should not re-layout canvas in case of antisense creation

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
> Backmerge: 6493 - Undo of deleted bond on sequence mode causes "ghost" monomer appearence on the canvas

- ketcher-autotests/tests/API/api-set-get-molecule.spec.ts
- ketcher-autotests/tests/API/view-only-mode.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files-export-import-query-features.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/SDF-Files/sdf-files.spec.ts
- ketcher-autotests/tests/Indigo-Tools/Aromatize-Dearomatize/aromatize-dearomatize.spec.ts
- ketcher-autotests/tests/Indigo-Tools/Calculate-CIP-Tool/calculate-cip-tool.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Antisense-Chains/antisense-chains.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Erase-Tool/erase-tool.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher2.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher4.spec.ts
- ketcher-autotests/tests/Reactions/Cascade-Reactions/cascade-reactions.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/attachment-point-tool.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-tool.spec.ts
> Autotests: #6511 - Removed unnecessary metaDataIndexes from verifyFileExport calls

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/utils.ts
> Backmerge: #6546 - Macro structure duplicated on canvas when using ketcher.getMolfile() and pasting

- example/package.json
- example/src/index.tsx
- package-lock.json
Fix example enabling routes for popup and duo for vite.
Fix #4145
> #4145 - fix implement popup versions of ketcher and routing for vite from master

- ketcher-autotests/tests/File-Management/Open-And-Save-Files/SDF-Files/sdf-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Save-File/save-file.spec.ts
- ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts
… valid helper functions (verifyFileExport)
> #6364 - Autotests: Replace File comparison (for SDF files ONLY!) operations with valid helper functions (verifyFileExport)

- README.md
- packages/ketcher-core/src/application/editor/actions/paste.ts
- packages/ketcher-core/src/application/ketcher.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
Closes: 
#6608 - API setMolecule moves molecule off-canvas on second call
#6607 - README missing coordinate units for setMolecule and addFragment API methods
> Backmerge: #6608 - API setMolecule moves molecule off-canvas on second call

- packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
> Backmerge: #6159 - Aromatizing doesn't work for Pyridone and Pyrone (molecules from Template library)

- packages/ketcher-core/src/application/editor/modes/BaseMode.ts
- packages/ketcher-core/src/application/indigo.ts
- packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
- packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
- removed format autodetection during copy/paste from ketcher
- added sequence-type parameter to indigo convert payload
> Backmerge: #6588 - Peptide sequence not pasting directly on canvas

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/editor/editorEvents.ts
- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/application/render/renderers/sequence/BaseSequenceItemRenderer.ts
- packages/ketcher-macromolecules/src/EditorEvents.tsx
Closes:
- #6632 - New sequence appears gray after clearing the canvas in non-sync mode
- #6631 - Sync mode causes incorrect letter input after adding a monomer in non-sync mode
(cherry picked from commit dc7643cca39958e0f4384c8889795912dc3903f8)
> #6632 - New sequence appears gray after clearing the canvas in non-sync mode (#6656)

- packages/ketcher-core/src/application/render/renderers/sequence/SequenceViewModel/SequenceViewModel.ts
- packages/ketcher-core/src/domain/entities/index.ts
- packages/ketcher-macromolecules/src/components/contextMenu/SequenceItemContextMenu/SequenceItemContextMenu.tsx
- packages/ketcher-macromolecules/src/components/modal/ConfirmationDialog/ConfirmationDialog.tsx
- packages/ketcher-macromolecules/src/components/modal/modalContainer/types.ts
(cherry picked from commit 6ce99a4d8bea8f644374cd7ba3961898dedacd86)
> Backmerge: #6615 - Missing warning message when deleting all hydrogen bonds between two chains

- ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDXML-Files/cdxml-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Image-files/image-files.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/InChi/InChi.spec.ts
- ketcher-autotests/tests/File-Management/Open-And-Save-Files/Rxn-Files/rxn-files.spec.ts
- ketcher-autotests/tests/File-Management/Smile-Files/smile-files.spec.ts
- ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts
- ketcher-autotests/tests/Reactions/Reaction-tools/Plus-and-Arrow-tools/plus-and-arrows-tools.spec.ts
- ketcher-autotests/tests/Structure-Creating-&-Editing/Simple-Objects/action-on-simple-objects.spec.ts
- ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts
- ketcher-autotests/tests/Templates/Functional-Groups/functional-groups.spec.ts
- ketcher-autotests/tests/Templates/Template-Manipulations/Manipulations-rings.spec.ts
- ketcher-autotests/tests/Templates/User-Templates/user-templates.spec.ts
- ketcher-autotests/tests/User-Interface/Clear-Canvas/clear-canvas.spec.ts
- ketcher-autotests/tests/User-Interface/Hot-Keys/hotkeys.spec.ts
… page); function on selectClearCanvasTool(page);
> #6633 - Autotests: Replace selectTopPanelButton(TopPanelButton.Clear, page); function on selectClearCanvasTool(page);

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> Backmerge: #6617 - Empty element appears after undoing line deletion in Sequence mode and switching to Flex/Snake mode

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
> Backmerge: #6443 - System allow to select single antisense symbol that causes an error if it got deleted

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/domain/entities/LinkerSequenceNode.ts
- prevent caret move if added sequence item becomes part of linker
> #6783 - Incorrect cursor jumps after phosphate insertion in middle or at end of sequence

- packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
- packages/ketcher-core/src/domain/entities/LinkerSequenceNode.ts
- prevent caret move if added sequence item becomes part of linker
> Backmerge: #6783 - Incorrect cursor jumps after phosphate insertion in middle or at end of sequence

- packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
##What was the issue?
On Macromolecules mode RNA Editor tab if any presets selected in presets section on sequence mode. If I press the `Enter` key the a new preset was duplication happens (because of triggering the onSave func on the case). That was blocking the present selection and the Enter key behaviour.
##What was done?
Regarding the case onSave method has been replaced with the Editor New Sequence method. `Enter` key starts new sequence in editor as expected.
> #6870 - Enter key adds undeletable preset to preset section

- ketcher-autotests/tests/specs/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useMonomerExpansionHandlers.ts
- packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/MacromoleculeMenuItems.tsx
> Backmerge: #7008 – Support of expanded monomer options doesn't work if monomer loaded from file/clipboard

- packages/ketcher-macromolecules/src/components/macromoleculeProperties/CalculateMacromoleculePropertiesButton.tsx
- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
> #7033 – calculateMacroProperties API is called immediately on sequence selection, even when Calculate Properties window is closed

- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
- fixed recalculate properties to handle only micro structures selected
> #7017 - “Calculate Properties” shows wrong behavior when sequence is connected to microstructure

- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
- fixed recalculate properties to handle only micro structures selected
> Backmerge: #7017 - “Calculate Properties” shows wrong behavior when sequence is connected to microstructure

- ketcher-autotests/package.json
Pass GENERATE_DATA environment variable to Docker container for automatic data generation during test runs without manual .env file editing.
> #6340 - Get rid of GENERATE_DATA flag in updating example files process 

- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- added monomer to atom bond to selection
> Backmerge: #7074 - Formula in "Calculate Properties" window is not updated when selecting monomers with connected microstructure

- packages/ketcher-macromolecules/src/components/TopMenuComponent/TopMenuComponent.tsx
- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
- packages/ketcher-macromolecules/src/state/common/editorSlice.ts
Closes:
- #7034 - Unipositive ions default value is shown in nM instead of mM for double-stranded sequence selection
- #7030 - Missing Celsius symbol (°C) in “Melting temperature” label
- fixed default value for upc
- fixed title for melting temperature
- fixed memory leak for selectEntities event
- fixed sending macro properties calculation request with stale upc and nac measurement units
> #7034 - Unipositive ions default value is shown in nM instead of mM for double-stranded sequence selection

- packages/ketcher-macromolecules/src/components/TopMenuComponent/TopMenuComponent.tsx
- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
- packages/ketcher-macromolecules/src/state/common/editorSlice.ts
Closes:
#7034 - Unipositive ions default value is shown in nM instead of mM for double-stranded sequence selection
#7030 - Missing Celsius symbol (°C) in “Melting temperature” label
- fixed default value for upc
- fixed title for melting temperature
- fixed memory leak for selectEntities event
- fixed sending macro properties calculation request with stale upc and nac measurement units
> Backmerge: #7034 - Unipositive ions default value is shown in nM instead of mM for double-stranded sequence selection

- packages/ketcher-core/src/domain/helpers/monomers.ts
- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
> #7085 - Ketcher does not send bond type to Indigo if connection is different from R2–R1, causing missing data in "Calculate Properties"

- packages/ketcher-core/src/domain/helpers/monomers.ts
- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
> Backmerge: #7085 - Ketcher does not send bond type to Indigo if connection is different from R2–R1, causing missing data in "Calculate Properties"

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/application/render/restruct/resgroup.ts
- separated rendering of attachment point atoms and leaving group atoms for expanded monomers from hover rendering
> #7027 - Incorrect highlight (missing fill) for leaving-group atoms

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/application/render/restruct/resgroup.ts
- separated rendering of attachment point atoms and leaving group atoms for expanded monomers from hover rendering
> Backmerge: #7027 - Incorrect highlight (missing fill) for leaving-group atoms

- packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts
> Backmerge: #7096 - Clearing canvas while "Calculate Properties" window is open causes console errors

- packages/ketcher-core/src/domain/entities/BaseMonomer.ts
- packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- added recalculation of attachment points after setting new monomerItem to monomer
> Backmerge: #7200 - App crashes after modifying amino acids and switching to Micro mode

- packages/ketcher-core/src/application/render/renderers/TransientView/ModifyAminoAcidsView.ts
- packages/ketcher-core/src/domain/helpers/monomers.ts
- packages/ketcher-macromolecules/src/components/contextMenu/SelectedMonomersContextMenu/helpers.ts
#7203 - N-methylation is shown as available for Hyp even though it shouldn't be
- fixed context menu items list collecting rules
#7202 - Incorrect order of amino acid modification options in context menu
- applied sorting for amino acid modification menu items
> Backmerge: #7203 - N-methylation is shown as available for Hyp even though it shouldn't be

- packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
> Backmerge: #7266 - Oligonucleotides input field becomes unresponsive after entering zero

- ketcher-autotests/tests/specs/Bugs/ketcher-3.6.0-bugs.spec.ts
> #7279 - should handle undefined events property without throwing error

- packages/ketcher-macromolecules/src/EditorEvents.tsx
> #7117 – Chemical elements disappear when attempting to Expand the Structure in Micro mode after selecting one in Macro mode

- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-core/src/application/render/restruct/resgroup.ts
- packages/ketcher-core/src/domain/entities/sgroup.ts
- packages/ketcher-react/src/script/editor/tool/sgroup.ts
- packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
- added set expand = true to nucleotide component sgroups during creation (same as for superatoms)
- added usage of uppercase for nucleotide component class value
> #7314 - Preview: Structure disappears after removing abbreviations and adding nucleotide component to phosphate group

- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
Closes:
#7365 - Console errors appear when using actions on structures with nucleotide component marking
#7386 - Delete operation causes exception: Uncaught (in promise) Error: Minified Redux error
- moved getState upper to scope
> #7365 - Console errors appear when using actions on structures with nucleotide component marking

- packages/ketcher-react/src/script/ui/state/editor/index.js
- packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
Closes:
https://github.com/epam/ketcher/issues/7365 - Console errors appear when using actions on structures with nucleotide component marking
https://github.com/epam/ketcher/issues/7386 - Delete operation causes exception: Uncaught (in promise) Error: Minified Redux error
- added sleep call to fix redux errors (same approach as was for other calls)
> Backmerge: #7365 - Console errors appear when using actions on structures with nucleotide component marking

- packages/ketcher-react/src/script/editor/Editor.ts
> Backmerge: #7627 – Selection tools stop working after creating first monomer via wizard when many structures are on canvas

- packages/ketcher-react/src/script/editor/tool/create-monomer.ts
> #7725 – Hand tool and Area Selection Tool buttons close Monomer creation wizard if pressed

- packages/ketcher-core/src/application/editor/Editor.ts
- packages/ketcher-core/src/application/editor/editorEvents.ts
- packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts
- packages/ketcher-core/src/domain/AttachmentPoint.ts
- packages/ketcher-macromolecules/src/EditorEvents.tsx
- packages/ketcher-react/src/script/editor/HoverIcon.ts
Closes:
https://github.com/epam/ketcher/issues/7722 - Connection preview does not follow cursor and AP to AP connection is not possible
https://github.com/epam/ketcher/issues/6581 - Monomer placement offset from cursor when Ketcher runs in a popup with increased browser zoom
- fixed error in firefox console related to HoverIcon (added safety check)
- added window resize handler in CoreEditor to reset canvas bbox data
- added additional check in monomer mouseleave handler to stop handler if mouse goes to attachment point (firefox issue)
> Backmerge: #7722 - Connection preview does not follow cursor and AP to AP connection is not possible

- packages/ketcher-core/src/application/editor/Editor.ts
- added preventing for macro copy-paste events if editor is in micro mode
> Backmerge: #7152 - Copy keyboard shortcut works wrong for text content

- packages/ketcher-react/src/script/editor/Editor.ts
- fixed casting 0 to false for leaving group atom id
> Backmerge: #7837 - Unable to create monomer if molecule loaded from KET

- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- added recalculation of fragments after monomer creation
- skipped connected component search for monomers
> #7688 - Attached groups are lost when saving and reopening monomer created via Monomer Wizard in KET format

- packages/ketcher-core/src/domain/entities/struct.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- added recalculation of fragments after monomer creation
- skipped connected component search for monomers
> Backmerge: #7688 - Attached groups are lost when saving and reopening monomer created via Monomer Wizard in KET format

- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
> #7877 - Ketcher losts attachment point name on loading s-group from mol v3000

- packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts
> Backmerge: #7877 - Ketcher losts attachment point name on loading s-group from mol v3000 

- packages/ketcher-core/src/application/render/raphaelRender.ts
- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/views/components/MonomerCreationWizard/MonomerCreationWizard.tsx
> #7804 – Incorrect atom label upon monomer saving when removing automatically assigned attachment point via R-group

- packages/ketcher-core/src/application/render/raphaelRender.ts
- packages/ketcher-core/src/application/render/restruct/reatom.ts
- packages/ketcher-react/src/script/editor/Editor.ts
- packages/ketcher-react/src/script/ui/views/components/MonomerCreationWizard/MonomerCreationWizard.tsx
> Backmerge: #7804 – Incorrect atom label upon monomer saving when removing automatically assigned attachment point via R-group

- packages/ketcher-macromolecules/src/components/Layout/Layout.tsx
- packages/ketcher-react/src/hooks/index.ts
- packages/ketcher-react/src/hooks/useRaf.ts
- packages/ketcher-react/src/hooks/useRequestAnimationFrame.ts
- packages/ketcher-react/src/script/ui/views/toolbars/ArrowScroll/ArrowScroll.tsx
issue >> https://github.com/epam/ketcher/issues/7770
- Split top bar scroll logic in Layout into no-arg functions and pass to ArrowScroll
- ArrowScroll: stop event propagation in onClick handlers; type callbacks as () => void
- Fixes runtime error: \"Cannot read properties of undefined (reading 'stopPropagation')\" when holding the right arrow (useInterval calls without event)
> #7770 - Pressing Right Scroll Arrow button of top menu cause exception to console

- ketcher-autotests/tests/specs/Macromolecule-editor/Import-Saving-Files/import-saving-fasta.spec.ts
> Autotests: #7472 - autotests transform isolated test execution to clear canvas test execution for import-saving-fasta.spec.ts

- ketcher-autotests/tests/specs/Macromolecule-editor/Import-Saving-Files/import-saving-sequence.spec.ts
> Autotests: #7473 - Transform isolated test execution to clear canvas test execution for import saving sequencespects
