gulp/style-html.js, gulp/tests.js, gulp/utils.js, package-lock.json, package.json, src/script/index.js, test/io/io.js
Changed to @babel/X dependencies where possible
Updated Babel config
=> Properly migrated to Babel 7.X

package.json, src/script/ui/state/action/index.js, src/script/ui/state/editor/index.js
- add temporary solution to copy state into global variable
- update lint-staged config
=> #92 Get state call throws exception

src/script/ui/component/structrender.jsx, src/script/ui/component/view/openbutton.jsx, src/script/ui/state/editor/index.js
- fix Openbutton issue
- update structrender.jsx
=> # Recognize function does not work

src/script/ui/dialog/mainmenu/recognize.jsx
- add check if image preview is supported
- add info message if file is empty or incorrect
=> #28 Recognize Molecule: pictures in tif-format cannot be loaded

src/script/ui/state/hotkeys.js
Use latest state on Redux on keydown action
=> #118 copy and cut actions don't work on canvas

src/contexts/formContext.tsx, src/contexts/index.ts, src/hooks/index.ts, src/hooks/useFormContext.tsx, src/script/ui/component/form/form.jsx, src/script/ui/dialog/toolbox/rgroup-logic.jsx
- add FormContext & useFormContext hook
- update rgroup-logic.jsx
=> #119 dialog for editing rgroup does not work

src/script/chem/struct/index.js, src/script/editor/index.js
Add SimpleObjects to Struct.clone()
=> #117 cut command does not work for Simple Objects

README.md, src/script/chem/smiles/index.js
- add transformation of [5, 6, 7, 8] bond types into SMILES
=> #31 query bonds are replaced with Single Smiles

src/icons/files/shape-circle.svg, src/icons/files/shape-rectangle.svg, src/script/ui/component/actionmenu.jsx
- update shape-circle.svg
- update shape-rectangle.svg
- add icon while sub-menu is opened
=> #124 Icon in toolbox is missed while sub-menu is opened

src/script/chem/struct/index.js, src/script/editor/actions/paste.js, src/script/editor/shared/closest.js, src/script/render/restruct/resimpleobject.js
- move 'center' method into SimpleObject
- update paste.js to work with simple objects
=> #125 cannot insert simple object as fragment

src/script/editor/tool/simpleobject.js
- add support of undo/redo for simple objects
=> #129 undo does work for simple objects

src/script/editor/tool/reactionplus.js, src/script/format/chemGraph/toGraph/prepare.js, src/script/ui/data/convert/structformat.js
- add additional params to JSON.stringify call
- save all fragments as a single molecule
- fix reactionplus.js
=> #132 ketcher's format redundancy

src/script/editor/operations/op-frag.js
=> #134 dragging doe not work properly

example/package.json, example/src/index.tsx, example/yarn.lock, package.json, src/index.tsx, src/script/index.js, src/script/ui/component/cliparea.jsx, src/script/ui/dialog/mainmenu/about.jsx, yarn.lock
- add react-app polyfill
- fix issue with parsing of mol strings
- fix issue with closing modal windows by pressing ESC button
=> ketcher does not work in IE11

src/script/editor/actions/simpleobject.js, src/script/editor/operations/op.js, src/script/editor/shared/closest.js, src/script/editor/tool/simpleobject.js, src/script/render/restruct/resimpleobject.js
- fix selection
- add anchor points
- add resizing for circle, rectangle and line
=> #112 simple objects selection and dragging enhancements

src/script/ui/component/actionmenu.jsx
- update logic to show active menu item
=> #147 bond tool does not work correctly

src/script/editor/actions/atom.js
=> #146 Deleting the sprouted bond does not work correctly

src/script/ui/component/cliparea.jsx, src/script/ui/component/dialog.jsx
- update dialog.jsx
- cancel paste to cliparea if event.target is form element
=> #143 pasting into 'Open structure' box does not work

src/script/ui/dialog/toolbox/atom.jsx
=> #152 Atom number field is empty in 'Atom properties' dialog

example/package.json, example/src/App.tsx, example/yarn.lock
=> #148 update miew version

src/script/ui/dialog/mainmenu/save.jsx
- add alert to show error (should be replace by custom dialog in the future)
=> #175 cannot save incorrect s-group

src/script/ui/dialog/mainmenu/analyse.jsx
- delete allowMovement function
=> #213 User can't copy values from text fields in "Calculated Values" window

src/script/ui/component/cliparea.jsx, src/script/ui/dialog/mainmenu/open.jsx, src/script/ui/state/hotkeys.js
=> #193 Copy to Clipboard doesn't work

src/script/ui/state/server/index.js
=> #187 Blank page appears while saving file with R-group

src/script/editor/tool/simpleobject.js, src/script/render/restruct/resimpleobject.js
- add logic to calculate distance to sides of rectangle
=> #226 incorrect selection of rectangles

src/script/chem/molfile/index.js, src/script/ui/data/convert/structformat.js, src/script/ui/state/shared.js
- add condition to check mol version
=> #228 File V3000 format with Atom NOT List is not loaded

src/script/editor/tool/sgroup.js
- clear selection after pressing on Ok button
=> #173 group selection doesn't disappear

src/script/ui/state/hotkeys.js, src/script/ui/state/index.js
- update global state initialization
=> #237 'Cut', 'Copy' buttons doesn't work - error appears

packages/ketcher-react/src/script/editor/index.js, packages/ketcher-react/src/script/editor/operations/base.js, packages/ketcher-react/src/script/editor/operations/op.js
https://github.com/epam/ketcher/issues/54
=> #54 fire custom event on sctructure change

packages/ketcher-react/src/script/ui/dialog/mainmenu/analyse.jsx
=> #215 Show error to user in case any error happened during calculating values

packages/ketcher-react/src/script/ui/component/actionmenu.jsx, packages/ketcher-react/src/script/ui/state/toolbar/index.js
=> #248 getComputedStyle Error when parameter 1 is not of type 'Element'

packages/ketcher-react/src/script/ui/dialog/mainmenu/analyse.jsx
update formulaInputMarkdown method
=> #279 Calculated Values displays some values from last calculation

packages/ketcher-react/src/script/ui/app/index.jsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/AtomInfo/AtomInfo.module.less, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/ElementsTable/ElementsTable.jsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/GenericGroups/components/GenGroup.module.less
Removed eslint and stylelint warnings in files changed by me
=> #262 Code cleanup

packages/ketcher-core/src/format/FormatterFactory.ts, packages/ketcher-core/src/format/GraphFormatter.ts, packages/ketcher-core/src/format/MolfileV2000Formatter.ts, packages/ketcher-core/src/format/RxnFormatter.ts, packages/ketcher-core/src/format/ServerFormatter.ts, packages/ketcher-core/src/format/SmilesFormatter.ts, packages/ketcher-core/src/format/structFormatter.types.ts, packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts, packages/ketcher-react/src/script/ketcher.ts
- update StructFormatter methods
- add containsReaction() method
- add getRxnAsync() method
=> #296 Ketcher API: Add possibility to save RXN files

packages/ketcher-react/src/script/ui/state/shared.js, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.jsx
update Miew.jsx, 
update Save.jsx
update shared.js
=> #300 User can't open Structure from file

packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/components/FormulaInput/FormulaInput.jsx
=> #305 'Calculated Values' of R-Group-member shows incorrect message in Standalone mode 

packages/ketcher-react/src/script/ui/state/server/index.js
fix selection mapping (reactions are OOS)
=> #310 Selection processing doesn't work correctly 

packages/ketcher-react/src/script/ui/component/form/systemfonts.jsx
=> #320 fonts drop-down updates

packages/ketcher-react/src/script/chem/molfile/molfile.ts
- update logic of saving atoms to mol v2000
=> #322 Error when User try to save structure in SMARTS

packages/ketcher-react/src/script/ui/state/hotkeys.js
- add alert to inform about unsupported bonds number
=> #177 User can't copy/cut and paste SRU-polymer

packages/ketcher-react/src/script/editor/operations/simpleObject.ts, packages/ketcher-react/src/script/render/restruct/resimpleobject.js
…ulating them would be reimplemented in #315
=> #317 - remove drawing of diagonal reference points

packages/ketcher-standalone/src/infrastructure/services/struct/StandaloneStructService.ts
=> #211 'Check Structure' tool not displays warnings

packages/ketcher-core/src/chemistry/entities/Struct.ts, packages/ketcher-react/src/script/chem/molfile/molfile.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
=> #145 Add multiple arrow support for the same canvas

packages/ketcher-react/src/script/editor/operations/bond/index.ts
- update bond update operation
=> #365 cut command dos not work for benzene

packages/ketcher-react/src/script/chem/molfile/common.js
=> #384 xBonds is not defined

packages/ketcher-react/src/script/ketcher.ts
- add optional rescale parameter to setMolecule method
=> #386 update ketcher API

packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/components/FormulaInput/FormulaInput.jsx
=> #388 'Calculated values' fields are editable

packages/ketcher-react/src/script/editor/tool/template.js, packages/ketcher-react/src/script/ui/state/server/index.js
=> #396 Invalid behavior when fusing cycles bond-to-bond

packages/ketcher-react/src/script/ui/state/server/index.js
- update reindexMap generation
=> #319 Incorrect selection in reactions

packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
=> Revert "make generation of svg to a separate element"

packages/ketcher-react/src/script/editor/actions/erase.js, packages/ketcher-react/src/script/editor/operations/atom/index.ts, packages/ketcher-react/src/script/editor/operations/base.ts, packages/ketcher-react/src/script/editor/operations/bond/index.ts, packages/ketcher-react/src/script/editor/shared/action.ts
sort operations (Add_Atom should be before Add_Bond)
=> #419 Incorrect behavior of Ketcher after deleting of a part of R-Group member

packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/components/FormulaInput/FormulaInput.jsx
- add handlers to contenteditable div
- update content generation
=> #429 "+" sign does not presented in formula

packages/ketcher-react/src/script/ui/component/structrender.jsx
=> #431 User templates are shown without the images

packages/ketcher-react/src/script/editor/actions/erase.js, packages/ketcher-react/src/script/editor/operations/atom/AtomAttr.ts, packages/ketcher-react/src/script/editor/operations/fragmentStereoAtom.ts, packages/ketcher-react/src/script/editor/operations/sgroup/SGroupAttr.ts, packages/ketcher-react/src/script/editor/operations/sgroup/sgroupAtom.ts
- update sorting of operations (erase.js)
- add priority to S-Group and AtomAttr operations
- update fragmentStereoAtom operations
=> #433  deleting of a part of S-Group member issue

packages/ketcher-react/src/script/ui/state/options/index.js, packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/Analyse.jsx
=> #445 Display Elemental Analysis value with one decimal place

packages/ketcher-react/src/script/ui/component/form/form.jsx
=> #514 Blank page and a console error appear while saving

packages/ketcher-core/src/chemistry/serializers/ket/schema.json, packages/ketcher-react/src/script/render/restruct/resgroup.js
=> Revert "194 - Stereo labels after pasting display incorrectly"

packages/ketcher-react/src/script/render/restruct/reatom.ts
- update reatom to ingore enchacedStereoFlag if fragment is null
=> #621 The structure with R-Group is not visible

packages/ketcher-react/src/script/editor/actions/paste.js
filter fragments to ignore 'null' items
=> #633 load as fragment does not work

packages/ketcher-react/src/script/editor/operations/calcimplicitH.ts
update priority of calcImplicitH operation
=> #636 calc implicit H does not work properly

packages/ketcher-core/src/domain/serializers/mol/MolSerializer.ts, packages/ketcher-core/src/domain/serializers/sdf/SdfSerializer.ts, packages/ketcher-core/src/domain/serializers/smi/SmiSerializer.ts, packages/ketcher-react/src/script/editor/operations/atom/AtomAttr.ts, packages/ketcher-react/src/script/editor/operations/bond/BondAttr.ts, packages/ketcher-react/src/script/editor/operations/bond/index.ts, packages/ketcher-react/src/script/render/restruct/reatom.ts, packages/ketcher-react/src/script/ui/state/shared.js
replace node.children with node.childNodes
=> #624 IE: The structure cannot e loaded

packages/ketcher-react/src/script/editor/tool/attach.js
set default value for attachment Points
=> #652 custom template cannot be created

packages/ketcher-react/src/script/ketcher.ts, packages/ketcher-react/src/script/ui/component/view/savebutton.jsx
update 'generateImageAsync' function
=> #627 IE: save structure as SVG does not work

packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
Fix the impossibility to save the structure with a large number of atoms
=>  #612 Limitation of s-group count

packages/ketcher-react/src/script/ui/action/copyImageToClipboard.js, packages/ketcher-standalone/src/infrastructure/services/struct/StandaloneStructService.ts
Add alert when user couldn't save the structure
=>  #691 Can not save structure to clipboard with atom generics

packages/ketcher-core/src/domain/entities/Text.ts, packages/ketcher-react/package.json, packages/ketcher-react/src/script/render/restruct/ReText.ts, packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/FontControl.module.css, packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/FontControl.tsx, packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/index.ts, packages/ketcher-react/src/script/ui/views/modal/components/Text/Text.module.less, packages/ketcher-react/src/script/ui/views/modal/components/Text/Text.tsx, yarn.lock
Add the ability to set the size of fonts in the text tool
=> #703 Add Font Size

packages/ketcher-react/src/script/builders/ketcher/ButtonName.ts, packages/ketcher-react/src/script/ui/action/index.js, packages/ketcher-react/src/script/ui/action/isHidden.ts, packages/ketcher-react/src/script/ui/action/server.js, packages/ketcher-react/src/script/ui/action/tools.js, packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/RGroup/RGroup.tsx, packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/Shape/Shape.tsx, packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ToolbarMultiToolItem/ToolbarMultiToolItem.tsx, packages/ketcher-react/src/script/ui/views/toolbars/toolbar.types.ts
Expand the list of tools that can be hidden
=> #713 Hiding buttons on the left menu

packages/ketcher-react/src/script/editor/actions/bond.ts, packages/ketcher-react/src/script/editor/actions/utils.js
=> #526 180-degree angle in case of two connected double/triple bonds

README.md
ref: https://gist.github.com/lifeart/43ade02d32806b96a9da45dcf62be0ef
=> EPAM OSS: Readme update initiative

packages/ketcher-react/src/script/ui/component/form/input.jsx, packages/ketcher-react/src/script/ui/component/form/input.module.less
**Chrome:** 
**Edge:** 
**IE**
=> #769 Fixed wrong checkbox color

packages/ketcher-react/src/icons/files/template-5.svg
=> #764 Fixed Cyclobutan button's svg

packages/ketcher-core/src/domain/serializers/smi/__tests__/dfs.test.js
=>  #747 Cover by tests in serializers SMILES

packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
In some cases parsing JSON is not needed
=> #794 Template Edit Window: a lot of scrolls appear in small browser window 

packages/ketcher-core/src/domain/entities/SGroupForest.ts, packages/ketcher-react/src/script/editor/operations/sgroup/sgroupHierarchy.ts
update priority of s-group hierarchy operations
=> #975 Application hangs after undo action applying to S-Group type changes

packages/ketcher-core/src/application/editor/actions/utils.ts
=>  #986 incorrect double bonds building

packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/editor/tool/apoint.js, packages/ketcher-react/src/script/editor/tool/rgroupatom.js, packages/ketcher-react/src/script/ui/component/form/input.module.less, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.module.less, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Check/Check.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Check/Check.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Check/components/ErrorsCheck.jsx
=> Revert "#513 It should be impossible to add attachment point(s) to an atom with R-Group Label and vice versa "

packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
remove response transformation into base64
=> #371 image generation does not work

README.md, example/package.json, example/src/App.tsx, packages/ketcher-react/README.md, packages/ketcher-react/package.json, packages/ketcher-react/src/script/ui/action/server.js, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx, packages/ketcher-react/src/script/ui/views/modal/components/meta/Settings/Settings.tsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx, yarn.lock
=> #1188 implement miew viewer with miew react

package.json, yarn.lock
Using one of fixes suggested here: https://github.com/facebook/create-react-app/issues/11773#issuecomment-996926736 
The change is only at root `package.json`, so individual packages are not affected.
=> Fix hot reload in example app

packages/ketcher-polymer-editor-react/src/__snapshots__/Editor.test.tsx.snap, packages/ketcher-polymer-editor-react/src/components/modal/Open/__snapshots__/Open.test.tsx.snap, packages/ketcher-polymer-editor-react/src/components/modal/save/__snapshots__/Save.test.tsx.snap, packages/ketcher-polymer-editor-react/src/components/notationInput/inputArea/__tests__/__snapshots__/notationInput.test.tsx.snap, packages/ketcher-polymer-editor-react/src/components/shared/modal/__snapshots__/Modal.test.tsx.snap, packages/ketcher-polymer-editor-react/src/theming/mixins/mixins.ts
Possibly a temporary solution for Firefox scrollbar styling. If you wanna eventually make FF's scrollbar styling identical to Chromium-based browsers, you can see a linked issue and a draft PR linked to it
https://github.com/epam/ketcher/issues/1233
=> Add styles for firefox scrollbar

packages/ketcher-react/src/script/ui/views/toolbars/ArrowScroll/ArrowScroll.module.less, packages/ketcher-react/src/script/ui/views/toolbars/BottomToolbar/BottomToolbar.module.less, packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.module.less, packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/LeftToolbar.tsx, packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ToolbarMultiToolItem/ToolbarMultiToolItem.module.less, packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ToolbarMultiToolItem/ToolbarMultiToolItem.tsx
Update styles for left and bottom toolbars
=> #1377 implement new design of left toolbar

packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomControls.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomInput.tsx
=> #1378 Fix zoom input keystroke handling

package.json, packages/ketcher-react/src/script/ui/component/view/Atom/Atom.jsx, packages/ketcher-react/src/script/ui/component/view/Atom/Atom.module.less, packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/AtomsList/AtomsList.tsx, packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/RightToolbar.module.less, yarn.lock
added hover and selected styles for atoms list
=> #1315 atomslist styles fix

packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/GenericGroups/GenGroup.tsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/GenericGroups/GenSet.tsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/GenericGroups/GenericGroups.tsx
[Task](https://github.com/epam/ketcher/issues/1408)
=> #1408 'Add button' is disabled in Periodic table

packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/Analyse.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/components/FormulaInput/FormulaInput.jsx
'contentEditable' prop fix for preventing formula deletion
=> 1417 formula field deletion bug fix

packages/ketcher-react/src/script/ui/dialog/template/template-lib.module.less, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.module.less, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/PeriodTable.module.less, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.module.less, packages/ketcher-react/src/script/ui/views/modal/components/meta/About/About.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Check/Check.module.less, packages/ketcher-react/src/style/mixins.less, packages/ketcher-react/src/style/variables.less
=> #1448 Change the scrolls used in the forms

packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx, packages/ketcher-react/src/script/ui/dialog/template/template-lib.module.less, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.module.less, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Recognize/Recognize.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Recognize/Recognize.module.less, packages/ketcher-react/src/style/mixins.less
- redesign recognize molecule dialog
- fix styles of buttons (in recognize and templates dialogs)
- add footerContent prop in Dialog for rendering non-standard buttons set or other content (footer content, if provided, will be rendered before buttons)
- fix some global styles in Dialog
=>  #1097 redesign recognize molecule floating window

packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx
=> #1462 redesign miew window

packages/ketcher-react/src/script/ui/component/form/input.jsx, packages/ketcher-react/src/script/ui/component/form/input.module.less, packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo/enhancedStereo.module.less, packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo/enhancedStereo.tsx, packages/ketcher-react/src/script/ui/dialog/toolbox/sdata.jsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/TypeChoice/TypeChoice.jsx, packages/ketcher-react/src/script/ui/views/modal/components/PeriodTable/components/TypeChoice/TypeChoice.module.less, packages/ketcher-react/src/style/variables.less
changes styles for Stereochemistry window
changes radio buttons styles:
=> Floating Windows - Redesign Enhanced Stereochemistry window + radio buttons redesign

packages/ketcher-react/src/script/ui/views/modal/components/process/Check/Check.jsx
Fixed styles
Logical issues to be investigated and fixed later (behavior is the same as in demo, most likely - external issue)
=> #1356 structure check window fixes

packages/ketcher-react/src/script/ui/component/form/form/form.jsx, packages/ketcher-react/src/script/ui/dialog/toolbox/sdata.jsx, packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.jsx, packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less
- add label for 'Type'
- add delimiters in headers
- fix issues with clickable area
- limit horizontal text area extension
- fix select styles
=> #1396-s-groups-redesign-bugfix

packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/ui/component/form/Select/Select.module.less, packages/ketcher-react/src/script/ui/component/form/form/form.module.less, packages/ketcher-react/src/script/ui/component/form/input.module.less, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Atom/Atom.module.less, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Atom/Atom.tsx, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Atom/ElementNumber/ElementNumber.tsx, packages/ketcher-react/src/style/variables.less
=> #1426 Floating windows - Change Atom properties window design

packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Automap/Automap.module.less, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Automap/Automap.tsx
=> #1457 mode field in reaction automapping doesn't match mockup

packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Automap/Automap.module.less, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Automap/Automap.tsx
=> Revert "#1457 mode field in reaction automapping doesn't match mockup"

packages/ketcher-react/src/script/ui/views/modal/components/document/Open/Open.module.less, packages/ketcher-react/src/script/ui/views/modal/components/document/Open/Open.tsx, packages/ketcher-react/src/script/ui/views/modal/components/document/Open/components/TextEditor.tsx
Open structure window should contain textarea
fixed styles
=> #1450 open structure window doesn't match mockup

packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less
=> Revert "#1396 s group windows fix clickable area"

packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less
=> #1396-fix-horizontal-scroll

packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/ui/component/form/Select/Select.module.less, packages/ketcher-react/src/script/ui/component/form/input.module.less, packages/ketcher-react/src/script/ui/dialog/template/template-attach.jsx, packages/ketcher-react/src/script/ui/dialog/toolbox/sgroup.module.less, packages/ketcher-react/src/script/ui/views/modal/components/Text/Text.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Analyse/Analyse.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Check/Check.module.less, packages/ketcher-react/src/style/variables.less
fixed paddings, font-size and color for inputs and buttons
=> #1498 update font size for dialogs

packages/ketcher-react/src/script/ui/dialog/toolbox/labeledit.jsx, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx
Add "focusable" unnecessary field for focus parameter specification in Dialog Component
=> fix onFocus for Dialog component

packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/ui/component/form/Select/Select.module.less, packages/ketcher-react/src/script/ui/dialog/template/template-attach.jsx
- fixed search hover style and template window styles;
- added max-height for long lists in select dropdowns.
=> #1525 fixed design issues in templates window

packages/ketcher-react/src/script/ui/views/modal/components/Text/FontControl/FontControl.module.less
Fix dropdown arrow position in browser zoom mode
=> #1515 Text editor design issues hotfix

packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts
Here you can check the hash key that came from the server
https://www.chemspider.com/InChI.asmx?op=InChIToInChIKey
=> #1334 getting InChIKey on remote fix

packages/ketcher-react/src/script/ui/dialog/template/template-attach.jsx
fixed right column width according to Andrei Mitroshin's suggestion
=> fix right column width in template edit

packages/ketcher-react/src/script/ui/views/modal/components/meta/Settings/Settings.tsx
=> #1590 Add tooltips for open/save/reset in the settings window

packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx
Added unmount function for Dialog component
=> #1577 Fix unable to open dialogs with hot keys for the second time 

packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.module.less
removed min height to hide second scroll inside the dialog
=> #1620 fix vertical scroll in dialog

packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/editor/tool/sgroup.ts
#1539 save properties on s-groups selections
=> #1539 fix s-groups selections

packages/ketcher-core/README.md, packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts, packages/ketcher-core/src/infrastructure/services/struct/remoteStructServiceProvider.ts, packages/ketcher-react/README.md
added custom headers option to remote struct service provider
=> #1628 add custom headers

DEVNOTES.md, example/README.md
Update devnotes.md, add link to devnotes to example readme.
=> fix(#1717): update doc

packages/ketcher-core/src/application/editor/actions/bond.ts, packages/ketcher-core/src/application/editor/actions/utils.ts, packages/ketcher-react/src/script/editor/tool/bond.ts, packages/ketcher-react/src/script/ui/views/modal/components/Text/Text.tsx
add bond check to atomForNewBond
=> fix: add bond check to atomForNewBond

packages/ketcher-core/__tests__/domain/serializers/ket/fixtures/toKet.ts, packages/ketcher-core/__tests__/domain/serializers/ket/fixtures/toStruct.ts, packages/ketcher-core/src/application/editor/actions/paste.ts, packages/ketcher-core/src/application/editor/actions/text.ts, packages/ketcher-core/src/application/editor/operations/Text/TextCreateDelete.ts, packages/ketcher-core/src/application/render/restruct/reloop.js, packages/ketcher-core/src/application/render/restruct/retext.ts, packages/ketcher-core/src/domain/entities/text.ts, packages/ketcher-core/src/domain/serializers/ket/schema.json, packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts, packages/ketcher-react/src/script/editor/tool/apoint.ts, packages/ketcher-react/src/script/editor/tool/text.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx, packages/ketcher-react/src/script/ui/views/modal/components/Text/Text.tsx, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
update text position for ket format with pos, update tests (WIP)
=> feat: update text position for ket format with pos

package.json, packages/ketcher-core/package.json, packages/ketcher-core/src/domain/serializers/ket/fromKet/textToStruct.ts, packages/ketcher-core/src/domain/serializers/ket/toKet/textToKet.ts, packages/ketcher-core/src/domain/serializers/ket/utf8Converter.ts, yarn.lock
Adding utf8 support for text in ket format
=> #1699 utf 8 support for text

packages/ketcher-core/src/application/formatters/formatterFactory.ts
roll back mol v2000 and smiles convertations to ketcher
=> fix: roll back mol v2000 and smiles convertations to ketcher

packages/ketcher-core/src/domain/serializers/mol/molfile.ts, packages/ketcher-react/src/script/ui/data/convert/structconv.js
- fixed nan bug. flags convert was fixed in structconv
- fixed ctabv2000 header. replaced spaces with `0`
=> Ketcher creates invalid molfiles with "NaN"

packages/ketcher-core/src/application/editor/editor.types.ts, packages/ketcher-core/src/application/formatters/serverFormatter.ts, packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-core/src/application/ketcherBuilder.ts, packages/ketcher-core/src/application/render/options.js, packages/ketcher-core/src/application/render/raphaelRender.js, packages/ketcher-core/src/application/render/render.types.ts, packages/ketcher-react/src/script/api.ts, packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/data/schema/options-schema.ts, packages/ketcher-react/src/script/ui/state/server/index.js, packages/ketcher-react/src/script/ui/state/shared.js, packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.ts
implement get settig and setSetting API methods
=> feat: implement get settig and setSetting API methods

packages/ketcher-core/src/domain/serializers/sdf/sdfSerializer.ts
=> #1788 Update format when saving template library to sdf

DEVNOTES.md
Change the order of packages. (ketcher-core should be started before all).
=> Fix DEVNOTES.md. Change the order of packages.

packages/ketcher-react/src/script/ui/action/index.js, packages/ketcher-react/src/script/ui/state/action/index.js, packages/ketcher-react/src/script/ui/state/shared.js, packages/ketcher-react/src/script/ui/state/toolbar/index.js, packages/ketcher-react/src/script/ui/views/toolbars/LeftToolbar/leftToolbarOptions.ts
- To simplify interaction with selection tools we have changed the default selection tool to the rectangle selection tool.
=> #1817 Change the default selection tool to the rectangle selection tool

.github/ISSUE_TEMPLATE/bug_report.md, example/config/webpack.config.js
Removed extra part in page title. Also updated bug_report template
=> #1839 – removed lightweight tag from page title

packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.ts
=> #1795 added `render-coloring: true` to add colors when saving

example/config/webpack.config.js, packages/ketcher-react/src/script/ui/state/index.js
=>   #1843 – added possibility to enable/disable redux-logger

packages/ketcher-standalone/package.json, yarn.lock
Updated indigo version to 1.8.1
=> updated indigo version to 1.8.1

packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
Updated packages version to 2.6.2
=> updated packages version to 2.6.2

packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx, packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx
When select a structure from template window it automatically starts to be added to canvas
=> #1823 Add a template to the clipboard when selected

packages/ketcher-react/src/script/ui/component/structrender.tsx, packages/ketcher-react/src/script/ui/state/templates/index.js, packages/ketcher-react/src/script/ui/utils/index.ts
Improved search performance in template dialog by caching rendering result.
resolves #1915
=> #1915 – improved search performance in template dialog

packages/ketcher-react/src/script/ui/data/schema/sdata-schema.js, packages/ketcher-react/src/script/ui/dialog/toolbox/sdata.jsx, packages/ketcher-react/src/script/ui/state/modal/form.js, packages/ketcher-react/src/script/ui/state/modal/sdata.js
Added custom name & value fields instead dropdowns
=> #1888 Ability to add custom name and values for data sgroup

documentation/help.md
=> #1912: update help.md with updated list of keyboard shortcuts

packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
fix #1936
Added handle if template is null
=> #1936 Adding functional group to atom generate a JavaScript console error

packages/ketcher-react/src/script/editor/tool/bond.ts, packages/ketcher-react/src/script/ui/component/structrender.tsx, packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx, packages/ketcher-react/src/script/ui/dialog/template/useSaltsAndSolvets.ts, packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts, packages/ketcher-react/src/script/ui/utils/index.ts, packages/ketcher-react/src/script/ui/utils/renderStruct.ts
Added prerendering for part of structures to immediately show them to user.
Rendering for structures is done in batches to improve performance and make UI interactive.
=> #1958 Improve performance, when opening Salts and Solvents tab

packages/ketcher-react/src/templates/fg.sdf
=> #1998 Functional Groups: The abbreviation and hovering preview 'Boc' is displayed as 'Bn

packages/ketcher-react/src/script/ui/component/form/input.tsx, packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
Forward ref from TemplateDialog  - trough Input component - to GenericInput, use it to preserve focus on search input when tab changed (rename input.jsx to .tsx, add types)
=> #1963 Custom Templates  when switching between tabs focus is not active on search bar

packages/ketcher-react/src/script/ui/utils/index.ts
=> #2046 Remove excessive warnings in template dialog

packages/ketcher-react/src/script/ui/component/form/input.tsx, packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx
- Fixed "Edit" button not opening the edit template modal from templates table.
- Fixed typing error (QoL for development process)
=> #2040: Template Library: When you select edit any template, the edit window does not appear

packages/ketcher-core/src/domain/serializers/mol/v3000.js
Added parsing "agents" feature for parser of RXN v3000
Fixes #1931
=> #1931 Reagents: An error message appears when opening the file RXN v3000 with reagent

packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-react/src/script/editor/shared/closest.js
=> #2051: S-groups are not interactive when cursor is outside of the hover area

packages/ketcher-react/src/script/editor/tool/bond.ts
=> #1906 drawing bonds in one direction does not change the bond created in the other direction

packages/ketcher-react/src/script/editor/tool/sgroup.ts
=> #1887 Add s-group data for atom or bond without selection

packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json, yarn.lock
=> #2096 – updated indigo version to 1.9.0-rc.4

packages/ketcher-core/src/application/render/restruct/resgroup.js
=> #2109: Console error when adding sGroups to canvas

packages/ketcher-react/src/script/ui/component/form/input.tsx
=> #2108 - Input fields in some modals lose focus when typing

packages/ketcher-core/src/application/editor/actions/rotate.ts, packages/ketcher-react/src/script/ui/action/flips.ts, packages/ketcher-react/src/script/ui/action/tools.js
=> #1889 add ability to flip a part of structure

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/hand.ts
=> #2112: The hand tool is still following the cursor when moving outside the canvas

packages/ketcher-core/src/application/editor/operations/sgroup/SGroupAttr.ts, packages/ketcher-core/src/application/editor/operations/sgroup/sgroupAtom.ts, packages/ketcher-core/src/domain/entities/sgroup.ts, packages/ketcher-core/src/domain/entities/sgroupForest.ts, packages/ketcher-react/src/script/editor/Editor.ts
=> #2091 Using paste tool (or new template tool) - clearing the canvas causes console errors

packages/ketcher-react/src/constants.ts, packages/ketcher-react/src/script/ui/action/index.js, packages/ketcher-react/src/script/ui/state/action/index.js, packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-react/src/script/ui/state/shared.ts, packages/ketcher-react/src/script/ui/utils/settingsManager.ts, packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ToolbarMultiToolItem/ToolbarMultiToolItem.tsx
The last used selection tool is stored in localStorage. (resolves #1818)
=> #1818: Persist user settings

packages/ketcher-react/src/script/editor/tool/template.ts
=> #2086: Dragging a selected s-group sometimes duplicates it

packages/ketcher-core/src/application/editor/actions/template.ts
=> #2134 – Update valency of heteroatoms when adding Functional Groups

packages/ketcher-standalone/package.json, yarn.lock
=> #2132: Migrate to Indigo v1.10.0-rc.1 in-browser module

packages/ketcher-standalone/package.json, yarn.lock
=> #2153: Migrate to Indigo v1.9.0 in-browser module

.github/ISSUE_TEMPLATE/feature_request.md
=> Backmerge: update feature request template

packages/ketcher-react/src/script/editor/tool/template.ts
More like a crutch for now, maybe will be able to come up with a better solution.
=> #2135 - add tmp fix for functional groups handling in template tool

packages/ketcher-react/src/script/ui/views/modal/components/meta/About/About.jsx
=> #2169 Warning in console when About icon clicked

packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-core/src/application/render/restruct/visel.js
=> #2170: Connected contracted functional groups become non-interactive

packages/ketcher-react/src/script/ui/component/form/input.tsx
=> #1963 – Custom Templates: when switching between tabs the focus is not active on the search bar

packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-core/src/application/render/restruct/visel.js
=> Backmerge: #2170: Connected contracted functional groups become non-interactive

packages/ketcher-core/__tests__/domain/serializers/ket/KetSerializer.test.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-core/src/domain/serializers/ket/schema.json, packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts, packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts
=> #2142 s groups get lost when saving as ket file

packages/ketcher-react/src/script/editor/tool/select.ts, packages/ketcher-react/src/script/ui/component/form/form/form.jsx, packages/ketcher-react/src/script/ui/state/editor/index.js, packages/ketcher-react/src/script/ui/state/modal/atoms.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/items/AtomBatchOperations.tsx, packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx, packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Atom/Atom.tsx
=> #2145 – Atom properties is applied to the entire selected structure

packages/ketcher-react/src/script/ui/component/form/Select/Select.tsx
=> #1456 The selected file format in the Save Structure window doesn't match the mockup

packages/ketcher-react/src/script/editor/tool/apoint.ts, packages/ketcher-react/src/script/editor/tool/eraser.ts, packages/ketcher-react/src/script/editor/tool/hand.ts, packages/ketcher-react/src/script/editor/tool/reactionmap.ts, packages/ketcher-react/src/script/editor/tool/reactionplus.ts, packages/ketcher-react/src/script/editor/tool/reactionunmap.ts, packages/ketcher-react/src/script/editor/tool/rgroupatom.ts, packages/ketcher-react/src/script/editor/tool/rgroupfragment.ts, packages/ketcher-react/src/script/editor/tool/rotate.ts, packages/ketcher-react/src/script/editor/tool/sgroup.ts, packages/ketcher-react/src/script/editor/tool/simpleobject.ts
* #2210 – label does not appear when hovering on created S-Group
* Fix label of Data S-Group not showing
---------
closes #2210
=> Backmerge: #2210 – label does not appear when hovering on created S-Group (#2217)

packages/ketcher-core/__tests__/domain/entities/pile.test.ts, packages/ketcher-core/__tests__/domain/serializers/ket/KetSerializer.test.ts, packages/ketcher-core/src/domain/entities/pile.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-core/src/domain/serializers/ket/schema.json, packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts, packages/ketcher-core/src/domain/serializers/ket/toKet/prepare.ts, packages/ketcher-standalone/package.json, yarn.lock
Resolves #2142 
This PR includes two commits.
The first commit is to revert the previous merged [commit ](https://github.com/epam/ketcher/pull/2191)which resolved the issue in another way.
The second commit is implemented as [the proposed solution written in the issue description](https://github.com/epam/ketcher/issues/2142#issue-1562251108).
=> #2142 s groups that combine multiple molecules get lost when saving as ket file

packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> #2228 – There are freezes in application when Chrome DevTools are opened

packages/ketcher-react/src/script/ui/state/modal/atoms.ts
=> #2233 – The sctucture with different atoms is vanished after applying 'Exact change'

packages/ketcher-react/src/script/ui/state/modal/atoms.ts
=> Backmerge: #2233 – The sctucture with different atoms is vanished after applying 'Exact change' (#2236)

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts, packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts, packages/ketcher-react/src/script/ui/utils/index.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> #2215 – When moving mouse cursor over created S-Group pop-up tool tip does not disappear

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts, packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts, packages/ketcher-react/src/script/ui/utils/index.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> Backmerge: #2215 – When moving mouse cursor over created S-Group pop-up tool tip does not disappear (#2240)

packages/ketcher-core/src/application/formatters/formatProperties.ts, packages/ketcher-core/src/application/formatters/formatterFactory.ts, packages/ketcher-core/src/application/formatters/structFormatter.types.ts, packages/ketcher-core/src/utilities/b64toBlob.ts, packages/ketcher-core/src/utilities/index.ts, packages/ketcher-react/src/script/ui/utils/fileOpener.js, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
Closes #2005 
Added exports CDX files like Base64 (`*.b64cdx`) and like binary (`*.cdx`) file formats
=> #2005 Add CDX export to output formats list

packages/ketcher-core/src/application/editor/actions/erase.ts
=> #2238 – Deleting an atom that is bonded to another atom results in deletion of the second atom as well

packages/ketcher-core/src/application/editor/actions/erase.ts
=> Backmerge: #2238 – Deleting an atom that is bonded to another atom results in deletion of the second atom as well (#2251)

packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
=> #2241: Shift+F opens the Template window with previously opened tab

packages/ketcher-react/src/script/ui/dialog/template/TemplateDialog.tsx
=> #2264 - Template menu tab and content differs

packages/ketcher-core/src/application/editor/actions/erase.ts
=> #2266: Atom click on Functional Groups/Salts and Solvents doesn't replace them it forms a scattering of atoms

packages/ketcher-react/src/script/editor/tool/bond.ts
=> #1906{reopen} drawing bonds in one direction does not change the bond created in the other direction

.github/ISSUE_TEMPLATE/bug_report.md
Test case field was added to bug template to avoid creating duplicate test cases.
=> Update bug_report.md - add test case field

packages/ketcher-react/src/script/editor/tool/template.ts
=> #2269 with each addition of fg to fg connected to terminal atoms of structure bond disappears and structure decreases

packages/ketcher-core/src/application/editor/actions/bond.ts, packages/ketcher-react/src/script/editor/tool/bond.ts, packages/ketcher-react/src/script/editor/tool/chain.ts
- Add ability to add bond to a contracted group
- Add ability to add chain to a contracted group
Resolves #2257
=> #2257 - Unable add a bond to a Function Group

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/atom.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenu.tsx, packages/ketcher-react/src/script/ui/views/components/ContextMenu/contextMenu.types.ts
=> #2247 Clicking outside context menu applies currently selected tool

packages/ketcher-core/src/domain/entities/functionalGroup.ts, packages/ketcher-react/src/script/editor/tool/template.ts
=> #2294 After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover

packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> #2316 – Calculate CIP: Hovering over the label R/S displays Indigo system information

packages/ketcher-react/src/script/editor/tool/paste.ts
=> #2329 – Can not open unknown super-atoms

packages/ketcher-react/src/script/editor/tool/paste.ts
closes #2329 
closes #2336 
closes #2337
=> Backmerge: #2329 – Can not open unknown super-atoms (#2331)

documentation/help.md
closes https://github.com/epam/ketcher/issues/2341
=> Backmerge: #2341 - update the help.md page (#2354)

packages/ketcher-core/src/application/render/raphaelRender.js, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/paste.ts, packages/ketcher-react/src/script/editor/tool/template.ts
=> #2325 – When user hovers cursor with any template selected near the border of the canvas scrollbars appear

packages/ketcher-react/src/script/editor/tool/template.ts
=> #2326 Functional Group forms a bond instead of a replacement

packages/ketcher-react/src/script/ui/views/components/StructEditor/SGroupDataRender.tsx
**Ticket**
https://github.com/epam/ketcher/issues/2348
- added check condition
=> #2348 When you hover over a bond with Attached S-group application crashes

packages/ketcher-react/src/script/ui/views/components/StructEditor/SGroupDataRender.tsx
**Ticket**
https://github.com/epam/ketcher/issues/2348
- added check condition
=> Backmerge: #2348 When you hover over a bond with Attached S-group application crashes

packages/ketcher-core/src/domain/constants/elementColor.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/HoverIcon.ts, packages/ketcher-react/src/script/editor/tool/atom.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
=> #2390 – Selected atom is not displayed under cursor during structure loading

packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ActionButton/ActionButton.tsx
=> #2421 Add locators and/or functions for tools sub-menus

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/HoverIcon.ts
=> #2419 – After pressing Calculate CIP, an abbreviation appears under mouse cursor

README.md, packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-core/src/application/render/options.js, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/ExtendedTable.jsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/BoxWithLines.module.less, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/BoxWithLines.tsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenGroup.module.less, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenGroup.tsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenSet.module.less, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenSet.tsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenericGroups.module.less, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenericGroups.tsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/components/ButtonGenSet/ButtonGenSet.module.less, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/components/ButtonGenSet/ButtonGenSet.tsx, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/components/ButtonGenSet/index.ts, packages/ketcher-react/src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/index.ts
=> #2355 Add DisableQueryElements parameter to disable query elements from extended table

packages/ketcher-react/src/constants.ts, packages/ketcher-react/src/script/editor/tool/template.ts, packages/ketcher-react/src/script/ui/action/functionalGroups.ts, packages/ketcher-react/src/script/ui/state/functionalGroups/index.ts, packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts
- changed logic of the mouse down (add async await)
- created getter isModeFunctionalGroup
- created separate method showRemoveAbbreviationPopup to trigger popup
- created constants
Review and add to the q, please
=> #2425 - The 'Cancel' button does not reverse adding Template to expanded and contracted Functional Group 

packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/utils/canvasExtension.ts
=> #2446 – Structures are drawn outside the viewbox, when changing rendering options

packages/ketcher-core/src/application/render/canvasExtension.ts, packages/ketcher-core/src/application/render/index.ts, packages/ketcher-core/src/application/render/raphaelRender.js, packages/ketcher-react/src/script/editor/tool/select.ts, packages/ketcher-react/src/script/editor/utils/canvasExtension.ts
=> #2427 when moving a structure outside of the canvas structure does not move smoothly

packages/ketcher-core/src/application/render/raphaelRender.js, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts, packages/ketcher-react/src/script/editor/tool/paste.ts, packages/ketcher-react/src/script/editor/tool/select.ts, packages/ketcher-react/src/script/ui/component/form/input.tsx
=> Backmerge: #2482 – Ketcher with iFrame loads with scrollbars activated (#2489)

packages/ketcher-react/src/script/editor/tool/template.ts
**Problem**
The problem was connected with incorrect keys for functionalGroup
After we click on undo action or press Ctrl+z functionalGroups and sgroups has different id's in maps. 
You can check it by using ketcher.editor.struct() in console. Previously (version 2.8) id's for sgroup and functionalGroups were the same after undo.
Before clicking undo
After clicking undo
Seems different id's for sgroup and functionalGroup breaks undo() sometimes. 
To solve the problem I took key instead of id inside functionalGroup map
- created findKeyOfRelatedGroupId that delivers correct id for functionalGroup
- created getters struct / functionalGroup and other to not create same constants everytime
- refactored code
Review and add to the q, please
=> #2454 After clicking undo button edit abbreviation popup do not appear

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/application/render/restruct/rebond.ts, packages/ketcher-core/src/application/render/restruct/restruct.ts, packages/ketcher-core/src/application/render/util.ts, packages/ketcher-core/src/domain/entities/atom.ts, packages/ketcher-core/src/domain/entities/bond.ts, packages/ketcher-core/src/domain/entities/functionalGroup.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts, packages/ketcher-react/src/script/editor/tool/select.ts, packages/ketcher-react/src/script/ui/data/schema/struct-schema.js, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> #225 add support for stereo cip values in ket format

packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts
=> #225 – Add support for stereo CIP values in ket format

package-lock.json, packages/ketcher-standalone/package.json
=> #2458 Migrate to Indigo v1.11.0-rc.1 in-browser module

packages/ketcher-core/src/application/editor/actions/atom.ts, packages/ketcher-core/src/domain/entities/atom.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/moleculeToStruct.ts, packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts
=> #1865 Extended SMILES saved from Ketcher might be invalid for RDKit

packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts, packages/ketcher-react/src/script/editor/tool/paste.ts
=> #2502 – It is not possible to scroll to the top of a structure pasted  partially outside a canvas

packages/ketcher-react/src/script/editor/tool/helper/dropAndMerge.ts, packages/ketcher-react/src/script/editor/tool/helper/isAtomOutSideCanvas.ts, packages/ketcher-react/src/script/editor/tool/select.ts
=> #2502 – It is not possible to scroll to the top of a structure pasted partially outside a canvas

packages/ketcher-core/src/domain/entities/atom.ts
=> Hotfix: #2245 Settings: Terminal and Hetero is not selected as default and on option is not working

packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-react/src/script/editor/shared/closest.js
=> Backmerge: #2516 – When create Superatom part of the structure disappears (#2529)

packages/ketcher-core/src/domain/serializers/ket/schema.json
=> #2379 Can't open v3000 mol file with assigned Alias

packages/ketcher-react/src/script/editor/tool/sgroup.ts
Dont contract sgroups
Closes #2530
=> Hotfix: #2530 Tooltip for created Data S-Group not appears after hover on it

packages/ketcher-react/src/script/ui/action/index.js, packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-react/src/script/ui/state/shared.ts, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
Added removal not rendered struct on `save` action.
=> #2113 Hovered structure gets into the saved molecule

packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-react/src/script/ui/state/shared.ts, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
=> Backmerge: #2113 Hovered structure gets into the saved molecule (#2555)

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-react/src/script/ui/data/schema/options-schema.ts
=> Backmerge: #2585 Change behaviour of "Show hydrogen labels" setting so the "on" value works the same way as "terminal and hetero"

packages/ketcher-react/src/script/editor/tool/atom.ts
* Do not show hoverIcon if there's an active selection
=> #2428 - Atom letter is drawn at the cursor after user selects structure/part of structure on the canvas and then click atom on the toolbar

packages/ketcher-react/src/script/ui/component/cliparea/cliparea.module.less
* Fix style priority to hide textarea visually
=> #1835 - Extra textarea is shown, when Ketcher is not full-screen

packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
Closes #2596 
I tested some numbers and chose 1.4 as the factor at last.
Please let me know if you think 1.4 is not very suitable here.
=> #2596 Rotation tool: Use steps for increasing/decreasing the size of the rotation wheel

packages/ketcher-react/src/script/editor/tool/rotate-controller.ts
=> #2597 Rotation tool: fix selection box for expanded s-groups

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> #2127 Change esc behaviour logic for selection tool

packages/ketcher-react/src/script/editor/tool/template.ts, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.module.less, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx
* Add lazy loading for miew-react
* Fix build errors if any
=> #2655 - Add dynamic load for Miew

packages/ketcher-core/src/application/editor/actions/sgroup.ts, packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-core/src/domain/entities/sgroup.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> #2656 – After opening or pasting an unknown superatom onto canvas, it becomes non-interactive

packages/ketcher-core/src/application/editor/actions/sgroup.ts, packages/ketcher-core/src/application/render/restruct/resgroup.js, packages/ketcher-core/src/domain/entities/sgroup.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> Backmerge: #2656 – After opening or pasting an unknown superatom onto canvas, it becomes non-interactive (#2670)

packages/ketcher-core/src/application/render/index.ts, packages/ketcher-core/src/application/render/renderStruct.ts, packages/ketcher-react/src/script/ui/component/structrender.tsx, packages/ketcher-react/src/script/ui/state/saltsAndSolvents/index.ts, packages/ketcher-react/src/script/ui/utils/index.ts
=> #2650 Move renderStruct function from ketcher-react to ketcher-core

packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
=> #2634 – S-Group Polymer label has character limit

packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
=> #2634 – S-Group Polymer label has character limit (#2682)

packages/ketcher-react/src/script/ui/utils/renderStruct.ts
=> #2694 – Improve performance of Templates Modal

packages/ketcher-core/src/application/render/renderStruct.ts
=> Backmerge: #2694 – Improve performance of Templates Modal

packages/ketcher-react/src/script/ui/utils/renderStruct.ts
=> #2719 – Preview images for Functional Groups and Salts and Solvents are less readable

packages/ketcher-core/src/domain/entities/sgroup.ts, packages/ketcher-react/src/script/ui/views/components/StructEditor/InfoPanel.tsx
=> Backmerge: #2374 Tooltip for Multiple group and SRU Polymer appears in upper left area of canvas (#2735)

packages/ketcher-core/src/application/editor/actions/rotate.ts
=> #2599 Rotation tool: label rotation

example/vite.config.js
Closes #2780 
Fix the custom resolver to match win32 separators ( \ )
=> #2780 Add ability to run a project under windows os without using unix subsystems

packages/ketcher-react/src/script/editor/Editor.ts
Closes #2804 
- fixed last cursor position calculation
=> #2804 Selected Atom appears in the left upper corner of canvas

packages/ketcher-react/src/script/editor/Editor.ts
- fixed last cursor position calculation
=> Backmerge: #2804 Selected Atom appears in the left upper corner of canvas

packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx, packages/ketcher-react/src/script/ui/views/modal/components/process/Miew/Miew.tsx, packages/ketcher-react/src/script/ui/views/toolbars/BottomToolbar/BottomToolbar.container.ts, packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/RightToolbar.container.ts, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
=> Backmerge: #2803 – When user moves mouse, there is a constant update in the '3D Viewer' window

packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
=> #2812 – Tooltip for Data S-Group does not appear

packages/ketcher-core/src/application/render/restruct/reatom.ts
=> #2865 – Incorrect display of carbon in attachment points for functional groups

packages/ketcher-core/src/application/render/restruct/reatom.ts
=> #2864 – Incorrect display angle of attachment points for functional groups

packages/ketcher-react/src/script/ui/data/schema/struct-schema.js
=> #2854 - Multiple repeating S-groups: limit on maximum count

.github/CODEOWNERS, .github/auto_assign.yml
=> Codeowners

.github/auto_assign.yml, packages/ketcher-core/src/index.ts
=> Test qa assign

ketcher-autotests/tests/User-Interface/Zoom-Changes/zoom-changes.spec.ts, ketcher-autotests/tests/utils/selectors/testIdSelectors.ts, packages/ketcher-react/src/script/ui/views/Editor.jsx, packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomControls.tsx
added hotkey` ctrl + mouse wheel` for zoom Editor
Closes https://github.com/epam/ketcher/issues/2916
https://github.com/epam/ketcher/assets/50149163/0457ddac-f6f5-4dd9-969c-1c367a244957
=> #2916 allow zoom change via ctrl+scroll

package-lock.json, packages/ketcher-standalone/package.json
=> #2933 – Migrate to Indigo v1.13.0-rc.1 in-browser module

package-lock.json, packages/ketcher-core/src/application/editor/editor.types.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/App/App.tsx, packages/ketcher-react/src/script/ui/state/editor/index.js, packages/ketcher-react/src/script/ui/views/Editor.jsx, packages/ketcher-react/src/script/ui/views/components/StructEditor/StructEditor.jsx
Closes https://github.com/epam/ketcher/issues/2940
Fixed https://github.com/epam/ketcher/issues/2916
=> #2940 – No modal windows are opened during R-Group adding

.github/CODEOWNERS, .github/auto_assign.yml
=> Updated reviewers list

packages/ketcher-react/src/components/StructRender/StructRender.tsx
The implementation itself is taken from previously deleted code.
closes #2966
=> #2966 error message after opening saved png file

packages/ketcher-react/src/components/StructRender/StructRender.tsx
=> Backmerge: #2966 – Error message after opening saved .PNG file

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> updated ketcher version to 2.13.0-rc.2

packages/ketcher-react/src/script/ui/views/Editor.jsx
=> #2985 – Ctrl+Scroll for zooming is not working

packages/ketcher-core/src/application/editor/editor.types.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-react/src/script/ui/state/shared.ts
=> #3006 – The canvas view moves in the direction of the cursor

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> updated ketcher version to v2.13.0-rc.3

.github/CODEOWNERS, ketcher-autotests/playwright.config.ts
=> Removed QA from reviewers and limited amount of failures on CI

.github/auto_assign.yml
=> added QA member to file 'auto_assign'

ketcher-autotests/.eslintignore
- added ignored files to '.eslinignore' file
=> Autotests: #3090 Update '.eslintignore' file

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #3117 – Migrate to Indigo v1.14.0-rc.1 in-browser module

package-lock.json, packages/ketcher-standalone/package.json
=> #3151 - Migrate to Indigo v1.14.0-rc.2 in-browser module

packages/ketcher-react/src/script/editor/tool/template.ts
=> #3133 - Merge preview stops appearing after hovering over a terminal atoms

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher version to 2.14.0-rc.2

ketcher-autotests/tests/User-Interface/Save-Dialog/save-dialog.spec.ts, packages/ketcher-core/src/application/formatters/formatProperties.ts, packages/ketcher-core/src/application/formatters/formatterFactory.ts, packages/ketcher-core/src/application/formatters/structFormatter.types.ts, packages/ketcher-core/src/domain/services/struct/structService.types.ts, packages/ketcher-react/src/script/ui/data/convert/structConverter.ts, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.test.tsx, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/__snapshots__/Save.test.tsx.snap, packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.types.ts, packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
=> #3114 - Add support for exporting to InChiKey file format

packages/ketcher-core/src/domain/entities/sgroup.ts
Closes #3128 
https://github.com/epam/ketcher/assets/16281184/19dd426b-fac0-464e-96af-7a3f971bca47
=> #3128 - When dragging and dropping a Functional Group onto the structure, numerous errors appear in the console

.github/workflows/playwright.yml
=> Autotests: Add self-hosted runner

.github/auto_assign.yml
=> Autotests: Deleted 1 QA from auto assign- list

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher version to v2.13.0-rc.5

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> #3209 – expand the number of ignored keys for abbreviations lookup

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> Backmerge: #3209 – Expand the number of ignored keys for abbreviations lookup

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #3191 – Migrate to Indigo v1.14.0-rc.3 in-browser module

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Backmerge: #3191 – Migrate to Indigo v1.14.0-rc.3 in-browser module

.github/auto_assign.yml
=> Autotests: added 1 QA to 'auto_assign'

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
Updated Ketcher version to 2.15.0-rc.1
=> Updated Ketcher version to 2.15.0-rc.1

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update ketcher version

ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/attachment-point-tool.spec.ts, packages/ketcher-core/src/application/formatters/formatProperties.ts
=> #3248 – Files with the format InChIKey should be saved with the extension ".inchikey"

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useRGroupAttachmentPointEdit.ts
=> #3284 – Application crashes after selecting an attachment point and pressing the right mouse button

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #3275 – Migrate to Indigo v1.14.0-rc.5 in-browser module

packages/ketcher-core/src/application/formatters/formatProperties.ts
=> Backmerge: #3248 – Files with the format InChIKey should be saved with the extension ".inchikey"

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useRGroupAttachmentPointEdit.ts
=> Backmerge: #3284 – Application crashes after selecting an attachment point and pressing the right mouse button

package-lock.json, packages/ketcher-standalone/package.json
=> Backmerge: #3275 – Migrate to Indigo v1.14.0-rc.5 in-browser module

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher version to v2.15.0-rc.2

packages/ketcher-core/src/application/editor/operations/monomer/monomerFactory.ts, packages/ketcher-core/src/application/formatters/types/ket.ts, packages/ketcher-core/src/domain/helpers/monomers.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-core/src/domain/serializers/mol/molfile.ts, packages/ketcher-core/src/domain/serializers/serializers.types.ts, packages/ketcher-polymer-editor-react/src/Editor.tsx, packages/ketcher-polymer-editor-react/src/components/modal/save/Save.tsx, packages/ketcher-polymer-editor-react/src/components/modal/save/saveButton/SaveButton.tsx, packages/ketcher-polymer-editor-react/src/helpers/formats/formatProperties.ts, packages/ketcher-polymer-editor-react/src/helpers/formats/supportedFormatProperties.ts
- added ket macromolecules serializer for monomers and bonds
=> #3231 - Support serializing canvas to KET format for macromolecules on ketcher side

.github/workflows/playwright.yml
=> Autotests: removed unused docker images

packages/ketcher-core/src/domain/serializers/ket/schema.json
Failed tests passed locally 
[Playwright Test Report2.html.zip](https://github.com/epam/ketcher/files/12621077/Playwright.Test.Report2.html.zip)
[Playwright Test Report.html.zip](https://github.com/epam/ketcher/files/12621001/Playwright.Test.Report.html.zip)
=> #3323 - Update schema.json for atom query specific properties

ketcher-autotests/tests/File-Management/Open-And-Save-Files/KET-Files/ket-files-properties.spec.ts, ketcher-autotests/tests/Indigo-Tools/Reaction Auto-mapping tool/reaction-am-tool-veryfing-button.spec.ts, ketcher-autotests/tests/Reagents/RXN-Format/reagents-rxn-format.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts, ketcher-autotests/tests/Templates/S-Groups/s-groups.spec.ts
=> Autotests: Removed unnecessary eslint-disable comments

.github/workflows/ci.yml, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher version to v2.13.0

packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Bond/Bond.tsx
=> #3372 - Update customQuery for bonds using topology

packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-core/src/application/ketcherBuilder.ts, packages/ketcher-core/src/application/utils.ts, packages/ketcher-core/src/index.ts, packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts, packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx, packages/ketcher-react/src/script/ui/state/hotkeys.ts, packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
=>  #3024 – Can't copy/paste structure with Repeat count when the number of bonds/atoms is more than 999

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher version to 2.15.0-rc.3

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #3421 – Migrate to Indigo v1.14.0-rc.6 in-browser module

packages/ketcher-core/src/application/render/restruct/reatom.ts
…nvert incorrectly to custom query
=> #3445 - Atom properties "Substitution count" and "Ring bond count" convert incorrectly to custom query

packages/ketcher-core/src/application/formatters/serverFormatter.ts, packages/ketcher-core/src/application/formatters/smilesFormatter.ts
=> #3462 – Layout should not be called if there are coordinates in Extended SMILES

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> updated ketcher version to v2.16.0-rc.2

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher version to v2.16.0-rc.3

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update ketcher version to v2.15.0-rc.6

.stylelintrc.json, package-lock.json, package.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher version to v2.14.0

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/__snapshots__/Save.test.tsx.snap, packages/ketcher-standalone/package.json
=> Updated ketcher version to v2.15.0

packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
=> [Macro]:  #3489 - Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder

packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx, packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaBuilder.tsx, packages/ketcher-polymer-editor-react/src/components/monomerLibrary/monomerLibraryGroup/MonomerGroup.tsx, packages/ketcher-polymer-editor-react/src/state/rna-builder/rnaBuilderSlice.ts
- fixed presets deletion
- fixed monomer selection
=> Macro:  #3509 - RNA tab view while opening the RNA tab

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer.ts, packages/ketcher-core/src/domain/AttachmentPoint.ts
=> Macro: #3469 – Snake bonds should be displayed from/to attachment point for R1 and R2

.github/workflows/playwright-macromolecules.yml
=> - increased timeout on CI for macromolecules

packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditor.tsx, packages/ketcher-polymer-editor-react/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> Macro: #3538 - New created preset does not draw on canvas 

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/operations/polymerBond/index.ts, packages/ketcher-core/src/application/editor/tools/Bond.ts, packages/ketcher-core/src/application/render/renderers/RenderersManager.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts, packages/ketcher-polymer-editor-react/src/components/modal/monomerConnection/MonomerConnections.tsx
https://github.com/epam/ketcher/assets/70894460/209f33f1-3910-4272-a24b-74baefe91ea5
=> #3582 - AP are shown after closing modal

packages/ketcher-core/src/domain/entities/index.ts, packages/ketcher-polymer-editor-react/src/components/modal/monomerConnection/MonomerConnections.test.tsx, packages/ketcher-react/src/script/editor/tool/bond.ts, packages/ketcher-react/src/script/editor/tool/chain.ts, packages/ketcher-react/src/script/editor/tool/helper/isMacroMolecule.ts
This PR prevents regular (non-macro) editor from forming bonds with macromolecules. Not exactly what the issue asks about, but it was discovered as the easiest way for now.
=> #3604 macro preview window of micro structure shows pieces of macro structures

packages/ketcher-react/src/script/editor/tool/bond.ts, packages/ketcher-react/src/script/editor/tool/chain.ts, packages/ketcher-react/src/script/editor/tool/helper/isMacroMolecule.ts, packages/ketcher-react/src/script/editor/tool/select.ts
=> #3630 - Macro: restrict micro and macro structures merging

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-react/src/Editor.module.less, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbarIconButton.ts, packages/ketcher-standalone/package.json
Includes fix of https://github.com/epam/ketcher/issues/3623
=> Update ketcher version to v2.14.1

ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files.spec.ts, package-lock.json, package.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #3695 – Migrate to Indigo v1.16.0-rc.3 in-browser module

ketcher-autotests/tests/File-Management/Open-And-Save-Files/MOL-Files/mol-files.spec.ts, package-lock.json, package.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Backmerge: #3695 – Migrate to Indigo v1.16.0-rc.3 in-browser module

packages/ketcher-core/src/domain/AttachmentPoint.ts
=>  Macro: #3601 – attachment points aren't disappearing in snake viewed chain of peptides when hovering them multiple times

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- fixed maximum call stack size exception during snake layout for cyclic chains
=> #3718 - Macro: Pressing Snake mode button causes exception

packages/ketcher-core/src/application/editor/operations/monomer/monomerFactory.ts, packages/ketcher-core/src/application/formatters/types/ket.ts, packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts, packages/ketcher-core/src/application/render/renderers/PeptideRenderer.ts, packages/ketcher-core/src/application/render/renderers/PhosphateRenderer.ts, packages/ketcher-core/src/application/render/renderers/RNABaseRenderer.ts, packages/ketcher-core/src/application/render/renderers/SugarRenderer.ts, packages/ketcher-polymer-editor-react/src/theming/defaultTheme/defaultTheme.ts
- added drawing default color for monomers with unknown natural analog
- added 'moddna' type of monomers and drawing it as a chem
=> #3719 - Macro: Unable to load from file: System throws Convert Error! error message

packages/ketcher-core/src/domain/serializers/ket/helpers.ts
closes https://github.com/epam/ketcher/issues/3651
- added comment
=> #3651 - different coordinate systems are used in micro and macro mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> updated Ketcher version to v2.17.0-rc.3

packages/ketcher-polymer-editor-react/src/components/modal/save/Save.tsx
- added save modal closing after pressing save button
=> Macro: #3820 - System doesn't close Save dialog after Save button pressed

.github/auto_assign.yml
=> #4566- changed QA review group members

ketcher-autotests/tests/Macromolecule-editor/Peptides/peptide-monomer-library.spec.ts, packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-polymer-editor-react/src/components/monomerLibrary/MonomerLibrary.tsx
=> Macro: #3853 – cannot erase entered text in the search box in monomer library

packages/ketcher-core/src/application/formatters/formatterFactory.ts, packages/ketcher-react/src/script/ui/state/shared.ts, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
=> Backmerge: #3872 – Add support for all query properties in Mol V2000

packages/ketcher-core/src/domain/AttachmentPoint.ts
closes #3899
- removed strange setTimeout 1
=> #3899 - macro attachment points do not disappear when hover is removed from some monomers

packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #3728 - Add group selection for macromolecules

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-core/src/application/editor/index.ts, packages/ketcher-core/src/utilities/index.ts, packages/ketcher-core/src/utilities/shortcutsUtil.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-react/src/script/ui/action/index.js, packages/ketcher-react/src/script/ui/component/actionmenu.jsx, packages/ketcher-react/src/script/ui/views/toolbars/RightToolbar/AtomsList/AtomsList.tsx, packages/ketcher-react/src/script/ui/views/toolbars/ToolbarGroupItem/ActionButton/ActionButton.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/SystemControls.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/TopToolbar.container.ts
=> #3917 - Macro: Lack of consistency in hotkeys between micro and macro mods and absence of tooltips with information about hotkeys

packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx, packages/ketcher-react/src/script/ui/component/cliparea/clipboardUtils.js
=> #3915 - Pasting does not work in Firefox browser at all

packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx, packages/ketcher-react/src/script/ui/component/cliparea/clipboardUtils.js
=> Backmerge: #3915 - Pasting does not work in Firefox browser at all

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> Macro: #3900 - The last letter in RNA Builder name field cannot be deleted

ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts
=> Autotests: #1234 - fixed 1 test for r-group-fragment

packages/ketcher-core/src/domain/entities/struct.ts
- fixed texts scaling (removed ignoring scaling for texts if there is no reaction in structure)
=> Backmerge: #3961 - Micro: System disorganize molecule and label during loading from ppx file (base64 cdx format)

packages/ketcher-core/src/domain/serializers/ket/toKet/moleculeToKet.ts
=> #4045 System doesn't save selection state for custom query bonds

ketcher-autotests/tests/File-Management/Open-And-Save-Files/Save-File/save-file.spec.ts, ketcher-autotests/tests/User-Interface/Right-Click-Menu/right-click.spec.ts
=> - Fix right click test

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.18.0-rc.5

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 2.18.0-rc.6

package-lock.json, packages/ketcher-standalone/package.json
backmerge of https://github.com/epam/ketcher/pull/4081
=> Backmerge: #4080 Migrate to Indigo v1.18.0-rc.7 in-browser module

example/src/ModeControl/ModeControl.tsx, ketcher-autotests/tests/Structure-Creating-&-Editing/Simple-Objects/action-on-simple-objects.spec.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-macromolecules/src/components/FullscreenButton/FullscreenButton.tsx, packages/ketcher-macromolecules/src/components/contextMenu/RNAContextMenu.test.tsx, packages/ketcher-macromolecules/src/components/contextMenu/RNAContextMenu.tsx, packages/ketcher-macromolecules/src/constants.ts, packages/ketcher-macromolecules/src/helpers/calculatePreviewPosition.ts, packages/ketcher-react/src/constants.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenu.module.less, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomControls.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomInput.tsx
=> #4091 - Zoom menu does not appear if ketcher injected in popup

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 2.18.0-rc.7

example/src/ModeControl/ModeControl.tsx, ketcher-autotests/tests/Structure-Creating-&-Editing/Simple-Objects/action-on-simple-objects.spec.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-macromolecules/src/components/FullscreenButton/FullscreenButton.tsx, packages/ketcher-macromolecules/src/components/contextMenu/RNAContextMenu.test.tsx, packages/ketcher-macromolecules/src/components/contextMenu/RNAContextMenu.tsx, packages/ketcher-macromolecules/src/constants.ts, packages/ketcher-macromolecules/src/helpers/calculatePreviewPosition.ts, packages/ketcher-react/src/constants.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenu.module.less, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomControls.tsx, packages/ketcher-react/src/script/ui/views/toolbars/TopToolbar/ZoomInput.tsx
=> Backmerge: #4091 - Cursor position misalignment after switching in fullscreen after changing ketcher settings

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.19.0-rc.1

ketcher-autotests/README.md
=> Autotests: #4118 - update README file

ketcher-autotests/tests/User-Interface/Hot-Keys/hotkeys.spec.ts, packages/ketcher-react/src/script/editor/tool/template.ts, packages/ketcher-react/src/script/editor/tool/templatePreview.ts, packages/ketcher-react/src/script/ui/state/handleHotkeysOverItem.ts
=> Backmerge: #3918 - When deleting part of a structure using a hotkey Del, and preview of structure is under mouse cursor, an error occurs.

packages/ketcher-core/src/application/render/renderStruct.ts, packages/ketcher-core/src/application/render/restruct/retext.ts
- fixed the order of applying text styles
=> #4088 - System print out subscripted text imperfectly

packages/ketcher-core/src/application/render/renderStruct.ts, packages/ketcher-core/src/application/render/restruct/retext.ts
- fixed the order of applying text styles
=> Backmerge: #4088 - System print out subscripted text imperfectly

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- also updated ketcher to 2.18.0-rc.9
=> #4160 - Migrate to Indigo v1.18.0-rc.9 in-browser module

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher 2.18

packages/ketcher-core/src/domain/services/struct/structService.types.ts, packages/ketcher-macromolecules/src/helpers/formats/supportedFormatProperties.ts
=> Backmerge: #4295 - Cannot save FASTA using the Remote mode

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #4286 - Macro: Editing grid disappears but editing mode is on

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.19.0-rc.3

packages/ketcher-core/src/application/editor/tools/Clear.ts
=> #4356 - Macro: Clear canvas button doesn't work in Sequence mode

packages/ketcher-macromolecules/src/components/modal/UpdateSequenceInRNABuilder/UpdateSequenceInRNABuilder.tsx
=> #4454 - 'Update sequence' modal window: don't close RNA-builder after pressing 'Cancel' in modal window.

ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts, ketcher-autotests/tests/Reagents/CDX-Format/reagents-cdx-format.spec.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- also updated ketcher to 2.21.0-rc.1
=> #4463 - Update indigo to 1.20.0-rc.1

.github/workflows/playwright-macromolecules.yml
timeout rose up to 60 mins
[skip ci]
=> Bump request

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #4369 - Del button works as Backspace button that is wrong

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-macromolecules/src/data/monomers.sdf, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- also updated ketcher to 2.19.0-rc.4
=> #4519 - Macro: Add Pyrro and AspOH peptides to monomer library

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> #4487 - Macro: RNA builder: Cancel button doesn't work

.github/workflows/playwright-macromolecules.yml
Timeout from 60 to 90
[skip ci]
=> Bump request: Update playwright-macromolecules.yml

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
=> #4349 - Macro: Selection does not work in sequence editing with Shift+Up/Down arrow combination

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- updated ketcher to 1.20.0
- updated indigo to 1.19.0
=> Update ketcher to 2.20.0

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/application/render/restruct/rebond.ts, packages/ketcher-core/src/application/render/util.ts
=> #3843 - System doesn't filter out and do execute html tags and javascript in custom query feature text

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/application/render/restruct/rebond.ts, packages/ketcher-core/src/application/render/util.ts
=> Backmerge: #3843 - System doesn't filter out and do execute html tags and javascript in custom query feature text

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Backmerge: #4560 - Migrate to Indigo v1.20.0-rc.2 in-browser module

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #4531 - Allow moving and connecting "small" structures in macro mode

packages/ketcher-macromolecules/src/components/monomerLibrary/MonomerLibrary.tsx
=> #4488 - Macro: RNA Builder: System doesn't allow duplicate same preset twice

ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts
[skip ci]
- deleted 'test.fail()';
- increased 'test.setTimeout(150000)'
=> Bump request: Autotests: #4642 - test-fail-remove-and-increase-timeout

ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts
Revert "- deleted 'test.fail()'; (#4642)"
This reverts commit 183baf273aad68035420b823d2e5ebdb24457b1e.
=> Bump request: Autotests: #4661 - revert-branch

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/modes/BaseMode.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts, packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-core/src/application/render/renderers/sequence/BaseSequenceItemRenderer.ts, packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-macromolecules/src/components/LayoutModeButton/LayoutModeButton.tsx, packages/ketcher-macromolecules/src/components/SequenceTypeButton/SequenceTypeDropdown.tsx, packages/ketcher-macromolecules/src/components/contextMenu/RNAContextMenu.tsx, packages/ketcher-macromolecules/src/components/contextMenu/SequenceItemContextMenu/SequenceItemContextMenu.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/MonomerLibrary.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditor.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.test.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/__snapshots__/RnaEditorExpanded.test.tsx.snap, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/hooks/useDisabledForSequenceMode.test.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/hooks/useDisabledForSequenceMode.ts, packages/ketcher-macromolecules/src/hooks/stateHooks.ts, packages/ketcher-macromolecules/src/state/common/editorSlice.ts
=> #4501 - Macro: The system allows you to paste on canvas while modifying nucleotides in the RNA builder

packages/ketcher-macromolecules/src/Editor.tsx
Removed repeated execution of dispatch
=> #4543 - The cleared object is not returned by the Undo button in the Macromolecules mode.

packages/ketcher-core/src/domain/entities/vec2.ts, packages/ketcher-react/src/script/editor/tool/paste.ts
=> #4590 - RNA Structure is broken while we Copy from Macro and Paste to Micro canvas.

packages/ketcher-core/__tests__/application/render/renderers/PeptideRenderer.test.ts, packages/ketcher-core/__tests__/application/render/renderers/__snapshots__/PeptideRenderer.test.ts.snap, packages/ketcher-core/src/application/editor/internal.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts, packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts, packages/ketcher-core/src/application/render/renderers/ChemRenderer.ts, packages/ketcher-core/src/application/render/renderers/PeptideRenderer.ts, packages/ketcher-core/src/application/render/renderers/PhosphateRenderer.ts, packages/ketcher-core/src/application/render/renderers/RNABaseRenderer.ts, packages/ketcher-core/src/application/render/renderers/SugarRenderer.ts
=> #4692 - Macro: Cursors should be copied from small mode

ketcher-autotests/Dockerfile, ketcher-autotests/package.json, package-lock.json
=> #4704 - New Playwright version 1.44.1

packages/ketcher-core/__tests__/application/render/renderers/__snapshots__/PolymerBondRenderer.test.ts.snap, packages/ketcher-core/src/application/render/renderers/BaseRenderer.ts, packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer.ts, packages/ketcher-core/src/domain/AttachmentPoint.ts
=> #4697 - Macro: Highlight connection point (change mouse cursor) on mouse hover

ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Copy-And-Paste/sequence-mode-copy-paste.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-fasta.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-idt.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-mol.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-sequence.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Sequence-Mode/sequence-mode-import-export.spec.ts, package-lock.json, packages/ketcher-core/src/infrastructure/services/struct/remoteStructService.ts, packages/ketcher-standalone/package.json, packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.types.ts, packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
=> #4311 - Macro: Send monomer library from Ketcher to Indigo upon monomers import/export

ketcher-autotests/tests/Indigo-Tools/Calculate-CIP-Tool/calculate-cip-tool.spec.ts, ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Plus-and-Arrow-tools/plus-and-arrows-tools.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Bond-Tool/all-bonds.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts, ketcher-autotests/tests/Templates/Template-Manipulations/Template-manipulations.spec.ts, ketcher-autotests/tests/User-Interface/Editing-Tools/Copy-Cut-Paste/copy-cut-paste.spec.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #4731 – update ketcher packages and indigo dependency versions

packages/ketcher-core/src/application/editor/modes/BaseMode.ts
- removed error on ketcher side if format was not detected
=> #4739 - Pasting IDT structures via clipboard does not work

packages/ketcher-core/src/application/editor/modes/BaseMode.ts
- removed error on ketcher side if format was not detected
=> Backmerge: #4739 - Pasting IDT structures via clipboard does not work

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #4708 – Forbid merging cyclic sequences on delete in Sequence mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher version to 2.22.0-rc.3

packages/ketcher-core/src/domain/entities/monomer-chains/Chain.ts, packages/ketcher-core/src/domain/helpers/monomers.ts
- fixed case with infinite loop in chains analysis if phosphate is first in cycled chain
=> #4824 - Cycled chain breaks sequence canvas and entire app

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 2.22.0-rc.4

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/domain/serializers/ket/fromKet/polymerBondToDrawingEntity.ts, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #4839 - System loses connections to molecule R2 if there is no R1 attachment point

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useAddAttachmentPoint.ts
Fixed the logic for finding the last minimum number for the attachment point
=> #4784 - Attachment point enumeration logic works wrong

packages/ketcher-react/src/script/editor/tool/apoint.ts, packages/ketcher-react/src/script/editor/tool/charge.ts, packages/ketcher-react/src/script/editor/tool/rgroupatom.ts, packages/ketcher-react/src/script/editor/tool/rgroupfragment.ts, packages/ketcher-react/src/script/editor/tool/sgroup.ts
=> #4773 - It is impossible to apply R-group to atom with attachment point attached

ketcher-autotests/tests/Structure-Creating-&-Editing/Bond-Tool/all-bonds.spec.ts, ketcher-autotests/tests/Templates/Template-Manipulations/Template-manipulations.spec.ts
=> Autotests: #4867 - Take care of unstable tests (Bond tool: Manipulations with bondToolKey)

ketcher-autotests/tests/Indigo-Tools/Calculate-CIP-Tool/calculate-cip-tool.spec.ts, ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Plus-and-Arrow-tools/plus-and-arrows-tools.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Bond-Tool/all-bonds.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts, ketcher-autotests/tests/Templates/Template-Manipulations/Template-manipulations.spec.ts, ketcher-autotests/tests/User-Interface/Editing-Tools/Copy-Cut-Paste/copy-cut-paste.spec.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #4871 - Update ketcher packages and indigo dependency versions

packages/ketcher-core/src/domain/entities/functionalGroup.ts, packages/ketcher-react/src/script/editor/tool/atom.ts
added a check for the functional group
=> #4925 - Unable to change atom to another if molecule has attachment point

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update ketcher to v2.22.0-rc.9

packages/ketcher-core/src/application/editor/data/monomers.ket, packages/ketcher-core/src/application/render/renderers/UnsplitNucleotideRenderer.ts
- fixed nucleotides definition in library
- fixed unsplit nucleotides label styles
=> #4920 - Preview: Unable to load IDT codes for unsplit monomers we have in the library

packages/ketcher-core/src/domain/helpers/monomers.ts
- fixed check of chain beginning
=> #4934 - Preview: Enumeration counters remain unchanged after bond being deleted

packages/ketcher-core/src/application/render/restruct/reatom.ts
=> #4660 - Zero charge shows explicit 0 instead of blank after using A+/A- Tools

packages/ketcher-react/src/script/editor/tool/atom.ts, packages/ketcher-react/src/script/editor/tool/helper/getGroupIdsFromItems.ts
=> Backmerge: #4927 - Able to change attachment point label to an atom if it is selected first

packages/ketcher-core/src/application/render/restruct/reatom.ts
=> Backmerge: #4660 - Zero charge shows explicit 0 instead of blank after using A+/A- Tools

packages/ketcher-core/src/application/formatters/types/ket.ts, packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/monomerToDrawingEntity.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-react/src/script/editor/utils/functionalGroupsTooltip.ts
=> Backmerge: #4950 - Preview: Switching to Molecules mode causes crash if unknown monomer is on the canvas

packages/ketcher-core/src/application/editor/data/monomers.ket, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
- added classHELM: RNA for unsplit nucleotides
=> #5030 - Preview: Unable to save mix of unresolved nucleotides and nucleotides to Sequence (and FASTA)

packages/ketcher-core/src/application/editor/data/monomers.ket, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx
=> Backmerge: #5030 - Preview: Unable to save mix of unresolved nucleotides and nucleotides to Sequence (and FASTA)

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- also updated ketcher to 2.23.0-rc.2
=> #5050 - Update indigo to 1.22.0-rc.2 in browser module

package-lock.json, packages/ketcher-standalone/package.json
=> Backmerge: #5050 - Update indigo to 1.22.0-rc.2 in browser module

packages/ketcher-core/src/domain/entities/monomer-chains/ChainsCollection.ts
=> - removed console log

packages/ketcher-macromolecules/src/components/LayoutModeButton/LayoutModeButton.tsx, packages/ketcher-macromolecules/src/components/menu/subMenu/styles.ts
=> #4108 – Macro: There are no tooltips when hovering over each of the sequence modes

packages/ketcher-core/src/application/editor/operations/rasterImage/rasterImageMove.ts, packages/ketcher-core/src/application/editor/operations/rasterImage/rasterImageResize.ts, packages/ketcher-core/src/application/editor/operations/rasterImage/rasterImageUpsertDelete.ts, packages/ketcher-core/src/application/render/restruct/generalEnumTypes.ts, packages/ketcher-core/src/application/render/restruct/rerasterImage.ts, packages/ketcher-core/src/application/render/restruct/restruct.ts, packages/ketcher-core/src/domain/serializers/ket/schema.json, packages/ketcher-react/src/script/editor/tool/rasterImage.ts
=> Images lowest render z

ketcher-autotests/tests/Macromolecule-editor/Snake-Mode/side-chain-connections.spec.ts, ketcher-autotests/tests/utils/canvas/tools/helpers.ts, ketcher-autotests/tests/utils/common/helpers.ts
=> #5150 - Turn some tests to clear canvas way instead of page reload

packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts
=> #5023-Spliting molecule on pieces with attachment points of each cause crash when switching to Macro mode

ketcher-autotests/tests/test-data/KET/sequence-with-unresolved-idt-monomers-expected.ket, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-macromolecules/src/components/shared/Preview/index.tsx, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- also updated ketcher to 2.24.0-rc.1
=> #5221 - Update indigo to 1.23.0-rc.1 in browser module

packages/ketcher-macromolecules/src/helpers/rnaValidations.ts
=> #5196 - Preview: An error appears in the Console when opening any section in the RNA tab

packages/ketcher-macromolecules/src/helpers/rnaValidations.ts
=> Backmerge: #5196 - Preview: An error appears in the Console when opening any section in the RNA tab

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.test.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> #5255 – Fix adding new monomers to canvas in sequence mode while editing RNA in builder

ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-idt.spec.ts, packages/ketcher-core/src/application/editor/tools/Bond.ts, packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts
=> Backmerge: #5184 – Fix unresolved monomers bond establishing issue

packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx
=> #5121 - copy does not work in the firefox browser

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.23.0-rc.4

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> #5301 – New preset creation process interferes with monomer replacement on the sequence mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump version to 2.24.0-rc.3

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> Backmerge: #5300 – Attempt to insert improper monomer from the library to the sequence causes wrong error (#5303)

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaEditor/RnaEditorExpanded/RnaEditorExpanded.tsx
=> Backmerge: #5301 – New preset creation process interferes with monomer replacement on the sequence mode (#5304)

packages/ketcher-core/src/application/editor/data/monomers.ket
Issue => https://github.com/epam/ketcher/issues/5244
Changed P-quinonoid fluorescein to P-quinoid fluorescein
=> #5244-Add CHEMs to the library

ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-fasta.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-idt.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-ket.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-mol.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/import-saving-sequence.spec.ts, ketcher-autotests/tests/utils/common/loaders/waitForLoad/waitForLoad.ts, ketcher-autotests/tests/utils/files/readFile.ts
=> Autotest: #5377 - Flacky tests corrections

packages/ketcher-core/src/application/editor/data/monomers.ket
Issue => https://github.com/epam/ketcher/issues/5264
Fixed leaving group at the N-Methyl-Proline to R2
=> #5264-Add amino acids to the library

ketcher-autotests/tests/Indigo-Tools/Calculate-CIP-Tool/calculate-cip-tool.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts, ketcher-autotests/tests/utils/canvas/helpers.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump 2.22 release version to public

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/editor/operations/monomer/monomerFactory.ts, packages/ketcher-core/src/application/editor/tools/Monomer.ts, packages/ketcher-core/src/application/render/renderers/AmbiguousMonomerRenderer.ts, packages/ketcher-core/src/application/render/renderers/RenderersManager.ts, packages/ketcher-core/src/application/render/renderers/sequence/RNASequenceItemRenderer.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts, packages/ketcher-core/src/domain/entities/Nucleoside.ts, packages/ketcher-core/src/domain/entities/Nucleotide.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/monomerToDrawingEntity.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaBuilder/RnaAccordion/RnaAccordion.tsx, packages/ketcher-macromolecules/src/helpers/getPreset.ts, packages/ketcher-macromolecules/src/state/rna-builder/rnaBuilderSlice.helper.ts, packages/ketcher-macromolecules/src/state/rna-builder/rnaBuilderSlice.ts
- fixed ambiguous monomers in molecules mode
- fixed rna builder for ambiguous monomers
- fixed sequence mode for ambiguous monomers
=> #4557 - Support of ambiguous monomers in small molecules mode

ketcher-autotests/tests/Macromolecule-editor/Import-Saving-Files/saving-svg.spec.ts
This pull request refines and optimizes the test suite for  SVG files saving by clearing the canvas after each test in accordance with [this task](https://github.com/epam/ketcher/issues/5416).
Since some tests involve checking the contents of generated files, a page reload has been added for them.
The modifications have resulted in a reduction in the maximum execution time on a single worker — down to approximately 51 seconds (on my PC) from the previous ~85 seconds using the older page reload method. For tests where it is still necessary to reload the page, clear comments have been added to explain the rationale.
=> #5416 - Refactor SVG files save tests for sequential execution with canvas clearing

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #5420 – Update indigo to 1.24.0-rc.1 in browser module

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump 2.23 release version to public

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump 2.24 release version to public

packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts
=> #5466 - HELM inline SMILES monomer canvas color is wrong

packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
=> #5470 - Export of diffrent mixed and alternatives peptides (with diffrent proportions and percents) works wrong

packages/ketcher-core/src/domain/entities/fixedPrecision.ts, packages/ketcher-core/src/domain/entities/multitailArrow.ts
=> #5447 - Added fixed precision class, updated multitail calculations with fixed precision usage

packages/ketcher-react/src/script/ui/component/form/Input/Input.tsx, packages/ketcher-react/src/script/ui/component/form/MeasureInput/measure-input.jsx, packages/ketcher-react/src/script/ui/data/schema/options-schema.ts
=> #5175 - allow entering values in settings with the precision of one decimal place

packages/ketcher-core/src/application/render/renderers/BaseMonomerRenderer.ts
=> Backmerge: #5466 - HELM inline SMILES monomer canvas color is wrong

packages/ketcher-core/src/domain/entities/fixedPrecision.ts, packages/ketcher-core/src/domain/entities/multitailArrow.ts
=> #5447 - Added fixed precision class, updated multitail calculations with fixed precision usage 

README.md
=> Missing "s" typo in set.Settings

packages/ketcher-macromolecules/src/EditorEvents.tsx
=> #5368 - An error appears in the Console, when dragging a bond between any monomers

packages/ketcher-macromolecules/src/EditorEvents.tsx
=> Backmerge: #5368 - An error appears in the Console, when dragging a bond between any monomers

packages/ketcher-core/src/application/render/draw.ts
=> #4983 - Settings for the "attachment point tool" don't update with changed pixel settings

packages/ketcher-core/src/domain/entities/AmbiguousMonomer.ts
=> #5519 - Alias labels for mixed bases loaded from IDT are wrong

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useChangeBondDirection.ts
=> #5536 - White screen is displayed after change direction of wedge bond

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.25.0-rc.4

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #5560 – Update Indigo to 1.24.0-rc.4 in browser module

packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts
- fixed monomer to atom bonds repositioning issue after switching between modes if there are more than one molecule
=> #5359 - Display molecules in macro mode: basic structures with atoms and bonds

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 2.26.0-rc.1

packages/ketcher-react/src/components/ToggleButtonGroup/ToggleButtonGroup.tsx
=> #5615 - Overlapping UI elements in Query Properties right-click menu

packages/ketcher-core/src/application/editor/Editor.ts
=> #4394 - In the Sequence mode, the tooltip “Start new sequence” is shown outside of the canvas

packages/ketcher-core/src/application/editor/Editor.ts
=> Backmerge: #4394 - In the Sequence mode, the tooltip “Start new sequence” is shown outside of the canvas

ketcher-autotests/tests/utils/clicks/index.ts, packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-macromolecules/src/components/modal/monomerConnection/MonomerConnections.tsx
=> Backmerge: #5205 - Edit Connection points dialog can cause invalid connection between monomers

packages/ketcher-core/src/application/editor/operations/coreAtom/atom.ts, packages/ketcher-core/src/application/editor/operations/coreBond/bond.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #5657 - Clear canvas doesn't work for micro structures on macro mode

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/FlexModePolymerBondRenderer.ts
=> #5679 - Unable to establish connection between micro structure and macro ones

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
=> #5401 - Side-chain connections are not displayed in Snake mode

packages/ketcher-core/src/application/editor/operations/coreAtom/atom.ts, packages/ketcher-core/src/application/editor/operations/coreBond/bond.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> Backmerge: #5657 - Clear canvas doesn't work for micro structures on macro mode

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/FlexModePolymerBondRenderer.ts
=> Backmerge: #5679 - Unable to establish connection between micro structure and macro ones

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useMonomerExpansionHandlers.ts
=> #5662 – Fix inability to select Erase tool after monomer expansion

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
=> Backmerge: #5401 - Side-chain connections are not displayed in Snake mode

packages/ketcher-react/src/script/editor/tool/eraser.ts
=> #5665 – Show remove abbreviation dialog when trying to erase expanded monomer

packages/ketcher-react/src/script/editor/tool/image.ts
=> Backmerge: #5413 - Can't add specific SVG image to Canvas in Mozilla Firefox

ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/SelectionMenuItems.tsx
=> #5758 Highlight only bonds when selected bonds + atoms

packages/ketcher-core/src/application/editor/actions/fragment.ts, packages/ketcher-core/src/application/editor/actions/utils.ts, packages/ketcher-react/src/script/editor/tool/enhanced-stereo.ts, packages/ketcher-react/src/script/ui/state/hotkeys.test.tsx
=> #4936 - Applying Enhanced Stereochemistry to monomers causes its disappear from the canvas (and exception in console)

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useBondSGroupAttach.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useBondSGroupEdit.ts
=> #4941 - System shows Edit S-Group option for every bond of molecule if it has attachment point

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/editor.types.ts, packages/ketcher-core/src/application/ketcher.ts
=> add getket same logic as saving data

packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useMonomerExpansionHandlers.ts
=> Backmerge: #5662 – Fix inability to select Erase tool after monomer expansion

packages/ketcher-core/src/application/render/renderers/BondRenderer.ts, packages/ketcher-core/src/application/render/renderers/MonomerToAtomBondRenderer.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> Backmerge: #5686 - Bonds between micro and macro structures couldn't be selected and deleted in Macro mode

packages/ketcher-core/src/application/render/renderers/sequence/ChemSequenceItemRenderer.ts
=> #5673 - Micro structures connected to polymer chains are not shown on Sequence mode canvas

packages/ketcher-core/src/application/render/renderers/sequence/ChemSequenceItemRenderer.ts
=> Backmerge: #5673 - Micro structures connected to polymer chains are not shown on Sequence mode canvas

packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-react/src/script/ui/component/view/savebutton.tsx, packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.jsx
=> Backmerge: #5612 - The file size is the same when saved to png

packages/ketcher-core/src/domain/entities/Phosphate.ts, packages/ketcher-core/src/domain/entities/Sugar.ts, packages/ketcher-core/src/domain/entities/UnresolvedMonomer.ts
=> #5848 - Unable to establish connection between micro structure and sugar or phopshate (and partially - unresolved monomer)

packages/ketcher-core/src/application/render/restruct/restruct.ts, packages/ketcher-core/src/domain/entities/atom.ts, packages/ketcher-core/src/domain/entities/bond.ts, packages/ketcher-core/src/domain/entities/struct.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/helper/locate.ts
=> #5699 – Fix collapsed monomers and their bonds bulk selection, removal and undoing in micro mode

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/application/render/restruct/rebond.ts
=> #5685 - The diagonal bond in the molecule is displayed incorrect with ACS style

packages/ketcher-core/src/application/render/restruct/restruct.ts, packages/ketcher-core/src/domain/entities/atom.ts, packages/ketcher-core/src/domain/entities/bond.ts, packages/ketcher-core/src/domain/entities/struct.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/editor/tool/helper/locate.ts
=> Backmerge: #5699 – Fix collapsed monomers and their bonds bulk selection, removal and undoing in micro mode

ketcher-autotests/tests/utils/macromolecules/index.ts, packages/ketcher-core/__tests__/domain/entities/drawingEntitiesManager.test.ts, packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-core/src/application/editor/index.ts, packages/ketcher-core/src/application/editor/modes/BaseMode.ts, packages/ketcher-core/src/application/editor/shared/utils.ts, packages/ketcher-core/src/application/editor/tools/Zoom.ts, packages/ketcher-core/src/application/editor/tools/index.ts, packages/ketcher-core/src/application/editor/tools/types.ts, packages/ketcher-core/src/application/render/renderers/RenderersManager.ts, packages/ketcher-core/src/application/render/renderers/types.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts, packages/ketcher-macromolecules/src/components/modal/Open/Open.tsx
=> #5600 - Zoom in automatically upon import of small sequences

packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.utils.ts
=> #5809 – Open correct context menu for expanded monomer while clicking on bond or atom

example/package.json, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> 5900 - Increase Ketcher version

ketcher-autotests/tests/Indigo-Tools/Reaction Auto-mapping tool/reaction-am-tool-veryfing-button.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/functional-groups.spec.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #5898 – Update indigo to 1.26.0-rc.1 in browser module

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.26.0-rc.8

packages/ketcher-core/src/application/ketcher.ts
=> #5515: Add ketcher-calculate-api

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> - updated ketcher version to 2.28.0-dev.1

packages/ketcher-core/src/application/editor/modes/BaseMode.ts
In this PR, conditions are added to the `onCopy` method of the `BaseMode` class to handle copying of microstructures
=> #5931 – Copy/Cut-Paste functionality not working for microstructures in Macro mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 2.26.0

packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.types.ts, packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
=> #5972 - Export to three letter amino acid codes cause convert error

packages/ketcher-standalone/src/infrastructure/services/struct/indigoWorker.types.ts, packages/ketcher-standalone/src/infrastructure/services/struct/standaloneStructService.ts
=> Backmerge: #5972 - Export to three letter amino acid codes cause convert error

example/src/App.tsx, packages/ketcher-react/src/script/ui/App/App.tsx
=> #3813 - Page auto jump to top when ketcher editor inited

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/modes/types.ts, packages/ketcher-macromolecules/src/components/LayoutModeButton/LayoutModeButton.tsx, packages/ketcher-macromolecules/src/hooks/stateHooks.ts
=> #6029 - Enter flex mode when macromolecules mode was not entered in before and there is a drawing on canvas

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
=> #5970 - Unable to connect monomer to molecule in snake mode

packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer/SnakeModePolymerBondRenderer.ts
=> Backmerge: #5970 - Unable to connect monomer to molecule in snake mode

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/helpers.ts
Refactored to move class methods that do not use the this context into a separate helpers.ts file.
=> #6029 - Enter flex mode when macromolecules mode was not entered in before and there is a drawing on canvas - refactoring

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- fixed creation of antisense for partial selection by several pieces in one chain
=> #6096 - Antisense creation works wrong in case of partial selection

packages/ketcher-react/src/components/MonomerPreview/calculatePreviewPosition.ts
=> #6127 - Hover mouse over ambiguous monomer on Micromolecules canvas causes app crash

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/application/editor/modes/FlexMode.ts, packages/ketcher-core/src/domain/entities/Command.ts, packages/ketcher-macromolecules/package.json, packages/ketcher-macromolecules/src/components/modal/Open/Open.tsx, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #6129 - Undo operation creates unremovable bonds on the canvas (clear canvas doesn't help)

packages/ketcher-core/src/application/editor/EditorHistory.ts, packages/ketcher-core/src/application/editor/operations/coreAtom/atom.ts, packages/ketcher-core/src/application/editor/operations/coreBond/bond.ts, packages/ketcher-core/src/application/editor/operations/drawingEntity/index.ts, packages/ketcher-core/src/application/render/renderers/RenderersManager.ts, packages/ketcher-core/src/domain/entities/Command.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
- reworked bonds/atoms deletion logic
- moved post execution logic from renderer to command
=> #5949 - Delete of micromolecules bonds works wrong (or doesn't work)

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #5032 - Selection of monomers should disappear when the user moves the cursor

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/application/editor/modes/FlexMode.ts, packages/ketcher-core/src/domain/entities/Command.ts, packages/ketcher-macromolecules/package.json, packages/ketcher-macromolecules/src/components/modal/Open/Open.tsx, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Backmerge: #6129 - Undo operation creates unremovable bonds on the canvas (clear canvas doesn't help)

packages/ketcher-core/src/application/editor/operations/sgroup/sgroupAttachmentPoints.ts
=> #5795 - Undo operation doesn't work for monomer at micro mode if it was deleted - system throws exception in console

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
Uploading Запись экрана 2024-12-17 в 15.03.34.mov…
=> 5663 Movement of microstructures on Sequence mode doesn't work

packages/ketcher-core/src/domain/AttachmentPoint.ts
=> #6022 Side chain attachment point shown in wrong place in Snake mode

ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDXML-Files/cdxml-files.spec.ts, ketcher-autotests/tests/File-Management/Open-And-Save-Files/Image-files/image-files.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Clear-Tool/clear-tool.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Hotkeys/hotkeys.spec.ts, ketcher-autotests/tests/Macromolecule-editor/RNA-Builder/rna-library.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/R-group-tool/r-group-fragment-tool.spec.ts, ketcher-autotests/tests/User-Interface/Clear-Canvas/clear-canvas.spec.ts
=> Changing method

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #6216 – Update indigo to 1.27.0-rc.2 in browser module

ketcher-autotests/tests/File-Management/Open-And-Save-Files/Image-files/image-files.spec.ts, ketcher-autotests/tests/Indigo-Tools/Clean-Tools/clean-tools.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Plus-and-Arrow-tools/plus-and-arrows-tools.spec.ts, ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/attachment-point-tool.spec.ts, ketcher-autotests/tests/Templates/Functional-Groups/Functional-Group-Tools/functional-group-tools.spec.ts, ketcher-autotests/tests/Templates/User-Templates/user-templates.spec.ts, ketcher-autotests/tests/utils/canvas/helpers.ts
=> Autotests: #6047 - autotests replace clean up operations with valid helper functions

ketcher-autotests/tests/File-Management/Open-And-Save-Files/CDX-Files/cdx-files.spec.ts, ketcher-autotests/tests/File-Management/Open-And-Save-Files/Image-files/image-files.spec.ts, ketcher-autotests/tests/File-Management/Open-And-Save-Files/KET-Files/ket-files-properties.spec.ts, ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens-With-Respect-To-Selected-Atoms/toggle-explicit-hydrogens-with-respect-to-selected-atoms.spec.ts, ketcher-autotests/tests/Indigo-Tools/Toggle-Explicit-Hydrogens/toggle-explicit-hydrogens.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts, ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts, ketcher-autotests/tests/Reagents/CDX-Format/reagents-cdx-format.spec.ts, ketcher-autotests/tests/User-Interface/Toolbar/toolbar-ui.spec.ts, ketcher-autotests/tests/utils/canvas/tools/helpers.ts
=> fixes, function renamed

packages/ketcher-macromolecules/src/components/modal/save/Save.tsx, packages/ketcher-macromolecules/src/helpers/formats/formatProperties.ts
=> #6240 – Export to 3-letter sequence doesn't work

packages/ketcher-macromolecules/src/components/modal/save/Save.tsx, packages/ketcher-macromolecules/src/helpers/formats/formatProperties.ts
=> Backmerge: #6240 – Export to 3-letter sequence doesn't work

ketcher-autotests/tests/Reactions/Reaction-tools/Multi-Tailed-Arrow-Tool/multi-tailed-arrow-tool.spec.ts, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to public 2.27.0

packages/ketcher-core/src/application/editor/Editor.ts
=> 6108-system-allow-to-select-monomers-behind-opened-context-menu

ketcher-autotests/README.md, ketcher-autotests/docker-compose.yml
=> Use separate build folder to run docker tests

packages/ketcher-react/src/Editor.tsx
=> #6034 – Remove unnecessary transition

.github/ISSUE_TEMPLATE/bug_report.md
=> Bump update bug_report.md

ketcher-autotests/tests/User-Interface/Clear-Canvas/clear-canvas.spec.ts
Fix autotest Clear Canvas, remove comments.
Fix #6164.
=> 6164-changing-any-parameter-at-settings-cause-undoredo-work-wrong-or-delete-undo-history

.github/workflows/playwright-macromolecules.yml, .github/workflows/playwright.yml, .github/workflows/run-tests.yml
=> #6303 – Update GitHub actions version to v4

packages/ketcher-core/src/application/editor/actions/chain.ts, packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-react/src/script/editor/tool/chain.ts
=> #6222 - New chain tool behaviour

ketcher-autotests/tests/Macromolecule-editor/Clear-Tool/clear-tool.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Erase-Tool/erase-tool.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Rectangle-Selection-Tool/rectangle-selection-tool.spec.ts, ketcher-autotests/tests/Macromolecule-editor/Undo-Redo/undo-redo.spec.ts
=> Autotests: #6267 - Undo/Redo operations have been replaced with the valid helper functions.

README.md, packages/ketcher-react/README.md
=> #6034 – Update docs for opting out of macromolecules mode

example/package.json, example/vite.config.js, package-lock.json
- added additional fix for dev build
=> Backmerge: #3627 - Ketcher requires unsafe-eval in order to run, which contradicts content security policy best practises

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update version to 3.0.0-rc.3

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/application/ketcher.ts, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-react/src/Editor.tsx, packages/ketcher-standalone/package.json
=> #6370 - Inconsistent zoom behavior when inserting a molecule via setMolecule and Paste from Clipboard/Open from File

packages/ketcher-react/src/Editor.tsx
=> #6379 - Ketcher does not respond if switch to macromolecules, close popup with ketcher and open again

packages/ketcher-react/src/Editor.tsx
- clear isPolymerEditorTurnedOn on Editor destroy
=> Backmerge: #6379 - Ketcher does not respond if switch to macromolecules, close popup with ketcher and open again

packages/ketcher-core/src/domain/constants/monomers.ts, packages/ketcher-core/src/domain/helpers/rna.ts
Issue => https://github.com/epam/ketcher/issues/6196
https://github.com/user-attachments/assets/759d86bb-798f-4a00-ac90-eacf611e3974
=> #6196-Ambiguous DNA bases (N, D, H, W) wrongly converted to DNA bases on antisense creation

.github/workflows/run-tests.yml, ketcher-autotests/tests/utils/canvas/helpers.ts, packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-core/src/application/editor/tools/Zoom.ts
=> Autotests: #6390 - Hide scrollbars on demand in Macromolecules editor (Ctrl+B)

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> #6411 – Ketcher structure copy-paste in KET instead of MOL

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> Backmerge: #6411 – Ketcher structure copy-paste in KET instead of MOL

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/render/renderers/sequence/SequenceRenderer.ts
=> #6272 - Cursor position after adding preset in sequence mode causes an incorrect sequence formation

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump version to 3.1.0-rc.2

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher to v3.0.0-rc.8

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6446 - System shouldn't merge two antisense chains if separator monomer got deleted

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #6446 - System shouldn't merge two antisense chains if separator monomer got deleted

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/domain/entities/BackBoneSequenceNode.ts, packages/ketcher-core/src/domain/entities/EmptySequenceNode.ts
Closes:
#6462 - Adding peptide between RNA and - symbol breaks sense/antisense chain
#6460 - Troubles with switching to Edit mode if - symbol present in sequence
=> #6462 - Adding peptide between RNA and - symbol breaks sense/antisense chain

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6471 - Removing peptide from sense/antisence chain cause unnessussary phosphate removal

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/domain/entities/BackBoneSequenceNode.ts, packages/ketcher-core/src/domain/entities/EmptySequenceNode.ts
Closes:
#6462 - Adding peptide between RNA and - symbol breaks sense/antisense chain
#6460 - Troubles with switching to Edit mode if - symbol present in sequence
=> Backmerge: #6462 - Adding peptide between RNA and - symbol breaks sense/antisense chain

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 3.1.0-rc.3

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6493 - Undo of deleted bond on sequence mode causes "ghost" monomer appearence on the canvas

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 3.1.0-rc.4

.github/workflows/playwright-macromolecules.yml, .github/workflows/playwright.yml, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 2.28.0

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #6534 - Adding nucleotide to the last position having phosphate in antisense causes exception: ReferenceError: process is not defined

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/utils.ts, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Backmerge: #6546 - Macro structure duplicated on canvas when using ketcher.getMolfile() and pasting

packages/ketcher-react/src/script/editor/tool/rotate.ts
=> #6556 - Expanded macromolecules in Micro Mode causes unintended merging

packages/ketcher-react/src/script/editor/tool/rotate.ts
=> Backmerge [3.1]: #6556 - Expanded macromolecules in Micro Mode causes unintended merging

packages/ketcher-react/src/script/editor/tool/rotate.ts
=> Backmerge: #6556 - Expanded macromolecules in Micro Mode causes unintended merging

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 3.0.3

packages/ketcher-macromolecules/src/theming/globalStyles/getGlobalStyles.ts
=> #6561 - Switching to macromolecules changes CSS in the page

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #6628 - Add export of ketcher-standalone esm module as cjs

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-macromolecules/src/Editor.tsx
=> #6627 – Fix invisible snapping drawings after switching to micro mode

packages/ketcher-core/src/application/render/renderers/TransientView/TransientDrawingView.ts
=> #6621 – Fix monomer snapping wiping monomer labels

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-macromolecules/src/Editor.tsx
=> Backmerge: #6627 – Fix invisible snapping drawings after switching to micro mode

packages/ketcher-standalone/package.json
=> Backmerge: #6628 - Add export of ketcher-standalone esm module as cjs

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6624 - Enter key in single-strand edit mode incorrectly breaks both chains instead of only one

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #6624 - Enter key in single-strand edit mode incorrectly breaks both chains instead of only one 

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/render/renderers/sequence/BaseSequenceItemRenderer.ts, packages/ketcher-macromolecules/src/EditorEvents.tsx, packages/ketcher-macromolecules/src/components/SequenceSyncEditModeButton/SequenceSyncEditModeButton.tsx
=> #6632 - New sequence appears gray after clearing the canvas in non-sync mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json, packages/ketcher-standalone/rollup.config.js, packages/ketcher-standalone/src/emptyIndex.js
=> #6661 - Adjust ketcher-standalone entrypoints to work for all builders

packages/ketcher-core/src/application/render/renderers/TransientView/TransientDrawingView.ts
=> Backmerge: #6621 – Fix monomer snapping wiping monomer labels

packages/ketcher-core/src/domain/entities/Nucleoside.ts, packages/ketcher-core/src/domain/entities/Nucleotide.ts, packages/ketcher-core/src/domain/helpers/rna.ts
=> #6609 - System creates ambiguous RNA nucleotides instead of DNA ones in case of DNA antisense stand creation

packages/ketcher-core/src/application/render/renderers/sequence/SequenceViewModel/SequenceViewModel.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts, packages/ketcher-core/src/domain/entities/index.ts, packages/ketcher-macromolecules/src/components/contextMenu/SequenceItemContextMenu/SequenceItemContextMenu.tsx, packages/ketcher-macromolecules/src/components/modal/ConfirmationDialog/ConfirmationDialog.tsx, packages/ketcher-macromolecules/src/components/modal/modalContainer/types.ts
=> #6615 - Missing warning message when deleting all hydrogen bonds between two chains

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #6619 - System doesn't create antisense phosphate if it sistuated to the left from nubleotide

packages/ketcher-core/src/domain/entities/Nucleoside.ts, packages/ketcher-core/src/domain/entities/Nucleotide.ts, packages/ketcher-core/src/domain/helpers/rna.ts
(cherry picked from commit 18b77cfbc85fba3826041cc0fef3b9670b7436c2)
=> Backmerge: #6609 - System creates ambiguous RNA nucleotides instead of DNA ones in case of DNA antisense stand creation

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6443 - System allow to select single antisense symbol that causes an error if it got deleted

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher to 3.2.0-rc.2

packages/ketcher-macromolecules/src/components/contextMenu/SelectedMonomersContextMenu/SelectedMonomersContextMenu.tsx, packages/ketcher-macromolecules/src/components/contextMenu/SelectedMonomersContextMenu/helpers.ts, packages/ketcher-macromolecules/src/components/contextMenu/SequenceItemContextMenu/SequenceItemContextMenu.tsx
=> #6695 - Unable to create antisense RNA/DNA chain in case of multipal сhain selection (if not eligable for antisense chain selected)

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> #6709 - Unable to paste HELM from clipboard to the canvas. System throws an error: Convert error! option manager: Property "sequence-type" not defined

example-ssr/package.json, package-lock.json, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
=> #6723 – Forbid moving sequence nodes and snapping by select rectangle tool

example-ssr/package.json, package-lock.json, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
=> Backmerge: #6723 – Forbid moving sequence nodes and snapping by select rectangle tool

packages/ketcher-core/src/domain/helpers/rna.ts
=> #6729 - Create RNA/DNA Strand doesn't work for B, K, Y and S ambiguous bases

packages/ketcher-core/src/application/editor/tools/Clear.ts
=> #6759 – Add pruning of the remaining transient views on clear canvas button click

packages/ketcher-core/src/application/editor/tools/Clear.ts
=> Backmerge: #6759 – Add pruning of the remaining transient views on clear canvas button click

example-ssr/package-lock.json, example-ssr/package.json, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 3.1.0

packages/ketcher-core/__tests__/application/editor/tools/SelectRectangleTool.test.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts, packages/ketcher-core/src/typing.d.ts
=> Backmerge: #6813 – Click on monomer selection area causes an exception

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> #6712 - Adding RNA/DNA before empty space in sence sequense causes exception and broken canvas

packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
=> Backmerge: #6712 - Adding RNA/DNA before empty space in sence sequense causes exception and broken canvas

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher to 3.2.0-rc.5

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6776 - Phosphate does not appear immediately when added via keyboard in SYNC mode

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #6776 - Phosphate does not appear immediately when added via keyboard in SYNC mode

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> #6824 - Unable to delete multiple sequences at once via right-click menu in Sequence mode

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
=> Backmerge: #6824 - Unable to delete multiple sequences at once via right-click menu in Sequence mode

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 3.3.0-rc.2

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump version to 3.3.0 rc.3

packages/ketcher-core/src/domain/entities/BaseMonomer.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/monomerToDrawingEntity.ts, packages/ketcher-core/src/domain/types/monomers.ts
=> #6762 - System shows natural analog monomer as modified if source mol file contains only 3-letters natural analog name

ketcher-autotests/tests/pages/molecules/TopRightToolbar.ts, ketcher-autotests/tests/pages/molecules/canvas/AboutDialog.ts, ketcher-autotests/tests/specs/API/view-only-mode.spec.ts, ketcher-autotests/tests/specs/Bugs/ketcher-3.1.0-bugs.spec.ts, ketcher-autotests/tests/specs/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts, ketcher-autotests/tests/specs/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher2.spec.ts, ketcher-autotests/tests/specs/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher4.spec.ts, ketcher-autotests/tests/specs/Macromolecule-editor/Rectangle-Selection-Tool/rectangle-selection-tool.spec.ts, ketcher-autotests/tests/specs/Macromolecule-editor/Sequence-Mode/new-sequence-representation1-1.spec.ts, ketcher-autotests/tests/specs/User-Interface/About/about-ui.spec.ts, ketcher-autotests/tests/utils/clicks/index.ts
=> Autotests: #6898 - autotests create toprighttoolbar page object

packages/ketcher-core/src/application/editor/MacromoleculesConverter.ts, packages/ketcher-core/src/application/render/renderers/AtomRenderer.ts, packages/ketcher-core/src/application/render/renderers/BondRenderer.ts, packages/ketcher-core/src/domain/entities/CoreAtom.ts, packages/ketcher-core/src/domain/entities/CoreBond.ts, packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts, packages/ketcher-core/src/domain/entities/atom.ts, packages/ketcher-core/src/domain/entities/bond.ts, packages/ketcher-core/src/domain/entities/types.ts
=> #6271 – Support for stereo labels aka sip labels in macromolecules mode

ketcher-autotests/tests/specs/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useMonomerExpansionHandlers.ts, packages/ketcher-react/src/script/ui/views/components/ContextMenu/menuItems/MacromoleculeMenuItems.tsx
=> #7008 – Support of expanded monomer options doesn't work if monomer loaded from file/clipboard

packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> 6294 hiding toolbar buttons doesnt also hidedisable the corresponding keyboard shortcut

packages/ketcher-core/src/domain/services/struct/structService.types.ts, packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
=> #7039 – App crashes when adding Ambiguous Amino Acids to peptide sequence with open Calculate Properties window

packages/ketcher-core/src/domain/services/struct/structService.types.ts, packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
=> Backmerge: #7039 – App crashes when adding Ambiguous Amino Acids to peptide sequence with open Calculate Properties window

packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-macromolecules/src/components/LeftMenuComponent/LeftMenuComponent.tsx, packages/ketcher-macromolecules/src/components/TopMenuComponent/TopMenuComponent.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/ZoomControls.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/ZoomInput.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/helpers.ts, packages/ketcher-macromolecules/src/components/macromoleculeProperties/CalculateMacromoleculePropertiesButton.tsx, packages/ketcher-macromolecules/src/state/common/editorSlice.ts
=> #7015 – Alt+C / Option+C hotkey does not open the “Calculate Properties” window

packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-macromolecules/src/Editor.tsx, packages/ketcher-macromolecules/src/components/LeftMenuComponent/LeftMenuComponent.tsx, packages/ketcher-macromolecules/src/components/TopMenuComponent/TopMenuComponent.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/ZoomControls.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/ZoomInput.tsx, packages/ketcher-macromolecules/src/components/ZoomControls/helpers.ts, packages/ketcher-macromolecules/src/components/macromoleculeProperties/CalculateMacromoleculePropertiesButton.tsx, packages/ketcher-macromolecules/src/state/common/editorSlice.ts
=> Backmerge: #7015 – Alt+C / Option+C hotkey does not open the “Calculate Properties” window

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
=> #7018 – Unable to clear monomer selection after switching browser tabs

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts
=> Backmerge: #7018 – Unable to clear monomer selection after switching browser tabs

packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
=> #7026 – Calculate properties for peptides are missing in case of mixed peptide and RNA/DNA chain

packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
Issue => https://github.com/epam/ketcher/issues/7032
=>  #7032 - Ketcher allows to make changes in sequence while being in nucleotide modification mode

packages/ketcher-core/src/application/formatters/types/ket.ts, packages/ketcher-core/src/domain/serializers/ket/fromKet/monomerToDrawingEntity.ts, packages/ketcher-core/src/domain/serializers/ket/helpers.ts, packages/ketcher-core/src/domain/serializers/ket/ketSerializer.ts, packages/ketcher-core/src/domain/types/monomers.ts
=> Backmerge: #7062 – Rotation is incorrect upon exporting transformed monomer to SVG or PNG

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated Ketcher to v3.4.0-rc.2

ketcher-autotests/tests/specs/Macromolecule-editor/Rectangle-Selection-Tool/rectangle-selection-tool.spec.ts
=> #6928 - Autotests: convert tests in rectangle-selection-tool.spec.ts from isolated execution to clear canvas execution

packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx
=> #7023 - Hydrophobicity section is missing tooltip icon and description

packages/ketcher-react/rollup.config.js
=> Fixed ketcher-macromolecules styles import handling in ketcher-react

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/application/editor/tools/SelectRectangle.ts, packages/ketcher-core/src/utilities/dom.ts, packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx, packages/ketcher-macromolecules/src/components/shared/textInputField/TextInputField.tsx, packages/ketcher-macromolecules/src/hooks/useRecalculateMacromoleculeProperties.ts, packages/ketcher-macromolecules/src/state/common/editorSlice.ts
=> #7118 - Cannot edit concentration values of unipositive ions and oligonucleotides in Calculate Properties

packages/ketcher-macromolecules/src/Editor.tsx
=> #7178 The tooltip appears behind the context menu options

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 3.4.0-rc.7

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Updated ketcher to 3.5.0-rc.3

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 3.3.0

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 3.4.0

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 3.5.0-rc.5

packages/ketcher-macromolecules/src/components/Ruler/RulerArea.constants.ts, packages/ketcher-macromolecules/src/components/Ruler/RulerArea.tsx, packages/ketcher-macromolecules/src/components/Ruler/RulerScale.tsx
=> #7209 -  The ruler is limited to 190 divisions 

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump Ketcher version to 3.5.0-rc.6

ketcher-autotests/tests/pages/constants/EnhancedStereochemistry/Constants.ts, ketcher-autotests/tests/pages/molecules/canvas/EnhancedStereochemistry.ts, ketcher-autotests/tests/specs/Bugs/ketcher-2.27.0-bugs.spec.ts, ketcher-autotests/tests/specs/File-Management/Open-And-Save-Files/CDXML-Enhanced-Stereochemistry/cdxml-enhanced-stereochemistry.spec.ts, ketcher-autotests/tests/specs/Indigo-Tools/Enhanced-Stereochemistry/enhanced-stereochemistry.spec.ts, ketcher-autotests/tests/specs/Structure-Creating-&-Editing/Atom/Atom-Properties/atom-properties.spec.ts, ketcher-autotests/tests/specs/Structure-Creating-&-Editing/SMARTS-attributes/utils.ts, ketcher-autotests/tests/specs/User-Interface/Right-Click-Menu/right-click.spec.ts, packages/ketcher-react/src/script/ui/component/form/form/form.jsx, packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo/enhancedStereo.tsx
=> Autotests: #7302 create page object for enhanced stereochemistry window

README.md
=> #7381 - Create documentation for 'change' event subscription

packages/ketcher-macromolecules/src/components/DragGhost/DragGhost.tsx, packages/ketcher-macromolecules/src/components/DragGhost/svg/GhostRnaPreset.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/hooks/useLibraryItemDrag.tsx
=> #7371 – Mouse cursor doesn't positioned at the top left corner of preset

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Update Ketcher to 3.6.0-rc.2

example/src/App.tsx, package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-macromolecules/src/components/macromoleculeProperties/MacromoleculePropertiesWindow.tsx, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
- enabled strict mode
- added safety checks
=> #7568 - Unable to use Ketcher in the most basic of Vite projects

.github/workflows/run-tests-popup.yml, .github/workflows/run-tests.yml, ketcher-autotests/playwright.config.ts
=> Autotests: #6945 - Merged reports attempt

example/config/webpack.config.js, example/src/App.tsx, example/src/ClosableApp.tsx, example/src/DuoApp.tsx, example/src/PopupApp.tsx, packages/ketcher-macromolecules/src/hooks/stateHooks.ts, packages/ketcher-macromolecules/src/hooks/useLoading.ts
- enabled strict mode in each mode
- added bypass of error related to getting removed ketcher instance
- added closable app chunk
=> Backmerge: #7568 - Unable to use Ketcher in the most basic of Vite projects

packages/ketcher-core/src/application/render/restruct/reatom.ts
=> #7222 - Incorrect leaving group atoms for expanded monomers

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-macromolecules/src/components/DragGhost/DragGhost.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/hooks/useLibraryItemDrag.tsx, packages/ketcher-react/src/constants.ts
=> #7513 - "Ghost image" doesn't positioned below mouse cursor if dragged from Library to canvas in popup mode

ketcher-autotests/tests/specs/File-Management/Open-And-Save-Files/MOL-Files/mol-files-export-import-query-features.spec.ts
=> Autotests: #7464 - autotests transform isolated test execution to clear canvas test execution for mol files export import query featuresspects

packages/ketcher-core/src/application/formatters/types/ket.ts, packages/ketcher-core/src/domain/helpers/monomers.ts, packages/ketcher-react/src/script/editor/Editor.ts
=> #7577 – "Create a monomer" button becomes active for disconnected structures

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetItem/RnaPresetItem.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/MonomerItem.tsx
=> #7531 - Arrow icon appears in Sequence mode, violating requirement for Snake and Flex modes only

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetItem/RnaPresetItem.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/MonomerItem.tsx
=> Backmerge: #7531 - Arrow icon appears in Sequence mode, violating requirement for Snake and Flex modes only

packages/ketcher-core/src/application/editor/Editor.ts, packages/ketcher-core/src/domain/helpers/monomers.ts, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetGroup/__snapshots__/RnaPresetGroup.test.tsx.snap, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetItem/RnaPresetItem.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryGroup/__snapshots__/MonomerGroup.test.tsx.snap, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/MonomerItem.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/shared.ts, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/styles.ts, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryList/__snapshots__/MonomerList.test.tsx.snap
=> #7539 - No tooltip shown and invalid attachment allowed when adding a monomer without R1 to selected monomer with free R2

packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/hooks/useLibraryItemDrag.tsx
=> #7423 - It is possible to drag monomer from library and drop it to sequence canvas

packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetGroup/RnaPresetGroup.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/RnaPresetItem/RnaPresetItem.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryGroup/MonomerGroup.tsx, packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryItem/MonomerItem.tsx, packages/ketcher-macromolecules/src/components/preview/helpers.ts
=> #7562 - Tooltip overlaps monomers when hovering over arrow button on monomer card

.github/workflows/run-tests-popup.yml, .github/workflows/run-tests.yml, ketcher-autotests/package.json, ketcher-autotests/playwright.config.ts, ketcher-autotests/tests/specs/Chromium-popup/API/api-set-get-molecule.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/API/view-only-mode.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-2.26.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-2.27.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-2.28.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-3.0.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-3.1.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-3.2.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-3.3.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Bugs/ketcher-3.4.0-bugs.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Indigo-Tools/Aromatize-Dearomatize/aromatize-dearomatize.spec.ts, ketcher-autotests/tests/specs/Chromium-popup/Molecules-editor/star-atom.spec.ts
=> Autotests: #7672 autotests update configuration changes use testmatchtestignore for filtering fix html report serve set explicit viewport

packages/ketcher-core/src/application/editor/modes/BaseMode.ts, packages/ketcher-react/src/script/ui/component/cliparea/cliparea.jsx
=> #7606 – Pasting text into Symbol or Name fields in Monomer Wizard triggers unrelated "Convert error"

demo/src/components/ControlsCard.tsx
=> Fixed types in demo package

packages/ketcher-react/src/script/editor/Editor.ts
=> #7684 – Only selected atoms connected with bonds should be taken into account on monomer creation

packages/ketcher-react/src/script/editor/Editor.ts
=> Backmerge: #7684 – Only selected atoms connected with bonds should be taken into account on monomer creation

ketcher-autotests/tests/specs/Structure-Creating-&-Editing/SMARTS-attributes/Bond-attributes/bond-attributes.spec.ts
=> Autotests: 7487 Transform isolated test execution to clear canvas test execution for bond-attributes.spec.ts

ketcher-autotests/tests/specs/Templates/Functional-Groups/functional-groups.spec.ts
=> Autotests: 7488 Transform isolated test execution to clear canvas test execution for functional-groups.spec.ts

README.md
=> #7384 - Create documentation for hiding toolbar buttons

ketcher-autotests/tests/specs/Indigo-Tools/Calculated-Values-Tool/calculated-values.spec.ts, ketcher-autotests/tests/utils/common/helpers.ts, packages/ketcher-macromolecules/src/components/modal/Error/Error.tsx, packages/ketcher-react/src/components/InfoModal/InfoModal.tsx
=> Autotests: 7468 Transform isolated test execution to clear canvas test execution for calculated-values.spec.ts

ketcher-autotests/tests/specs/Indigo-Tools/Enhanced-Stereochemistry/enhanced-stereochemistry.spec.ts, ketcher-autotests/tests/specs/Indigo-Tools/Layout/layout.spec.ts, ketcher-autotests/tests/specs/Structure-Creating-&-Editing/Atom/Atom-Tool/atom-tool.spec.ts
=> Autotests: 7470 Transform isolated test execution to clear canvas test execution for enhanced-stereochemistry.spec.ts

packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/views/components/AttachmentPointEditPopup/AttachmentPointEditPopup.tsx, packages/ketcher-react/src/script/ui/views/components/ContextMenu/hooks/useMakeLeavingGroupAtomMenuItem.tsx
=> Backmerge: #7808 – Crash on create monomer dialog open: Uncaught ReferenceError: process is not defined

packages/ketcher-react/src/script/editor/Editor.ts
=> #7846 - Connection between created monomer and the rest of molecule got lost after monomer creation

packages/ketcher-core/src/application/render/raphaelRender.ts, packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/domain/helpers/attachmentPointCalculations.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/views/components/MonomerCreationWizard/MonomerCreationWizard.tsx
=> #7806 – Problematic points are not highlighted in red when validation is failed

packages/ketcher-core/src/application/render/raphaelRender.ts, packages/ketcher-core/src/application/render/restruct/reatom.ts, packages/ketcher-core/src/domain/helpers/attachmentPointCalculations.ts, packages/ketcher-react/src/script/editor/Editor.ts, packages/ketcher-react/src/script/ui/views/components/MonomerCreationWizard/MonomerCreationWizard.tsx
=> Backmerge: #7806 – Problematic points are not highlighted in red when validation is failed

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> - updated ketcher to 3.8.0-rc.3

packages/ketcher-react/src/script/editor/Editor.ts
=> Backmerge: #7846 - Connection between created monomer and the rest of molecule got lost after monomer creation

package-lock.json, packages/ketcher-core/package.json, packages/ketcher-macromolecules/package.json, packages/ketcher-react/package.json, packages/ketcher-standalone/package.json
=> Bump version to 3.8.0-rc.4

package-lock.json, packages/ketcher-core/src/application/editor/editorEvents.ts, packages/ketcher-core/src/application/editor/modes/SequenceMode.ts, packages/ketcher-core/src/application/render/restruct/restruct.ts, packages/ketcher-core/src/utilities/keynorm.ts, packages/ketcher-react/package.json, packages/ketcher-react/src/components/Dialog/Dialog.tsx, packages/ketcher-react/src/script/ui/action/tools.js, packages/ketcher-react/src/script/ui/action/zoom.js, packages/ketcher-react/src/script/ui/dialog/AbbreviationLookup/AbbreviationLookup.tsx, packages/ketcher-react/src/script/ui/state/hotkeys.test.tsx, packages/ketcher-react/src/script/ui/state/hotkeys.ts
=> #7979 – Pressing right Command key on Mac causes errors in DevTool Console (left Command works fine)
